### ISSUE TITLE
Migrate RocketChat to OCP 4

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#101]
Description:
Rocket.Chat deployment needs to be migrated from the pathfinder cluster to the silver (ocp4) cluster.

- [x] Change Rocket.Chat endpoints from chat.pathfinder.gov.bc.ca -> chat.developer.gov.bc.ca
- [x] Request and implement SSL certificates; send iStore to other team member as backup.
- [x] Create dev instances on Silver;
- [ ] Create test instances on Silver;
- [x] Create prod instances on Silver;
- [x] State/service migration steps/plans
- [ ] Shutdown pathfinder deployed rocketchat instances (add temporary forwarding of rc services?)

Definition of Done:
Platform Services Rocket.Chat migration to the silver cluster is complete, with legacy (pathfinder) deployments offline.

**Comment by jleach** [comment]
All the new RC material, including the helper app Reggie are located [here](https://github.com/bcgov/rocketchat).

**Comment by jleach** [comment]
The data migration plan. Run time ~ 54min.

# Data Migration

### Prerequisites

1. Destroy and rebuild empty mono instance on Silver (without dry-run data);

### Dump

1. oc logon to the source cluster;
2. oc project e5imao-prod
3. oc scale dc/rocketchat --replicas=0
4. oc rsync data-pump:/uploads/ uploads/
5. oc port-forward service/mongodb 27017
6. docker run -it --rm --name mongo -v $(pwd):/data mongo:3.6 /bin/bash
7. time mongodump -vvv --uri="mongodb://XXX:YYYY@host.docker.internal:27017/rocketdb?replicaSet=rs0" --gzip --archive=/data/dump-prod-202101ZZ.gz
8. oc scale statefulset/mongodb --replicas=0

real	  25m4.985s
user	  1m48.797s
sys.   1m39.072s

### Restore

1. oc logon to the destination cluster
2. oc project 6e2f55-prod
3. oc port-forward service/mongodb 27017
4. docker run -it --rm --name mongo -v $(pwd):/data mongo:3.6 /bin/bash
5. time mongorestore  --uri="mongodb://XXX:YYYY@host.docker.internal:27017/rocketdb?replicaSet=rs0" -d rocketdb  --gzip --archive=/data/dump-prod-202101ZZ.gz
6. oc rsync uploads/ data-pump:/uploads/
7. oc scale deployment/rocketchat-server --replicas=1
8. Test on Web, Mobile and Desktop.

real	 29m31.774s
user	 0m46.305s
sys   0m19.194s

### Maintenance Proxy

➜  rocketchat git:(master) ✗ oc get routes
NAME                      HOST/PORT                                     PATH   SERVICES     PORT       TERMINATION     WILDCARD
hubot-prod            hubot-prod-e5imao-prod.pathfinder.gov.bc.ca          hubot-prod   api        edge/Redirect   None
rocketchat             chat.pathfinder.gov.bc.ca                            rocketchat   3000-tcp   edge/Redirect   None
rocketchat-prod    chat-prod-test.pathfinder.gov.bc.ca                  rocketchat   3000-tcp   edge/Redirect   None

1. oc logon to the source cluster
2. oc project e5imao-prod
3. oc delete route rocketchat
4. oc process -f openshift/templates/maintenance-proxy.yaml -p DESTINATION_HOST_NAME="chat.developer.gov.bc.ca" -p SOURCE_HOST_NAME="chat.pathfinder.gov.bc.ca" | oc apply -f -
5. Test on Web, Mobile and Desktop.
