### ISSUE TITLE
Operational Automation Refactoring Planning

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#105]
As an operator of the existing platform, I would like to understand how my day 2 operations tasks will change with the new environment. A lab environment should be used to test out each of the standard operational tasks and learn how they need to be refactored for the new environment. 
- [ ] Initial collection of day 2 ops tasks
- [ ] Document / outline each task and the anticipated changes
- [ ] Create an issue for each ops task to track it's refactoring

**Comment by StevenBarre** [comment]
- Upgrades
- sos reports
- troubleshooting / reading system logs
- API Audit logs
- Router certificate re-key
- Master/Node/ETCD certs regeneration
- Build/Deploy/Image pruning
