### ISSUE TITLE
Create Ingress design

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#109]

**Comment by StevenBarre** [comment]
I believe this was covered by https://github.com/BCDevOps/OpenShift4-RollOut/blob/master/docs/F5-vs-HAProxy.md

@stewartshea @jefkel can we close this?

**Comment by stewartshea** [comment]
I don't think so... This isn't a comprehensive enough and doesn't actually
show what the end-state is. A dedicated document that outlines the each
active environment and exactly how teams are to leverage ingress is what I
would like to see out of this ticket.
--
Shea Stewart (He/Him), Partner
Arctiq: Intelligent Architecture
shea.stewart@arctiq.ca
+1-647-972-5191
http://www.arctiq.ca
Book at meeting here: https://x.ai/calendar/sheastewart

Why I Put Pronouns on my Email Signature
<https://medium.com/gender-inclusivit/why-i-put-pronouns-on-my-email-signature-and-linkedin-profile-and-you-should-too-d3dc942c8743>

**Comment by mitovskaol** [comment]
As we switched to. Openshift 4 SDN, teams will leverage KNPs for controlling ingress traffic.
