### ISSUE TITLE
Complete briefing note 

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#115]
In order to continue with this project, a costing briefing note must be completed and presented Hosting Branch

**Comment by Joe-Craig** [comment]
After meeting with Todd, David Ell, Nainesh, et al. It was agreed that we would proceed as a project using a professional service request (T&M) and iStore orders for infrastructure to the end of Release 1. 

At that time we would have enough information to write the Brief Note and progress with a SCO.

**Comment by tosazuwa** [comment]
Hi @Joe-Craig , i am going to move this ticket back to the backlog and we can review when ready. I will be deleting the "parked" swim lane. Any ticket/activity we want to defer can sit in the backlog till we are ready to execute. Just to avoid having multiple swim lanes that wont be used often

**Comment by Joe-Craig** [comment]
BN was complete and sent to Hosting Branch. They will present to BC DEvExchange and give the OK to move forward to SCO.
