### ISSUE TITLE
Create Professional Services Order iStore request 

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#116]
A PSO iStore order is required for DXC to conduct these services. 

We will need to determine the initial commitment expectation of hours based on our sprint structure.

**Comment by kelpisland** [comment]
I have a meeting tomorrow with David to fine tune the expectations and scope of the Prof Serves ask. Stay tuned.

**Comment by tosazuwa** [comment]
Hi @kelpisland , @lukegonis ,do we have an i-store for this pls?

**Comment by tosazuwa** [comment]
i-store order now recieved by @Joe-Craig . I-store #1003935
