### ISSUE TITLE
Create iStore Request for VMs

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#119]
42 VMs ordered
- 10 x 3 Cluster Environments (K-Prod, K-lab, C-lab)
- 9 Netapp VMs
- 3 small bootservice VMs

- [x] Submit iStore requests for VMs
- [x] Confirm Available capacity for Release 1
- [x] Confirm Approved iStore orders in DXC

**Comment by jefkel** [comment]
1 of 4 separated iStore request #s has been seen on the DXC side, still waiting for the others to appear.

**Comment by sbarre-esit** [comment]
iStore numbers
- 1002583
- 1002590
- 1002594
- 1002870

**Comment by jefkel** [comment]
Update: Service Desk is re-submitting the iStore request with 35 VMs broken into groups of 5, I will update once I have new iStore #'s to track.  (existing order for the 3 BootService VMs has gone through)

**Comment by jefkel** [comment]
Updated iStore orders for tracking, and moved to blocked - pending orders confirmed in DXC system.

Orders confirmed through to DXC order system:
- [x] 1002870 - REQ0040749 3 x bootservice VMs (1 CORE, 6GB RAM, 50GB storage)
- [x] 1004120
- [x] 1004122
- [x] 1004123
- [x] 1004127
- [x] 1004132
- [x] 1004136
- [x] 1004138
- [x] 1004141
- [x] 1004143 - REQ0041280 3 x NetApp nodes

**Comment by jefkel** [comment]
@sbarre-esit could you confirm whether the orders/quantities of vms in the last round of iStore requests matches the release 1 spreadsheet?
