### ISSUE TITLE
DXC Professional Service Agreement complete

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#122]
- [x] Professional Services agreement sent to Hosting Branch for approval

- [x] DXC to create high level SOW and send to Hosting branch

- [x] Hosting branch to approve i-store request and send to Todd for approval

- [x] i-store request approved by Todd

- [x] Hosting branch/DXC confirms PSA sent/recieved   

- [x] PSA order is in effect, and the services and billing to DevOps to begin

**Comment by tosazuwa** [comment]
The Professional Services order is being expedited. The contracts team will confirm the availability of the professional services resources no later than end of day Monday Jan 20th

**Comment by Joe-Craig** [comment]
@tosazuwa Could you clarify, Is that the DXC contracts team or the Provinces one? Not sure what the comment about availability of resources relates to. Thanks

**Comment by Joe-Craig** [comment]
@tosazuwa  Any update on this?

**Comment by StevenBarre** [comment]
@tosazuwa can you please provide a date when the PSA will be signed?

**Comment by tosazuwa** [comment]
I sent an email to Leanne. Still waiting on her response. I usually apply the 24 hour rule before i send a reminder:)

**Comment by tosazuwa** [comment]
Update from Leanne Jan 29th- Hosting Branch:

Yes, we received a SOW and it meets our needs. I’ve approved the iStore quote to move forward for Todd to apply his EA. (I’m guessing he is the EA). 

Once that is completed, the order is in effect, and the services and billing to DevOps will begin. 

Cheers,
Leanne
