### ISSUE TITLE
Define/design provisioning solution for namespace/resource provisioning, user onboarding and access management

### ISSUE THREAD

**Issue by sheaphillips** [BCDevOps/OpenShift4-RollOut#124]
As part of ongoing platform improvements in user experience, operability and observability, we need to implement an improved solution for handling request for resources (OCP namespace, keycloak realms, etc.) and user access management.  Currently this process is largely manual.

**Comment by mitovskaol** [comment]
Project provisioning moved to Project Registry, we are also looking to automate GitHub org membership with Just Ask! app.
