### ISSUE TITLE
Design Storage Topography Physical/virtual

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#127]
Orders in this fiscal year

**Comment by StevenBarre** [comment]
Storage team would like to know the expected performance required for PROD. IOPS, MB/s, Latency, and total storage. This will help them better plan for sizing and capacity.

**Comment by jefkel** [comment]
High level targets for the Cluster storage solution:

Cluster provisioned storage is designed for a mixed workload with the expectation of high performance.  The idea is to provide SSD level performance for a wide variety of workload types.

Storage Sizing expectations are to be consuming ~30-40 TB within the first year.  Planned growth of the cluster will approximately double that capacity.

**Comment by jefkel** [comment]
For specific performance from an IPS/MB/s, Latency we can look at the current CNS provided storage and use the performance numbers for IOPS, MB/s, Latency as a starting point.

**Comment by tosazuwa** [comment]
@DanDeane  to follow up with Storage team and providing some comments this afternoon

fyi!: 
 * Order netapp licenses in larger chunks (10/20/40 TB quarterly) and then order SAN in smaller chunks as needed to keep monthly costs down. 
* Is there a rebate plan for when we switch to physical? (Jim knudson? (netapp sales rep)

**Comment by StevenBarre** [comment]
While standard RH Gluster Server does have a way to do some [monitoring](https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.5/html-single/monitoring_guide/index) it isn't implemented in CNS. So I don't have a good way to get current IOPS, MB/s, Latency.

I've made a rough estimate based on `iostat` that the average MB/s is 12 with a peak of around 100. But I don't have a good way to measure IOPS or Latency.

I've provided the data I have to the storage team.

**Comment by jefkel** [comment]
Can this ticket be closed/completed? @Joe-Craig @sbarre-esit

**Comment by StevenBarre** [comment]
@jefkel I'm not sure? What is our Definition of Done here? I think we're still waiting on a decision on physical vs virtual for the prod clusters?

I think that decision is waiting on quotes from our Storage team, and then David Ell to see the cost difference of physical to virtual.

**Comment by Joe-Craig** [comment]
ROM pricing for both physical and virtual have been supplied. David has questions regarding what upstream impacts have been considered.

New action on @Joe-Craig and @Scott-McWilliams to review the current data center infrastructure and suggest upgrades to move it towards the 40/100 model.
