### ISSUE TITLE
Procure Software Entitlements for Cluster Add-Ons

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#128]
Contract amendments for the following; 
- [x] Sysdig
- [x] Aporeto
- [x] Aqua 
- [x] Artifactory?
- [x] Vault

**Comment by tosazuwa** [comment]
Had a conversation with @lukegonis . We will be speaking with someone in Finance/Procurement in the next few weeks, for the contracts modification process

**Comment by tosazuwa** [comment]
Hi Team. Can we add updates to the ticket please?

**Comment by stewartshea** [comment]
No final numbers yet. This is in progress. Waiting on some detail from @jefkel before we can provide some quotes to move forward with contract amendments

**Comment by stewartshea** [comment]
Numbers are confirmed and requests are put out for pricing.

**Comment by stewartshea** [comment]
I have pricing for Sysdig, Artifactory, and most of the Vault pieces; waiting on the others.

**Comment by tosazuwa** [comment]
The OCP 4 Project has committed funding to proceed with software entitlements licenses for 2019/2020  fiscal. @mitovskaol leading the procurement effort.

**Comment by stewartshea** [comment]
Sysdig has agreed to a 30 day extension... we need to get these procurements moving along quickly.

**Comment by jefkel** [comment]
All software license procurements  have been awarded and are working through the final procurement process and will be available as invoices close.

**Comment by stewartshea** [comment]
This is all complete.
