### ISSUE TITLE
Redeploy KLAB Cluster into the SDN Compartment

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#13]
**Describe the issue**
Deploy KLAB with all the new SDN networking.

**Which Sprint Goal is this issue related to?**
Initial deployment of KLAB in SDN

**MVP**
KLAB cluster available to the Platform Experience Team for functional testing on the cluster.

**Definition of done Checklist (where applicable)**
- [x] Ensure ESX hosts have all needed vlans trunked to them
- [x] Have DXC/ATT configure F5 Virtual Edition with internal and external vlans
- [x] Have DXC/ATT configure F5 Virtual Edition with NAT gateway
- [x] Deploy OCP onto nodes
- [x] Run cluster config automation
- [x] Verify basic cluster operations (Storage provisioning, network access, basic application deployment)

**Comment by StevenBarre** [comment]
It's alive https://console-openshift-console.apps.klab.devops.gov.bc.ca/ !

Still need to run the cluster config automation. Don't have SSH access to my util server yet and working over the VMware Console is a bit of a pain. Network is fixing the mgmt network as a top priority though.

**Comment by jefkel** [comment]
Pulled Aporeto install out of this task to better focus on MVP cluster availability for functional testing.

Added a task to validate the base cluster functionality as a checklist item (my thought is to block completion until workarounds or fixes for storage provisioning are available)
