### ISSUE TITLE
Update OpenShift 4 Infrastructure List

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#131]
https://docs.google.com/spreadsheets/d/1aRbWq3quyUZumMSkc6I12WiSq8LuTbp1IHlhZpo9kHU/edit?usp=drive_web&ouid=106502627101184943364

- [x] List Updated with host details (cores/RAM/Storage needs)
- [x] Confirm Data Centre Virtual Capacity
- [x] Confirm Data Centre Physical Capacity (for Release 2 targets)

**Comment by jefkel** [comment]
List Updated and being reviewed by Dan/Steven

**Comment by DanDeane** [comment]
I have confirmed virtual capacity for release 1.

**Comment by jefkel** [comment]
@DanDeane are you able to confirm physical space available based on the release 2 worksheet?

**Comment by DanDeane** [comment]
yes @jefkel , @sbarre-esit and I met with our datacenter team on Friday and they have confirmed that there should be no issues for HW.
