### ISSUE TITLE
Discussion on Storage Platform design

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#137]
To discuss:
What criteria do we want to use to decide if we go physical or not?
Pro and cons for either Platform based on our requirements?

Tolu to book meeting for week of Dec 2nd, 9am-10am

**Comment by jefkel** [comment]
Meeting completed with following outcomes:
- Expected that Capital Cost budget will be available and preferred over ongoing operational costs for the design of the solution.
- Agreed to maintain and report on the performance of the 3.11 Virtual NetApp as additional load is added. The performance metrics of the back end to be reported by DXC as requested.
- On demand performance tests by Wade to help track Development team's perceived performance. (every 2 or 4 weeks) (results to be tracked in trello ticket for now)
- Performance is expected to drop off as additional load moves onto the NetApp storageClasses, monitoring is to help track how much it changes. (no definitive performance requirements as the current implementation is primarily built to resolve capacity issues)
- Bruce/DXC to document hardware NetApp solution design and provide ballpark cost.
- Ballpark operational costs for alternate SAN backed NetApp Virtual would be based off of Tier-1: 0.90/GB/Month, Tier-0: 3.00/GB/Month
T1: ~55k/month,  T0: 180k per month (60TB of SAN for 30TB usable NetApp OnTap provisioned storage) 
- 30TB of consumed, usable storage in Kamloops expected within first year, planning for double that to last for the first 2 years. (60TB)
- 1/3 of the Kamloops capacity (10TB) will be targeted for Calgary for the first year, 20TB as the target capacity for 2 years.
- Specific provisionable storageClass to be targeted for enterprise backup integration.

**Comment by tosazuwa** [comment]
Hi @jefkel , can we call this done? Thanks for capturing the notes

**Comment by jefkel** [comment]
With the update from the last storage review, it looks like we are going to go ahead with both the netapp Virtual orders (to be in place by early January as storage team is short-staffed for the rest of the month) as well as the physical netapp orders ready to go by the first week of January.  The timeline will be extremely tight between a decision re: physical vs virtual and needing to get any orders sent.
