### ISSUE TITLE
Reserve Cluster and Service nets

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#139]
The OpenShift SDN requires two ranges that do not overlap with any networks a pod might route too elsewhere in the datacenter.

Each host needs a subnet big enough to give an IP to each pod. Currently kublet limits to 250 pods per host but our RH TAM suggests this may change in the future. So we'll get a /23 per host. We are very unlikely to have more than 128 nodes in a cluster so a /16 ClusterNet should be sufficient to provide all the hosts with a /23.

Each k8s service needs its own IP that comes from the ServiceNet. A /16 should be sufficient to give every pod its own service.

We can use the same ClusterNet and ServiceNet in all our clusters as they won't ever be talking to each other over the SDN.

**Comment by stewartshea** [comment]
I'm scoping around 180 pods / host at the moment @sbarre-esit ; I'm not thinking I'd like to increase above that based on our current node size. Just an FYI.

**Comment by StevenBarre** [comment]
@stewartshea ya it's unlikely we'd need more than a /24 per host, but its not something you can change after the cluster is built, so better to future proof ourselves. I don't think a /17 is that much easier to find compared to a /16 either.

**Comment by StevenBarre** [comment]
Ordered via RITM0048337. Moving to blocked waiting on the Network team to provision.

**Comment by StevenBarre** [comment]
Network team advises us this is something we need to ask the Province for. @DanDeane is going to talk to David Ell about getting some reserved private ranges.

**Comment by DanDeane** [comment]
Have spoken with Scott McWilliams regarding this as he is the entry way into all conversations with David from the AdvSol perspective and he is drafting and sending a note to David to get this going as we speak / type.

**Comment by DanDeane** [comment]
Blocked by network team for production network segments.  ETA 2 - 3 weeks.  I will be escalating today.
Good to go lab network segments in Kamloops only.

**Comment by tosazuwa** [comment]
@DanDeane  to meet with David Ell to discuss reserved private IP ranges

**Comment by DanDeane** [comment]
Correction here....Scott and Paul from our architecture and engineering group are talking with David Ell and Charles Middleton regarding these subnets.  No update today on their progress.

**Comment by StevenBarre** [comment]
Paul followed up with David Ell on Friday, no reply yet.

**Comment by tosazuwa** [comment]
Emailed David Ell today. He confirmed his team has submitted an iStore order to Charles’s team for the private IPs, and it’s making it through the process.  Should be done soon.

**Comment by StevenBarre** [comment]
Network ranges received!
