### ISSUE TITLE
DXC/Network Team to setup networks

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#140]
DXC/Network teams to set up all the networks. 

- [x]  subnets  to be configured in the infrastructure (switches, FW’s, F5 etc)

- [x]  vlans added to the trunks 

- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by kelpisland** [comment]
@DanDeane and I had a good conversation, internal escalation is underway. We should have an update on timing by EOD Friday

**Comment by tosazuwa** [comment]
@DanDeane, pkease update ticket based on Fridays conversation with @kelpisland

**Comment by DanDeane** [comment]
escalation complete with an ETA at the end of the this week [2019-12-13].  I will be following up today to ensure that the network team is on track.  I will provide updates once I have followed up with them.

**Comment by kelpisland** [comment]
Thanks @DanDeane - that’s good news!

**Comment by tosazuwa** [comment]
Thanks @DanDeane . You rock!

**Comment by DanDeane** [comment]
escalated and asked for an update this morning.

**Comment by StevenBarre** [comment]
Re: Prod and storage vlans #132 #133 #134 #135 from network team
> First, the subnets need to be configured in the infrastructure (switches, FW’s, F5 etc).  From that perspective, Calgary Lab is ready to go, Kamloops prod was supposed to be ready to go but it was not completed properly so I’ve sent updates to DXC.  The storage subnets are “in progress” and I need to get a status.  And, I need to check on Kamloops lab.  The second thing is to get the vlans added to the trunks which I hope to get done in the next few days (probably complete early next week).

**Comment by tosazuwa** [comment]
@sbarre-esit , can you add a bit more detail to the description above and add your specific tasks to this ticket? I have added a task list. This will help with trackability. I took a first stab at it

**Comment by DanDeane** [comment]
all storage networks provided and added to the clusters.  
Ready for Steven to begin building and for the additional NetApp clusters to be deployed.
