### ISSUE TITLE
Proactive monitoring of netapp Virtuals (tools in place as well as new tools from netapp) 

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#141]
Confirm and test netapp monitoring and escalation processes before going Live

- [ ] tools: existing and new netapp specific tools 
- [ ] roles: DXC has control, will need to present data as it's not exposed to other teams 
- [x] storage team monitors netapp (bruce/jody/etc), and that includes the VM appliance monitoring. (ESX team is monitoring the esx hosts for issues.) 
- [ ] alerts platform team (steven and william) 
- [ ] timely alerts to Todd for purchase, etc.. 
- [ ] communication:Alerting? (possibly into rocketchat?)

**Comment by StevenBarre** [comment]
- tools: existing and new netapp specific tools

Storage team has existing monitoring tools and SMTP alerts configured and tested.

- roles: DXC has control, will need to present data as it's not exposed to other teams

Storage team owns this and will create any needed INCs. MCS will pass the info on via RC same as we would for a SAN issue.
