### ISSUE TITLE
Virtual to Physical conversation: Go/No Go decision timeframe for physicals

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#142]
•	iops on SAN 
•	Load on netapp vms (network/cpu/etc) 
•	NICS on hosts 
•	Understand upstream network impacts (netapp physicals are all IP network and will impact data network saturation) 
•	What are the best price→ size options? 
•	Concluded that early Jan is go-nogo decision timeframe for physicals or not going to happen in time for rollout.
•	Leaning toward Physical NetApps as sizing expectations to be past the financial pain point as soon as we migrate, and expect to exceed SAN pain point (of 150TB) within 1-2 years

**Comment by StevenBarre** [comment]
@kelpisland @jefkel this was decided as physical correct?

**Comment by Joe-Craig** [comment]
ROM pricing sent to clients. 

> Hi David,
> 
> Per conversations with Todd Wilson, he is looking for budgetary pricing for the OpenShift Storage solution so that he can request the capital.  We have priced out ROM pricing for both a physical and a virtual solution with 60TB usable storage for KPROD and approx. 20TB usable storage for CPROD.  They do anticipate a growth of 30TB/year.   The ROM cost for either solution is very close for the 1st year – between 500K – 750K.  We have not been asked to provide pricing for future years.  Below is a summary of points for consideration between each solution.   
> 
> Primary Points of Consideration for OpenShift Storage Solution
>  
> •	Costing: The design of the virtual storage offering from NetApp, called ONTAP Select, requires significantly more storage capacity than a physical solution.  This is due to the High Availability design of ONTAP Select and the fact that each VM node has to replicate its data to the other HA node pair's storage.  In contrast, the physical solution uses RAID DP to protect the data more efficiently.  This means that ongoing monthly operational charges will be significantly more than a physical solution.
>  
> •	 Performance:  The proposed physical solution will provide a higher and more consistent level of performance than the alternative ONTAP Select solution.  This is due to the fact that the hardware approach provides 100% dedicated storage, compute, and network resources to ONTAP versus the ONTAP Select solution which sits on a shared virtual environment.  Additionally, the hardware approach will ensure dedicated SSD storage, whereas the ONTAP Select approach will utilize Tier 2 SAN, which is typically a blend of SSD and SAS 10k drives.
>  
> •	 Availability: The proposed physical solution will provide a greater level of hardware resiliency and availability since ONTAP clustering technology (used in both approaches) happens at “hardware speeds” on the physical systems vs the ONTAP Select instance which needs to traverse the hypervisor layers.
>  
> •	Scalability: NetApp recommends ONTAP Select for smaller customer use cases such as lab environments, remote or branch office sites.   For larger environments, or solutions that may grow rapidly, the physical solutions better manages risks, and provides greater resources to scale upwards while maintaining performance objectives.
>  
> •	Network Complexity:  Both solutions will use Ethernet to deliver storage (iSCSI & NFS).  The physical solution will have dedicated 10 Gb network ports to provide higher throughput whereas the ONTAP Select solution will be limited by shared network bandwidth provided by the ESXi hypervisor for all VMs on that cluster.  Additionally, physical network connections minimize the number of elements for troubleshooting.
> 
> Can you please advise what are the next steps to provide the ROM costs to Todd so that he can request the funds from his group?
> 
> Thanks in advance,
> 
> Erwin Lee, PMP
> Program Manager, Strategic Portfolio Management Office

**Comment by Joe-Craig** [comment]
Todd has indicated that the preferred route is to use physical NetApps for the production environments.
