### ISSUE TITLE
Installation of tools infrastructure hosts

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#147]
Installation of the 3 boot service hosts

- [x] Kamloops Lab Boot service host
- [x] Calgary Lab boot service host
- [x] Kamloops Prod Boot service host

@sbarre-esit will be creating playbooks and roles to set up `httpd`, `tftpd`, and `dhcpd` on the servers as well as generate the correct CoreOS ignition files to build the cluster.

TODO:
- [x] Figure out DHCP advertising of routes
- [x] Add iSCSI Initiator name to hosts
- [x] `node.session.timeo.replacement_timeout = 5` in iscsi.conf
- [x] Add NFS domain name

**Comment by DanDeane** [comment]
vm's deployed....over to Steven to configure.

**Comment by StevenBarre** [comment]
Making progress on an ansible playbook to install and configure HTTPD, TFTPD, DHCPD, and generate the Ignition files for the cluster.

**Comment by StevenBarre** [comment]
Done!
