### ISSUE TITLE
Deploy F5 in Kamloops Lab

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#148]
initial deployment and configuration of the F5 in Kamloops Lab

**Comment by DanDeane** [comment]
blocked waiting on DXC/AT&T network team.  they have not extended the required vlan all the way to our hosts.  It is on the network core...so that is a start.

**Comment by DanDeane** [comment]
Initial F5 cluster configuration completed by AT&T.  Ready for testing.
