### ISSUE TITLE
Order 2 physical NetApp appliances for production clusters in Kamloops and Calgary

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#151]
- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by StevenBarre** [comment]
See also #36

**Comment by Joe-Craig** [comment]
Pricing is now complete and we can move on to generating the SCO. Need to discuss with David Ell whether the network upgrades he wants should be put into the SCO or a separate one.

**Comment by tosazuwa** [comment]
Closing this ticket as its a duplicate of #36
