### ISSUE TITLE
Configure Temporary NetApp Virtuals for Kamloops Prod

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#154]
With a physical NetApps to be purchased/delivered, we expect a delay for the physical hardware to arrive.  Virtual NetApp appliances are to be used until we can re-build the prod storage using the physicals.  (VM's and storage have been delivered and are waiting for provisioning)

- [x] Establish Cluster Name - MCS-VKPROD-NETAPP
- [x] Order gear under #36
- [x] Plan network design
- [x] Reserve IP Addresses and DNS Names from Network Team
- [x] Storage Team - Download latest ONTAP firmware and install and configure
  - [x] Submit request for SMTP to Infrastructure Group
  - [x] Configure AutoSupport for HTTPS  (Firewall requests)
  - [x] Configure Timezone and NTP
  - [x] Create SVM for Trident/OpenShift
  - [x] Create SVM for CORP Login
  - [x] Create Aggregates on both nodes
  - [x] Configure Aggregate Delegation
  - [x] Disable FSID
  - [x] Configure NFS Protocol and NFS Data LIF
  - [x] Configure iSCSI Protocol and iSCSI Data LIFs on each node
  - [x] Add cluster to Unified Manager
- [x] Setup Trident on the cluster and test

**Comment by StevenBarre** [comment]
Poked at the storage team to get this back on the radar

**Comment by StevenBarre** [comment]
Completed except for issue tracked in #186
