### ISSUE TITLE
Physical Server count change

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#156]
Todd mentioned that he is looking at adding additional servers to the physical server order (currently 15 hosts)

- [x] Todd to confirm final count of hosts
- [x] Update iStore request with new count of hosts
- [x] Additional TOR switches *may* be part of this?

Needs to be finalized ASAP to get order in before end of fiscal.

**Comment by tosazuwa** [comment]
Meeting scheduled for Friday Jan 31st with David Ell to finalize final numbers for hosts

**Comment by tosazuwa** [comment]
This i-store order will possibly not be placed this fiscal. TBC for next fiscal

**Comment by tosazuwa** [comment]
Closing ticket. 15 servers/hosts will be tracked in ticket #34
