### ISSUE TITLE
Validate all new provisioned networks

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#157]
Set up a pair of VMs, ping one from the other on each interface, move one of the VMs around to all the ESX hosts to ensure its working.

- [x] KLAB
- [x] CLAB
- [x] KPROD
- Confirm KPROD prod subnet is the full /25 by pinging from a low IP to a high one.

**Comment by DanDeane** [comment]
klab and kprod are working.

**Comment by DanDeane** [comment]
clab network confirmed as working across all hosts in the cluster.
