### ISSUE TITLE
Confirm SDN Compartment Go/No Go 

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#158]
With a re-deploy required to move from the DMZ to the SDN Compartment, we need an availability date to plan toward.

Definition of done: 
- [x] A confirmed availability date of the SDN Compartment

- [x] Designs handed to DXC from Hosting branch

- [x] Plans added for the re-deploy of the clusters with dates attached.

**Comment by tosazuwa** [comment]
Email sent to David Ell regarding cloud zone availability

**Comment by tosazuwa** [comment]
Heard back from David Ell. He has met with his team yesterday (Jan 27) and they are still in the initial design phases.  He states that they wouldn’t expect the Cloud Zone to be available until late Spring/early Summer. 

We will need to adjust the OCP 4 Road map and discuss impact/work arounds, etc@kelpisland

**Comment by tosazuwa** [comment]
Meeting scheduled with @kelpisland & David Ell for Friday Jan 31 with Hosting Branch, to discuss Cloud zone availability and timelines

**Comment by tosazuwa** [comment]
Meeting outcome: 

David Ell & Team are working on the design pattern for Cloud Zone. Tentatively to be completed by end of Feb 2020. David Ell will provide bi-weekly updates and confirm when design is ready. 
Cloud Zone availability milestones could be pushed into May 2020. 

Dependency on David Ell & team vetting design pattern, impact of design etc

**Comment by tosazuwa** [comment]
Cloud Zone (now known as SDN Compartment) design meeting held Friday Mar 6th. Next steps to hand designs to DXC for deployment

**Comment by Joe-Craig** [comment]
Will speak to Paul Bartle and Scott McWilliams about what work DXC needs to do to move the OCP clusters to the SDN compartment.

**Comment by jefkel** [comment]
Tolu has mentioned that the new servers (the 15 we've ordered) will be able to be built directly in the SDN Compartment.  This brings up a question:

Are we able to re-deploy our current OCP 4 clusters as an SDN Compartment deployment now?  
- If **yes**, then let's get that moved up ASAP in our project
- if **no**, then what steps are required to allow this? and what is the target date that we can expect to redeploy our current clusters as SDN compartment hosts?

**Comment by StevenBarre** [comment]
Steps: 
- Meeting yesterday with A&E to discuss the implementation design
- Confirm the routing path purposed from the WAN router to the F5s will work (Stuart)
- Create diagrams of network objects and traffic flows in the SDN compartment (Scott)
- Create a Brief Note on the use of  the F5s in the OCP environment (Scott)
- Present to Brief Note to JTSAWG and JOC (OCIO Hosting Services) for approval (Scott)
- Discuss our specific SDN solution with ISS, to determine how it fits into the SDN Compartment pattern. Document this in a tech note for JTSAWG approval. Use this to document for obtaining STRA (AS, ISS)
- Create a tech note documenting how the 
- Stand up fresh F5 VCMP or virtuals and perform base configuration (AS/ATT)
- Update SiS Firewall rules as needed (443 and 6443) (Steven to request)
- Request new public subnets and private subnets (Steven)
- Configure the F5 BIG-IP to work with the F5 Container Ingress Services(AS/ATT)
- Set up API VIPs on new F5s (AS/ATT)
- Move VMs into new subnets (Dan/Steven)
- Rebuild cluster and test

@jefkel can you confirm we don't need to expose port 80 to the public internet? Seems in the interest of security we should only publish 443.

@jefkel any idea how many public IPs we'll need?

Target date: End of Sprint 7

**Comment by StevenBarre** [comment]
We'll also require Aporeto (or other SDN) config understood before we can stand up PROD. This includes ensuring we have rules that can't be overridden by developers to enforce the zone model.

**Comment by jefkel** [comment]
Great list @sbarre-esit we should capture that in the ticket to implement.  This was the “can we get started” decision.

I am not quite sure whether we want to remove the port 80 feature just yet.  I’d suggest further discussion with the team.

WRT IPs, not sure at the moment as we are setting up for the initial migration, I don’t know that we will require more than the base cluster needs to start, but I’m happy to add options.

As for enforcement of a zone model, there is still work to be done to determine how to enable the teams to design their app’s network security requirements.

**Comment by jefkel** [comment]
Closing, Tracking implementation progress in #185
