### ISSUE TITLE
Scope Out Service Description for OCP4

### ISSUE THREAD

**Issue by Joe-Craig** [BCDevOps/OpenShift4-RollOut#159]
Build a shell outline of the services that will be available going forward for the OCP 4.
These services should form the core of the SCO that will be drawn up by Advanced Solutions, once the SCO is complete and signed off the services described can then be iStored ordered by the client.

High level:
-  [x] Adding a new cluster (Virtual, Physical)
- [x]  Adding a new worker node to the cluster (Non-custom)
- [x] Adding more storage to existing instance
- [x] Adding a new instance of the storage solution
- [x] Decommissioning a cluster
- [x] Adding a security node ???
- [ ] Deploying security ???

**Comment by Joe-Craig** [comment]
Working on outline. Will be meeting with Steve Hiley today (25th Feb) to confirm that outline conforms to format for contracts.

**Comment by Joe-Craig** [comment]
A proposed service evolution framework was presented Friday 6th March. The framework was accepted as a good basis for taking forward. It was agreed that this work cannot and does not need to be done at this time. We still have to wait till the service is stabilized so we can build the detail of the service descriptions.

**Comment by Joe-Craig** [comment]
Completion of this does not impact the delivery of the OCP 4 rollout project so closing ticket.

**Comment by tosazuwa** [comment]
[https://app.zenhub.com/files/217612857/a8bcae39-0b2d-41ef-81ac-06166c662001/download
