### ISSUE TITLE
Decommission 3.11 Pathfinder Cluster

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#16]
When the cluster has been emptied, fully decommission the cluster in preparation for a new pathfinder deployment in Azure.

**Comment by mitovskaol** [comment]
@wmhutchison can this now be closed?

**Comment by wmhutchison** [comment]
@mitovskaol Yup, an unused Epic, can be closed. The single task https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1314 remains open on a small bit of final paperwork that's about to drift in, and will be closed off as well when done.
