### ISSUE TITLE
Assess impact of OCIO network improvements request

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#160]
- [x]  Decision from Todd re physical servers and network topology for NetApps and improvements to TOR (Top Of Rack) switches

- [ ] SCO/procurement of any outstanding items

**Comment by Joe-Craig** [comment]
Met with Todd and David Friday and got a clear direction on what the plan is with the budget spend.
Working internally to draw up the new plan for SCOs to deliver the requested items before end of fiscal.

Have meetings today (4th feb) to discuss the new plan and get the DXC teams approvals to proceed.

**Comment by Joe-Craig** [comment]
Impact has been assessed and the outcome documented.
SCO have been created to purchase the agreed upgrade hardware for the data center improvements.
