### ISSUE TITLE
Create OCP 4 Migration Guide

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#162]
**Goal**
Create a set of resources for developer teams to leverage when planning an application migration to OCP4

**Outcomes**
- [x] OCP 4 migration workshop
- [x] Migration Checklist Template
- [x] post it/make available
- [x] 'how to contribute' guide

1. Domain Migration

 *Migrating Vanity Domains*
When migrating to OCP4 you will be moving clusters and will need a plan to migrate your vanity domain name (i.e helloworld.gov.bc.ca or hellobc.com). This will consist of your DevOps specialist working with the iStore team to point your DNS records to the new cluster as you move workload and data.

*Migrating General Domains*
If you're using a domain with `pathfinder.gov.bc.ca` in it when you migrate to OCP4 the pathfinder part will go away and be replaced with a new component. Its recommended that you use a vanity domain like mycoolapp.gov.bc.ca for production users. If you don't need this, or don't want to do it, begin socializing the change is coming with you users. When you move to OCP4 and you new system is running, make sure to let your users know where your app moved to.
- [ ] StorageMigration tool for Developers

https://github.com/BCDevOps/OpenShift4-Migration

**Comment by jefkel** [comment]
Historic openshift WIKI repository
http://github.com/bcdevops/openshift-wiki
docs/OCP is where most of the platform documentation was originally(currently?) located

Repo that was originally planned for migration docs/notes (has a start on a couple of documents)
https://github.com/bcdevops/OpenShift4-Migration

**Comment by mitovskaol** [comment]
Questions for discussion before the early adopter orientation on Sep 22:
1) how many teams? **22 teams** (invasive species doesn't have DevOps skills)
Do a round-table using the survey submissions.

2) When can the early adopters bring production workloads?  

- "early-access" window from mid-Oct (the week of Oct 12) to mid-Nov, 

- the teams that are comfortable with bringing their prod workloads during the early-access, are encouraged to do so however  feature roll-out will continue during the early-access period (more frequent change windows and maintenance activities during the early-access),
- production-ready after the "early-access" and have the teams to commit to migrate prod workloads after the "early-access" window is over.

Platform Services will provide production support from Day 1, the teams are responsible for supporting their prod workloads as soon as they are migrated.

3) any prep work they can start now?
- plan your DNS migration - *.pathfinder will be gone, consider migrating to *.devops.gov.bc.ca - iStore order for a Vanity plate , pipeline automation, database migration strategy
- the teams will need to reconfigure how their DNS resolves to point to the Silver cluster ingress
- secure DevOps resource(s) for the migration
Check out https://github.com/BCDevOps/OpenShift4-Migration/blob/master/docs/pre-migration-cl.md

4) access to the ocp 4 app migration docs repo - what is the contribution process? PR or GitHub issues? GitHub issues are better for tracking teams conversations and gathering informartion. 
https://github.com/BCDevOps/OpenShift4-Migration

5) RC #devops-ocp-migration - start discussing issues in RC, document solutions in GitHub issues, PS will merge common questions into the main doc in the GitHub repo.
RC -> GitHub issues ->GitHub repo via PR

6) would the teams like to have a weekly 30-min touch point - exchange reports of progress and pro-tips and ask for help in person? Ask the early adopters

7) Sample App migration demo - can we demo the migration process with a sample app @jleach?   Make a list of different app migration patterns e.g. a database/PVC migration, a DNS migration, etc and look for volunteers to run the demo. **Give the early adopters a heads-up that they will be expected to demo their migration process to the Platform community during the early-access window.** 

Book an early adopter kick-off in the week of Oct 5. 

8) All projects go through new Project Registry - full info is required - what is the url for the new registry and who can access it? http://registry.developer.gov.bc.ca  ,   IDIR only to log on, PO to submit a provisioning request. 
**Provide meaninful project names and descriptions, PLEASE!!!** Do it right the first time as currently no feature to edit submissions.

9) what about images in OCP 4? do we have a migration flow documented?
Some common images will be provided in the openshift namespace (backup, Patroni images). Other images the teams will have to build themselves.
Artifactory will be available for caching images, the teams will have access to the caching repos on Day 1. Private repos will be made available at a later phase.

**Comment by mitovskaol** [comment]
Migrating teams are encouraged to contribute to the Q&A section that is captured in the OCP 4 Migration repo's Issues.

**Comment by jleach** [comment]
The Migration Toolkit for Containers is out of scope for this ticket. It is being done as part of another ticket(s).
