### ISSUE TITLE
Implement Silver Cluster Switches

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#163]
- [x] Rough pricing has been completed by DXC

- [x] DXC to create SCO and submit to Hosting Branch for approval and signing

- [x] DXC goes to procurement and places order

- [x] Confirm deployment and configuration of the switches

**Comment by Joe-Craig** [comment]
Have updated this ticket to cover the ToR switches and the new racks needed for both Kamloops and Calgary to house the new OpenShift v4 environments.

**Comment by Joe-Craig** [comment]
Working with Datacenter Management to define the list of items needed for the OpenShift environments.

**Comment by stregear** [comment]
SCO 201 for the new racks/cage modifications in Kamloops and Calgary approved by the Province.  Service Orders for the new racks have been submitted to Q9.   SCO 201 did not include switches.

**Comment by Joe-Craig** [comment]
A price comparison of using all Arista switches as apposed to a mix of Arista/HPE has been requested. Working to get quotes and build price comparison.

**Comment by Joe-Craig** [comment]
SCO drafted and sent to province for sign-off

**Comment by Joe-Craig** [comment]
Still waiting for hosting branch to approve.

David Ell waiting for new OCPv4 architecture to see if there is any need for additional switches. When Jeff has finished architecture we can re-visit the rack layouts and true-up the number of switches needed and whether we need to extend the rack space.

**Comment by Joe-Craig** [comment]
Arista switches are with finance (final step to procurement)
HP switches are still needing a refreshed quote to do final pricing.

**Comment by Joe-Craig** [comment]
HP switches have been ordered and Arista switches are with procurement.

**Comment by Joe-Craig** [comment]
ETA for HP switches is June 25th for both Kamloops and Calgary

**Comment by Joe-Craig** [comment]
PO has been cut for Arista switches but  no ETA for their arrival yet.

**Comment by mitovskaol** [comment]
@Joe-Craig Thank you for the update about the switches. Can you please confirm if we build the Silver cluster with HP switches or will need both types of switches -  HP and Arista - to build the Silver cluster?

**Comment by StevenBarre** [comment]
We need both. The netapp will be accessed via the HPE switches, and the openshift intra-node traffic will flow over the Arista switches.

**Comment by Joe-Craig** [comment]
@mitovskaol Yes the current design is (as Steven says.) NAS using HP and ToR using Arista.

**Comment by mitovskaol** [comment]
See the update in ticket #37

**Comment by tosazuwa** [comment]
DXC Still waiting on network config

**Comment by Joe-Craig** [comment]
HP switches are now installed and configured for use in the Silver cluster
