### ISSUE TITLE
Decision support for IPI vs UPI in Azure

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#168]
Based on latest deployment issues with IPI installer in Azure, we are being asked to change our deployment strategy to use the UPI installation method in Azure to allow us to target a specific Resource Group.

- [x] pro/con of UPI vs IPI
- [x] work estimates for changing deployment strategy
- [x] Vendor Timelines for possible support of customizing resource group target vs timeline for UPI deployment

**Comment by filiy** [comment]
After talking to Jon from Gov and Gerald from Red Hat, UPI is going to be the path forward. OCP 4.4 with UPI will allow us to leverage all the same Azure features as using IPI. 

Jon would like to have some control about how we install the cluster.
