### ISSUE TITLE
Implement  Cluster Configuration Automation

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#173]
Encompasses all post-install configuration activities and will be tracked in their own tickets (under this EPIC)

See doc:
https://github.com/BCDevOps/OpenShift4-RollOut/blob/cluster-config-auto/docs/deploy/DeploymentChecklists.md

**Comment by StevenBarre** [comment]
@jefkel anything else we need here?

**Comment by jefkel** [comment]
Have you moved the missing pieces to other tickets? I'm still seeing some outstanding (blocked?) items on the list:
eg:
- [ ] Basic Nagios monitoring
- [ ] Figure out Ignition for physicals/bonding
etc...

**Comment by jefkel** [comment]
@sbarre-esit  Looks like we need an external route for the registry setup?  (expected to see same behavior as production in ability to access registry remotely via docker commands)

**Comment by StevenBarre** [comment]
> Have you moved the missing pieces to other tickets?

Done, also see https://github.com/BCDevOps/OpenShift4-RollOut/pull/275

> Looks like we need an external route for the registry setup?

https://github.com/bcgov-c/platform-ops/pull/262

**Comment by StevenBarre** [comment]
I've implemented all the items identified in https://github.com/BCDevOps/OpenShift4-RollOut/blob/cluster-config-auto/docs/deploy/DeploymentChecklists.md that can be automated with Ansible to stand up and configure a cluster to date.

Moving this Epic to the backlog in case any additional items are identified later.
