### ISSUE TITLE
F5 Recommendation to David Ell

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#175]
Steps required to finalize our F5 implementation (vCMP vs separate VM)

- [x] Confirm the routing path purposed from the WAN router to the F5s will work (Stuart)
- [x] Create diagrams of network objects and traffic flows in the SDN compartment (Scott)
- [x] Create a Brief Note on the use of the F5s in the OCP environment (Scott)
- [x] Present to Brief Note to JTSAWG and JOC (OCIO Hosting Services) for approval (Scott)

**Comment by tosazuwa** [comment]
To  escalate if no decision reached by Apr 14

**Comment by Joe-Craig** [comment]
BN presented and accepted by hosting branch.
Additional SCO to purchase new transceivers is required to implement the F5 recommendations.
