### ISSUE TITLE
Aquire SSL Certs for cluster endpoints

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#176]
Order/Track (via iStore) the following certificates for each cluster we are deploying.
iStore #: 1026043

- [ ] Kamloops Lab
  - [ ] api.cowichan.devops.gov.bc.ca
  - [ ] *.apps.cowichan.devops.gov.bc.ca

- [ ] Calgary Lab
  - [ ] api.thetis.devops.gov.bc.ca
  - [ ] *.apps.thetis.devops.gov.bc.ca

- [ ] Kamloops Prod
  - [ ] api.pacific.devops.gov.bc.ca
  - [ ] *.apps.pacific.devops.gov.bc.ca

**Comment by jefkel** [comment]
@sbarre-esit can you let me know when we have CSRs for the above? (I'll followup with the iStore certificate requests)

**Comment by StevenBarre** [comment]
From [DigiCert](https://www.digicert.com/easy-csr/openssl.htm)

> **What If I Need Subject Alternative Names?**
> Using OpenSSL to Add Subject Alternative Names to a CSR is a complicated task. Our advice is to skip the hassle, use your most important server name as the Common Name in the CSR, and then specify the other names during the order process. Our Multi-Domain (SAN) certificate ordering process allows you to specify all the names you need without making you include them in the CSR.

Not sure who the TLS provider for the Province is, but hopefully they allow the same thing. So I'll just generate one CSR for each for `*.apps` and you can add in the SANs when ordering.

```bash
DATE=$(date +%Y-%m-%d)
CLUSTER=cowichan
mkdir csr-${CLUSTER}-${DATE} && cd csr-${CLUSTER}-${DATE}
openssl req -new -newkey rsa:2048 -nodes \
  -out ${DATE}_${CLUSTER}.devops.gov.bc.ca.csr \
  -keyout ${DATE}_${CLUSTER}.devops.gov.bc.ca.key \
  -subj "/C=CA/ST=British Columbia/L=Victoria/O=Government of the Province of British Columbia/OU=Office of the Chief Information Officer/CN=*.apps.${CLUSTER}.devops.gov.bc.ca"
```

**Comment by StevenBarre** [comment]
@jefkel I've emailed you the CSRs

**Comment by jefkel** [comment]
Certs have been ordered

Service Desk ticket #s (pending updates with actual iStore request #s)
Kamloops Prod: 51829
Kamloops Lab: 51827
Calgary Lab: 51828 (iStore: 1022390)

**Comment by StevenBarre** [comment]
Blocked while the TLS certs are on order.

**Comment by jefkel** [comment]
Updated/Replaced Certificate iStore request that encompasses all 3 cluster certs:
iStore#: 1026043

**Comment by StevenBarre** [comment]
Generated CSRs and sent to ISB

**Comment by StevenBarre** [comment]
Role created and all certs applied.
