### ISSUE TITLE
Automate: Infra node creation

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#177]
Automate configuring infrastructure nodes from worker nodes.
 - add initial services that can be added there.

**Comment by StevenBarre** [comment]
Node config PR https://github.com/bcgov-c/platform-ops/pull/186

**Comment by StevenBarre** [comment]
PR to move Trident, route, and registry to Infra nodes
https://github.com/bcgov-c/platform-ops/pull/190

**Comment by StevenBarre** [comment]
PR merged
