### ISSUE TITLE
Automate: Generic Node Host Setup

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#179]
Configure machineconfigs for nodes

- [x] idmapd.conf Set NFS Domain
- [x] iscsid.conf Set node.session.timeo.replacement_timeout = 5
- [x] Enable iscsid service
- [x] Enable multipathd service
- [x] initiatorname.iscsi Set InitiatorName
- [x] Set up other system configs
- [x] chrony.conf set NTP servers
- [x] Set vga=14c

**Comment by StevenBarre** [comment]
Completed via https://github.com/bcgov-c/platform-ops/pull/186
