### ISSUE TITLE
Automate: Netapp Storage configuration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#180]
Set up Trident configs
- [x] Set up Trident
- [x] Configure the SVM
- [x]  *Install tridentctl
- [x]  *Install Trident
- [x]  *Set up backends
- [x]  *Create storage classes
- [x]  *Storage Pool Configuration (netapp-block-standard, netapp-file-standard)
- [x]  Create new storage classes (flexvol direct volumes eg: netapp-block-extended, netapp-block-extended)

**Comment by StevenBarre** [comment]
PR in progress https://github.com/bcgov-c/platform-ops/pull/189

**Comment by StevenBarre** [comment]
PR merged
