### ISSUE TITLE
Network Security Solution Review

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#182]
# Network Security Tooling Evaluation

# Purpose

---

In order to ensure we are making the right technical decisions in our zero-trust network security management goal for OpenShift and other areas of the network, we need to evaluate other tools and compare them to the current Aporeto deployment. The following list of requirements should be used as guidance when looking at new tools. 

Why? 

The Aporeto implementation (which is now acquired by Palo Alto Networks and being integrated into the PRISM suite) has had some maturity and stability issues that has affected users of the Pathfinder platform. Before continuing on and doubling down on this solution, we will perform a high-level analysis of the current market landscape and determine if other solutions should be evaluated in greater depth. 

# Functional Requirements

---

- [ ]  Centralized control plane with complete API supporting multiple clusters / systems
- [ ]  Supporting a zero-trust network configuration / implementation
- [ ]  Ability to deploy into on-prem and cloud kubernetes  environments (specifically OpenShift v4)
- [ ]  Ability to deploy into linux virtual machines (on-prem and cloud)
- [ ]  Ability to enforce policies at different levels of access/control
- [ ]  Ability to permit teams to create / update / manage their own specific policies (in a multi-tenant manner)
- [ ]  Ability to permit teams to view flow log data  (in a multi-tenant manner)
- [ ]  Ability to view network flows (in a multi-tenant manner)
- [ ]  Automatic workload identification (ie. creating runtime tags alongside user-generated tags)
- [ ]  Ability to create network policy between k8s and linux vm's
- [ ]  RBAC integrated with OIDC support
- [ ]  Relative easy degree of automation (ie. import / export configuration as code, etc)
- [ ]  Integration with alerting systems (ie. via webhook, smtp, or otherwise)
- [ ]  Complete audit trail capability
- [ ]  Ability to forward flow or audit logs to external SIEM systems
- [ ]  Ability to define "external networks" and "external endpoints" for use in policy creation (external endpoints could be things like HTTP L7 endpoints)
- [ ]  Enterprise Support

# Possible Solutions for Evaluation

---

- [ ]  VMware NSX
- [ ]  Calico Enterprise

**Comment by DanDeane** [comment]
add baremetal

**Comment by DanDeane** [comment]
IPS inline? vs outside of the solution and back again.

**Comment by mitovskaol** [comment]
Aporeto has been removed from OCP 4 Platform and we switched to use OCP 4 Built-In SDN instead.
