### ISSUE TITLE
Have MCS team member rebuild a cluster

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#187]
Validate all the steps, docs, and automation

- https://github.com/bcgov-c/advsol-docs/blob/master/OCP-4-Install.md
- https://github.com/bcgov-c/platform-ops/tree/ocp4-base/ocp4

**Comment by StevenBarre** [comment]
In progress.

**Comment by StevenBarre** [comment]
@wmhutchison rebuild kprod/Pacific onto 4.3 and made some PR changes to docs.

**Comment by jefkel** [comment]
Can we also track how long it takes to re-build a cluster?  I would expect drops in time required as we practice/automate, but eventually we could also see increases in time due to additional automated steps?

The goal being that we want to have as much documentation about known deployment times for a given cluster, along with clear pre-requisites and external dependency documentation where it is not part of the deployment automation.

**Comment by jefkel** [comment]
Also, links in the documentation reference cluster build automation that is not accessible as part of the developed automation: (https://github.dxc.com/AdvSol/rhcos-ignition-builder).  

Is this not included as automation code for the project?

**Comment by mitovskaol** [comment]
@wmhutchison will rebuild the cluster and measure the time it takes.

**Comment by wmhutchison** [comment]
Rebuild KPROD/Pacific cluster, starting from a state where all VMs are powered off and about to power up the bootstrap VM for imaging, and ends with all nodes in the cluster up, and automation ran to configure up Trident/Github authentication/EFK Logging.

Take 1: 61 minutes approx.
- 1:50pm to 1:53pm (turn on and image bootstrap, wait for initial API response)
- 1:54pm to 2:07pm (turn on and image masters, wait until done and bootstrap VM can be powered off)
- 2:08pm to 2:25pm (turn on and image infra/apps, wait until all nodes Ready and progress has only `authentication` remaining)
- 2:26pm to 2:34pm (run playbook to refactor API cert, wait until api pods all restart and oc works again)
- 2:35pm to 2:51pm (run playbook to do everything else including setup Trident, oauth, custom machine configs, and EFK logging)

**Comment by wmhutchison** [comment]
FYI if curious, took about 47 minutes to complete a cluster upgrade for KPROD/Pacific which has zero user workloads on it (3 masters, 3 infra, 4 app).
