### ISSUE TITLE
Complete DXC Service Agreement

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#189]
Just checking where we are with the DXC Service Agreement based on David Ell's presentation in Feb. Next steps @mitovskaol ?

**Comment by mitovskaol** [comment]
@tosazuwa We are still waiting on the next steps from them. Will let you know as soon as we get any new information.

**Comment by Joe-Craig** [comment]
After meeting with Todd, David Ell, Nainesh, et al. It was agreed that we would proceed as a project using a professional service request (T&M) and iStore orders for infrastructure to the end of Release 1.

At that time we would have enough information to write the Brief Note and progress with a SCO.

**Comment by Joe-Craig** [comment]
Nainesh and David Ell agreed the new service description could not be complete until the OCPv4 environment is delivered and has settled in. This is targeted for July 2020

**Comment by Joe-Craig** [comment]
Considering the changes to the OCPv4 project the impact of COVID-19 and the pushing back of the delivery of the OCPv4 environment, this deadline is likely to be extended.

**Comment by Joe-Craig** [comment]
Hosting branch and DXC have been in discussion over the way that storage used for the OCPv4 cluster is charged. A new storage type has been proposed for the contract that would cover the management/maintenance of the NetApp storage used in OpenShift.

**Comment by Joe-Craig** [comment]
First draft currently due end of October 2020.

**Comment by Joe-Craig** [comment]
Brief Note to be sent to province by 29th Oct 2020

**Comment by mitovskaol** [comment]
This work is handled by Hosting Branch and DXC, closing the ticket.
