### ISSUE TITLE
Order Servers and Storage for Gold cluster

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#191]
Order hardware for second production cluster
- [x] Create BN for Gold Cluster
- [x] Create pricing for Gold components
- [x] Issue SCO for Gold Cluster
- [x] Province to approve the SCO
- [x] Order VMs for Boot Service
- [x] Order 19 (was 14) x physical hosts (see spreadsheet for host details)
- [x] Order 1 physical NetApp appliance for second production cluster in Kamloops
- [x] Order switches for Gold cluster (ToR and NAS switches)
- [x] Implement cage upgrades to allow the deployement of Gold to existing cages
- [x] Confirm physical host order and expected delivery date (**BCGov/DXC**)

**Comment by jefkel** [comment]
Blocked waiting on final design approval

**Comment by Joe-Craig** [comment]
Brief Note issued for review - May 15th

**Comment by Joe-Craig** [comment]
Additional servers where requested to be added to the Brief Note - 18th May

**Comment by Joe-Craig** [comment]
Brief Note re-issued with additional hardware (8 more worker nodes) - 18th May

**Comment by Joe-Craig** [comment]
Awaiting - Confirmation from Davis Ell to move to SCO

**Comment by mitovskaol** [comment]
Received an approval to move to SCO. Will start working on the SCO, ETA for the having the SCO complete is June 12. After that the next step is to submit to Leanne for signing.

**Comment by Joe-Craig** [comment]
SCO with Province for approval.

**Comment by Joe-Craig** [comment]
Still waiting for Province to approve the SCO

**Comment by Joe-Craig** [comment]
SCO returned for more wording changes. 
Confusion over wording in the SOW attached to the iStore for professional services which did not make it clear that support was covered until we put in place a new service agreement for all OCP4 environments.

**Comment by tosazuwa** [comment]
@stregear has submitted procurement requests for servers and NetApp and  @lukegonis  has been provided with all the information for the istore orders (4). Also submitted procurement request for Arista switches. Waiting on quote for HP switches

**Comment by Joe-Craig** [comment]
SCO sent to Province
SCO signed off by Province
Procurement has been complete and PO sent to vendors

**Comment by Joe-Craig** [comment]
RITM0068735 – Arista Switches – 11/23/2020
RITM0068520 & RITM0068519 – Dell servers – 9/16/2020 & 9/29/2020
RITM0068791 – HP Switches – Still waiting for ETA
RITM0068608 – NetApp – Still waiting for ETA

**Comment by Joe-Craig** [comment]
RITM0068791 – HP Switches – 09/22/2020
RITM0068608 – NetApp – 09/09/2020
