### ISSUE TITLE
Order replacement App Nodes for Silver cluster

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#193]
Order of 4 VM's  for 3rd cluster to allow additional cluster validation space for platform services deployments and validation.  We already have master/infra nodes available, as well as netApp VMs with 2TB of storage.  The only piece missing from being able to deploy a 3rd cluster today is the application nodes (original app nodes have been re-claimed by OCP 3 cluster)

To be ordered:
- [x] 4 x Linux VM (4vCPU/2 Core, with 32G RAM and 100G storage) (same as the current cowichan/thetis app nodes)

It is understood that these will be purchased for a minimum 3 month period, and will be used as a test "silver" cluster until physical hardware arrives.

**Comment by StevenBarre** [comment]
This is for KPROD / PACIFIC correct?

I believe Pop will need to initiate the istores for these.

**Comment by jefkel** [comment]
That sounds good @sbarre-esit , he's added as well.  Could you (or william) work with him to make sure he has the required technical pieces in his iStore order?

**Comment by stregear** [comment]
Thank you – it is on my list ☺
---------------------------------------------
Sharon Tregear
Project Manager, SPMO
T: 250.405.4500.opt1. ext. 4576
M: 236.464.0251
sharon.tregear@dxcas.com<mailto:sharon.tregear@dxcas.com>

Advanced Solutions, a DXC Technology Company
2200 - 4464 Markham Street
Victoria, BC  V8Z 7X8
www.dxcas.com<http://www.dxcas.com/>
The information transmitted herein is intended only for the named recipient(s) above, and may contain information that is privileged, confidential, or exempt from disclosure under applicable law. If you have received this message in error, or are not the named recipient(s), please immediately notify the sender by replying to this email and delete this message from all computers. Thank you.

**Comment by StevenBarre** [comment]
iStore submitted

**Comment by StevenBarre** [comment]
iStore 1030281

**Comment by StevenBarre** [comment]
Nodes added to cluster
