### ISSUE TITLE
F5 Configuration Testing

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#194]
Create pro/con evaluation for leveraging F5 for OCP route object replacement vs keep OCP routes.

F5 VIP -> OpenShift HA-Proxy routers (same design as current)

F5 VIP -> OCP service definition (OCP router replacement)

Build pro/con list for each of the above:
- F5 performance testing results (how does it scale with # of ingress routes?)
- Automation and other edges for route creation?
- Route feature lists?

**Comment by StevenBarre** [comment]
Asked on F5 Slack

Steven Barre May 11th at 2:28 PM
Does it make sense for us to keep trying to completely replace the OpenShift Router with CIS? or should we look at just replacing specific routes and using configmaps to expose non-http services? What are the advantages of using CIS/Big-IP as an HTTP endpoint vs just passing the TCP traffic onto OCP/HAProxy?
4 replies

Steven Barre  3 days ago
I guess one pro of the Big-IP is TLS hardware offload. But one downside is that it has issues with too many objects (just as rules, pools, and pool members)

mdditt2000  16 hours ago
Really good question. Maybe only the routes that need TLS, Advanced WAF, BOT, DDOS enabled on the virtualserver.

Goran  3 hours ago
With CIS you can take advantage of F5 LB methods, pool monitors, custom ssl client profiles. Maybe you can achieve the same on OCP, not sure. But when you have people knowledgeable in F5 and load balancing in company you can use them to manage ingress for OCP. It should be more efficient then having them to learn how to do it on OCP.   Just my view.

**Comment by StevenBarre** [comment]
The CIS can be configure to build all route objects on the BIG-IP, or just ones with a specific label.

The BIG-IP has TLS hardware offload for improved performance. Most routes in the platform are TLS enabled using the default cert, so that could be a big plus and remove some load from the Infra nodes.

Today the CIS pod is not very performant at maintaining the config with a lot of routes, but should be addressed in 2.0 along with fixing some [issues](https://github.com/F5Networks/k8s-bigip-ctlr/issues/1281) that prevent all the default OCP routes from working.

BIG-IP likely has issues with larger numbers of objects and will need additional CPU/Memory to handle a large number of routes/pods.

**Comment by StevenBarre** [comment]
Adding here since I don't know where else to put it, hopefully CIS 2.0 will support using CRDs instead of ConfigMaps for non-http virtual servers.

https://github.com/F5Networks/k8s-bigip-ctlr/issues/579

**Comment by jefkel** [comment]
I'm seeing 2 themes here:
1: uncertainty that the CIS can:
- perform well with the large number of routes as our "Default" with the current release of CIS
- be feature compatible with existing route types
(Both of which look to be addressed in a future release)

2: can selectively implement:
- we can look at adding direct F5 integration "as needed" instead of default

It seems like by maintaining the Openshift router ingress as the default ingress we can mitigate both of the uncertainties in the first theme (performance and feature parity) while leveraging the second (ability to selectively implement) to add the features we want from the F5 where appropriate.

Thoughts?

**Comment by jefkel** [comment]
See PR https://github.com/BCDevOps/OpenShift4-RollOut/pull/233 for decision support/recommendations.

**Comment by StevenBarre** [comment]
Blocked while KLAB is moved to the SDN Compartment

**Comment by jefkel** [comment]
F5 and HAProxy decision recommendation can be found here: https://github.com/BCDevOps/OpenShift4-RollOut/blob/master/docs/F5-vs-HAProxy.md

**Comment by StevenBarre** [comment]
We've decided to use the build in HAproxy and only use CIS for non-http once it supports that.
