### ISSUE TITLE
GitOps Configuration Management (Argo)

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#195]
Demo/test leveraging Argo for cluster configuration management tasks:

- [x] RBAC configuration
- [x] Project/Namespace provisioning

**Comment by mitovskaol** [comment]
Still in progress, need more time to explore Argo.

**Comment by StevenBarre** [comment]
@j-pye have you seen https://docs.openshift.com/container-platform/4.4/scalability_and_performance/argocd.html ?

Oh, nevermind. Looks like there's not much info in there. Neat that it does get a mention in the official docs though!
