### ISSUE TITLE
Validate MachineConfig Behavior

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#197]
Answer the following:

How do MachineConfigs rollout when:
- Multiple MCs are created for the same Node Pool
- Master / Worker MCs are created at the same time

**Comment by j-pye** [comment]
OCP 4.4
Notes: 
- Machine Config Operator only takes action on 1 MachineConfigPool and 1 Node at a time. 
- Applying a MachineConfig while another is still rolling out will not impact any additional nodes, rollout proceeds with the updated rendered MC until all nodes are up to date.
- The Machine Config Operator will not remove files even if the rendered config no longer contains those files.
- During one of my tests I lost access to the console / auth for about 3.5 minutes ( stop watch when I noticed) but Apps on the worker nodes were still accessible as expected.

Useful FAQ
https://github.com/openshift/machine-config-operator/blob/master/docs/FAQ.md

@sbarre-esit Anything else you'd like me to look into for this?

**Comment by StevenBarre** [comment]
Refreshing my memory, this is related to https://github.com/bcgov-c/platform-ops/pull/224

So to answer the questions

- Multiple MCs are created for the same Node Pool

If a playbook creates several MCs, one node might have to get restarted twice to get it fully up to date, but the rest of the nodes will only update straight to the latest MCP.

- Master / Worker MCs are created at the same time

MCPs are managed separately and in parallel. So you could have both masters and workers rebooting at the same time.

Is my understanding correct @j-pye

**Comment by mitovskaol** [comment]
Needs more investigation around the behaviour of unschedulable nodes.

**Comment by j-pye** [comment]
@sbarre-esit Finished testing with unscheduled nodes. 

- Multiple MCs are created for the same Node Pool
If a playbook creates several MCs, one node might have to get restarted twice to get it fully up to date, but the rest of the nodes will only update straight to the latest MCP. **Yes, that's correct.**

- Master / Worker MCs are created at the same time
MCPs are managed separately and in parallel. So you could have both masters and workers rebooting at the same time. 

That's also correct. I also tried applying a machineconfig to multiple pools with one pool having unscheduled nodes. Pools updated as expected so long as there was capacity to drain the updating node.

Going to close this. If this requires further investigation I expect it will be due to version changes. Feel free to reopen if needed.
