### ISSUE TITLE
Switch to F5 Operator

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#199]
Do we want to switch from the current automation to the operator? Pros/Cons?

https://devcentral.f5.com/s/articles/Using-F5-BIG-IP-Controller-Operator-for-OpenShift

**Comment by jefkel** [comment]
Assuming no issues with decision in Ticket #194, then I would like to leverage this update as it supports a better pattern for the non-http ingress automation. (ie: leveraging the operator and CRD's for route objects rather than config maps)

**Comment by StevenBarre** [comment]
I don't think the Operator is needed for [CRDs]https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/_static/config_examples/crd/CustomResource.md#how-cis-works-with-crds) ? I think the CIS pods themselves handle the VirtualServer objects. The Operator is just for deploying the CIS pods in a more modern way.

I think I just need to check that the Operator supports all the options we want to set.

**Comment by StevenBarre** [comment]
Based on my reading and experiences with F5 so far, I'm going to vote against using the operator. I think it may be too restrictive in which options it supports vs just creating the deployments myself via ansible. Having direct control of the containers args instead of having an operator in the middle will give us more control and able to use new features more quickly.

The CIS components are not complex and so managing with a few manifests in ansible is easy enough.
