### ISSUE TITLE
Define team member from DXC 

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/OpenShift4-RollOut#2]
Identify the key technical resource from DXC that will be dedicated to this project.

**Comment by tosazuwa** [comment]
Hi @DanDeane , just following up on if we already have the resource confirmed from DXC for the project. Please confirm. Thanks

**Comment by DanDeane** [comment]
Hi @tosazuwa,  yes Steven Barre and myself.

**Comment by tosazuwa** [comment]
Perfect. Thanks
