### ISSUE TITLE
Jenkins Optimization

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#201]
Based on dashboard results, we can get some headroom by reducing jenkins cpu requests; 
- [x] Create dashboard of Jenkins usage
- [ ] Test Jenkins startup time with various configurations
- [ ] Send note to teams around results

**Comment by stewartshea** [comment]
Current dashboard is here: https://app.sysdigcloud.com/#/dashboards/164792/l:3600?scope=kubernetes.pod.name%20contains%20%22jenkins%22

**Comment by StevenBarre** [comment]
This is more https://github.com/BCDevOps/developer-experience than OCP4 I think?

I ran a quick test yesterday of jenkins with limits of 4cpu and 4gi and various requests. Both 1 and 10m request cpu started in the same time.

I think https://access.redhat.com/errata/RHBA-2019:4106 was affecting us though and is now fixed.

**Comment by stewartshea** [comment]
I'd like to run a few more tests and then document who we can target for resource reduction; we can move to the other repo if you like.
