### ISSUE TITLE
Image Registry configuration

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#202]
OCP 4 will leverage Artifactory as a production image registry source with individual OCP Registries for local cluster build/test targets, additional design for backing storage is needed:

- [Object storage is the recommended storage for OpenShift registry](https://docs.openshift.com/container-platform/4.4/scalability_and_performance/optimizing-storage.html#scaled-registry)
- Object storage is supported for Artifactory
- OCIO Object Store service is 1 option
- NetApp storage does NOT include object storage as a service ATM (Would need to build our own service gateway like Minio, etc if we needed to implement a cluster object store.)
- Openshift backing storage should be different than Artifactory backing storage

**Comment by jefkel** [comment]
Todo:
Object Storage:
- [x] create bucket user (thetis cluster)
- [x] create bucket (Thetis test cluster registry)
- [x] validate connectivity/access
- [x] design load test scenario
- [ ] test failure scenarios and document failure outcomes

**Comment by StevenBarre** [comment]
Access validated and built a new image and confirmed it was stored in ECS

**Comment by StevenBarre** [comment]
Going to see if I can re-purpose https://gist.github.com/ervinb/224359235ee046c68fbc9456d6c4662b for testing

**Comment by StevenBarre** [comment]
Test results: object store is MUCH slower than NFS. Pushing a 512Mi image to NFS took 47s and objstor took 124s

Got a hold of some slides from the OCIO Client Forum and not this bit

> typically aimed at object sizes over 100 kilobytes, updated infrequently, retained longer term, and have performance retrieval response targets of 100 milliseconds or more

I'm going to close this and revert to NFS.

**Comment by jefkel** [comment]
@sbarre-esit Great to know, could you update this ticket with the retrieval performance comparison too?  (and if you have more than the single sample for both, this would be a great place to capture that detail)

Putting actual validation numbers here will give a consolidated location if we need to pull that detail for a conversation about Object Store performance in the future.

**Comment by jefkel** [comment]
Regarding external route name (need to customize the default to something more developer friendly)

Some background/ideas:

Current cluster registry:
docker-registry.pathfinder.gov.bc.ca

Name Ideas:
ocp-registry.apps.*{cluster}*.devops.gov.bc.ca
docker-registry.apps.*{cluster}*.devops.gov.bc.ca
openshift-registry.apps.*{cluster}*.devops.gov.bc.ca

**Winning name:**
image-registry.apps.*{cluster}*.devops.gov.bc.ca

**Comment by tosazuwa** [comment]
@sbarre-esit  to update

**Comment by StevenBarre** [comment]
https://image-registry.apps.klab.devops.gov.bc.ca/v2/ up and running. PR to follow soon.

**Comment by StevenBarre** [comment]
> could you update this ticket with the retrieval performance comparison too? 

Results from the benchmark doing a push/pull of images of different sizes

```
Region   Image  (Mb)        Push time (s)  Pull time (s)
pvc      cache-bench-1024  83.903     60.075
objstor  cache-bench-1024  264.221    164.522
pvc      cache-bench-512   54.491     36.340
objstor  cache-bench-512   145.495    94.665
pvc      cache-bench-64    9.942      5.194
objstor  cache-bench-64    22.571     11.656
```

**Comment by jefkel** [comment]
mb and sec?

**Comment by StevenBarre** [comment]
Correct
