### ISSUE TITLE
Name/Label clusters consistently

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#205]
The current cluster naming convention started as "bodies of water", and that naming convention does not match the kprod/cprod/klab names of the physical hosts, or the story telling names of silver/gold.  To reduce confusion when communicating about each cluster, the names used could be consistent.

Names involved:
- Host names for individual nodes/hosts/devices that make up each cluster
  - rename hosts
  - update DNS / Infoblox / asset management
  - Rename ontap SVMs / NetApp devices
  - Ensure DCM Visios are up to date
- Externally accessible names (*.apps.**name**.devops.gov.bc.ca, etc)
  - New TLS certs to match
- cluster names used for story-telling (silver, gold, goldDR, etc)

**Comment by StevenBarre** [comment]
👍 Let's pick one naming convention, then stick with it. Renaming things now will be a bit of a pain, but I'd prefer if hostnames and DNS matched cluster names.

**Comment by jefkel** [comment]
Cluster Naming, to be updated from docs through SSL Certificates

`silver.devops.gov.bc.ca` (production Silver cluster in Kamloops)
`gold.devops.gov.bc.ca` (production Gold cluster in Kamloops)
`golddr.devops.gov.bc.ca` (production Gold (DR) cluster in Calgary)
`klab.devops.gov.bc.ca` (ops lab cluster in Kamloops)
`clab.devops.gov.bc.ca` (ops lab cluster in Calgary)

(Please comment here ASAP if changes are required.)

**Comment by jefkel** [comment]
@sbarre-esit Can you have a look at the list and let me know if we're missing any rename tasks in the description? (once we think we've got a list, we can create tickets for them and match them as dependencies here.)

**Comment by StevenBarre** [comment]
@jefkel description updated with additional tasks

**Comment by StevenBarre** [comment]
@mitovskaol has approved the new names.

**Comment by jefkel** [comment]
Tracking renames of clusters with the redeployment to the SDN networks (which is when they will be renamed)

**Comment by StevenBarre** [comment]
KLAB and SILVER have been renamed. Still working on getting new TLS certs.

CLAB will be up next. Gold and GoldDR don't exist and so don't need any renames.

**Comment by tosazuwa** [comment]
@sbarre-esit , can we create a separate ticket to track the KLAB and SILVER  SSL/TSL certs iStore order?  And link back to this EPIC. It will be easier to track that way.

**Comment by StevenBarre** [comment]
CLAB has now been rebuilt in the SDN compartment (and thus renamed). We also have all the certs needed for it. Calling this done.

https://console-openshift-console.apps.clab.devops.gov.bc.ca/
