### ISSUE TITLE
Integration of logging w/ OCIO SIEM

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#208]
Fwd logs to SIEM for longer-term retention

- [x] determine SIEM end-points
- [x] determine protocol and payloads
- [ ] test out
- [ ] set retention schedules on different types of logs

**Comment by StevenBarre** [comment]
So this has been handled in v4 with https://github.com/bcgov-c/platform-ops/pull/220

> set retention schedules on different types of logs

Who would manage that? Is that something for @NickCorcoran and the SIEM team to work on? or can this be closed now?

**Comment by StevenBarre** [comment]
There are a bunch of improvements in OCP 4.6 to Log Forwarding that need to be re-tested with the SIEM team. Some of the current log forwarding settings had to be removed to fix issues in the current version of logging.

**Comment by NickCorcoran** [comment]
@sbarre-esit, the retentions will be something I work on w/ the SIEM team.  As it's part of their side config, and not ours, I think we can close this and I'll follow up w/ them in collaboration w/ OCIO security investigations.  I'll make my own ticket to track that.

**Comment by NickCorcoran** [comment]
Closed and continued with https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1096
