### ISSUE TITLE
Energize racks for Silver cluster

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#210]
The 3 racks for the silver cluster have been upgraded to support additional power needed for the high density nodes.

However, the datacenter needs to take 3 planned maintenance windows to energize the racks.

This is required to be able to power up any of the equipment in these racks.

**Comment by stregear** [comment]
DXC DCM sent in request to Q9  proceed and have requested new dates to light up the rack, Q9 will work with ICBC to find a date/time.   Q9 would like to avoid starting May 25th and June 5th.   Q9 will come back with dates, if they are told there is still a freeze Sharon will escalate to David Ell.  The 3 maintenance windows will take between 3 and 4 weeks to complete.

**Comment by StevenBarre** [comment]
These have now been scheduled

- Branch Circuit Maintenance – BLUE on  June 18
- Branch Circuit Maintenance - RED on June 21
- Branch Circuit Maintenance - YELLOW on June 25

**Comment by StevenBarre** [comment]
All Silver racks energized
