### ISSUE TITLE
Document OCP4 Upgrade proceedure

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#211]
Write documentation on how to perform a OCP4 upgrade and which order clusters should be done in.

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/advsol-docs/pull/109

**Comment by StevenBarre** [comment]
@jefkel do I have the correct patching order in https://github.com/bcgov-c/advsol-docs/pull/109/files#diff-6c37ee1b50cdde5b34d4168785f05a1f5aee73c11d89a779f95ec2e6f99a65dfR3 ?

**Comment by jefkel** [comment]
That looks good.

Note: Re: patching, have you identified the configuration manifest that can be updated to kick off the upgrade? (to allow us to trigger the patch through the CCM workflow with approvals, etc..)

**Comment by jefkel** [comment]
might be good to put some words around the timing between GoldDR and Gold cluster upgrades (to indicate the application responsibility to validate their application in the DR cluster within the timeframe)... 

Alternatively, we can upgrade the Gold cluster first (and if there are service impacts, the DR site is still the "last known good" for failover?)

**Comment by StevenBarre** [comment]
> have you identified the configuration manifest that can be updated to kick off the upgrade?

@jefkel there is none documented. The [docs](https://docs.openshift.com/container-platform/4.6/updating/updating-cluster-between-minor.html) state

> Because of the difficulty of changing update channels by using oc, use the web console to change the update channel.

Referring to changing from `stable-4.5` to `stable-4.6`

Once on the right channel you can [use the cli](https://docs.openshift.com/container-platform/4.6/updating/updating-cluster-cli.html#update-upgrading-cli_updating-cluster-cli) to `oc adm upgrade`. But it is not apparent what that command does. It doesn't appear to be a trivial object patch though.

**Comment by StevenBarre** [comment]
@mitovskaol thoughts on timing and order of gold/golddr cluster upgrades? I'm personally a fan of doing Gold first so people can fail over to the "known good" Gold DR if there are any issues. Once everyone has failed back and Gold is called good we can move on to Gold DR.

**Comment by mitovskaol** [comment]
@sbarre-esit  I like the idea of patching Gold first so that the apps can failover to Gold DR that would still run on the last stable version, if needed. And Gold DR will be patched last so that the patching order for the OCP 4 Plattform can look like following: 
KALB -> CLAB -> Silver -> Gold -> Gold DR
We should probably leave the ARO cluster out as it will be patched by Mcrosoft and my understanding is that we will have litttle control over the timing of the upgrades, they happen as soon as a new version or a patch becomes available. 
What do you think?

**Comment by StevenBarre** [comment]
@mitovskaol how long should we give teams between GOLD and GOLDDR to validate their apps? Would one week be enough?

As for ARO, my understanding was that point releases were auto-installed if they fixed a security issue. ie: 4.5.14 -> 4.5.16 . Minor version upgrades would become available, then later are forced if you haven't done it yourself yet. ie 4.5 -> 4.6. So we can trigger them on our own schedule as long as we do it before the deadline. Maybe @stewartshea can shed some more light here?

**Comment by mitovskaol** [comment]
@sbarre-esit  one week wait between Gold and Gold DR patching seems good to me.  If @stewartshea can confirm that we have control over the major version upgrades in ARO, then the upgrade sequence could be as this:
KALB -> 2 days -> CLAB -> 2 days -> ARO -> 2 days -> Silver -> 1 week -> Gold -> 1 week -> Gold DR

**Comment by stewartshea** [comment]
Indeed, as far as I'm aware (and as has been my experience so far), the
upgrades to the ARO clusters need to be manually triggered by a user with a
cluster-admin role.

**Comment by mitovskaol** [comment]
KALB -> 2 days -> CLAB -> 1 days -> ARO LAB -> 1 days -> ARO Pathfinder -> 2 days -> Silver -> 1 week -> Gold -> 1 week -> Gold DR
