### ISSUE TITLE
Create ETCD Backup / Restore tools

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#216]
**Describe the issue**
ETCD is the core storage of all OCP configs. For disaster recovery purposes it should be backed up.
https://docs.openshift.com/container-platform/4.5/backup_and_restore/backing-up-etcd.html

**Definition of done Checklist (where applicable)**
- [x] Create tooling to back up ETCD
- [x] Document tooling
- [ ] Document restore process

**Comment by StevenBarre** [comment]
https://github.com/sushilsuresh/ocp4-ansible-roles/tree/master/roles/etcd-backup might be worth stealing

**Comment by wmhutchison** [comment]
Will check out the link - moving this into In Progress with the intent of starting actual work on this during this week.

**Comment by StevenBarre** [comment]
PR for tool https://github.com/bcgov-c/platform-tools/pull/21

**Comment by StevenBarre** [comment]
PR merged. Applied to Silver.

**Comment by StevenBarre** [comment]
Reopening since cron is failing in Silver

**Comment by StevenBarre** [comment]
Works in KLAB but fails in SILVER. Switching the namespace to Discovery Mode in Aporeto seems to solve the issue, but no flows are showing rejected so that we could write NSP to cover it.

**Comment by StevenBarre** [comment]
NSP created https://github.com/bcgov-c/platform-tools/pull/22 but also need some changes in Aporeto enforcer policy from @j-pye
