### ISSUE TITLE
Create pruning tools

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#217]
**Describe the issue**
An OpenShift cluster needs regular pruning to keep healthy. This includes the image registry soft and hard prune, as well as old builds and deployments.
https://docs.openshift.com/container-platform/4.4/applications/pruning-objects.html

Develop the needed CronJobs or other tooling to effect the pruning of the cluster

**Definition of done Checklist (where applicable)**
- [x] Image Registry Soft Prune
- [ ] Image Registry Hard Prune
- [x] Deployments Prune
- [x] Builds Prune

**Comment by StevenBarre** [comment]
Builds and deployment https://github.com/bcgov-c/platform-tools/pull/19

**Comment by StevenBarre** [comment]
Image Registry Soft Prune is handled by OCP, though it still has some bugs to work out. Waiting on an RFE from RH to improve it.

**Comment by StevenBarre** [comment]
The image registry hard prune we have automated for v3 only runs once a quarter and is unreliable. There's a lot of edge cases that can cause it to fail and leave the registry in read-only mode. Combined with the fact this change is not being announced to the users of the platform causes some people headaches until Ops can get in and fix things up. I don't think automation is making our lives better in this case.

I purpose that for v4 we simply treat hard pruning as part of quarterly patching and perform it during a Sunday morning change window. Then it can be properly announced to platform users via the usual channels and can be worked to completion by an ops person.

@mitovskaol @jefkel @wmhutchison thoughts?

**Comment by mitovskaol** [comment]
@sbarre-esit  I think combining hard pruning and quaterly patching is a great idea. Is there a standard template for patching announcement that you use? If so, it can be updated to mentiong the registry prune, this way it will be communicated through the alerts channel together with the patching announcement.

**Comment by StevenBarre** [comment]
I believe we just copy/paste from the previous quarters notification https://github.com/BCDevOps/platform-services-status-page-notifications/pull/90/files#diff-205535369f996e68de91f1f5c7da07a4 . But we might do the pruning as a separate RFC/notification and just do it once a quarter.

**Comment by mitovskaol** [comment]
Sounds good as long as we don't forget to announce it to the Platform teams :)

**Comment by jefkel** [comment]
I am not sure that I agree that automation is not making our lives better here.

I thought that the issues leading up to the registry remaining in ReadOnly mode were not issues that required intervention (ie: when the issue was addressed, the ONLY thing that needed to be done was to redeploy the registry in RW mode?)

From an automation perspective, the outstanding work was to have a hard cutoff for how long the process could run, and then (perhaps) a backup automation to check/ensure the registry was switched back to RW mode after a success/partial success/failed run of the prune?

If you're running the same process manually during a patch window, what exactly will be the difference? (ie: you'll run the prune, wait a long time.. and then check that it goes back to RW mode before troubleshooting any failures?)

**Comment by jefkel** [comment]
The developer impact is not relevant to an automation discussion other than the lack of announcements (maybe adding an RC announcement in the hard prune automation can help here?)

The troubleshooting that happens afterward is more related to how we prune, not whether the pruning is done via automation.

**Comment by jefkel** [comment]
As the platform get's larger, and the registry more active, the expectation is that a hard prune (that helps cleanup used storage) could be run on a more frequent basis (assuming automation is in place and it doesn't require a lot of manual overhead)

**Comment by StevenBarre** [comment]
I think the biggest problems come from an inability to test at scale without overtime or impact to users during the day, and part from the failure modes of pruning being an unknown black box. The pruner always runs fine in LAB. Only running it in PROD once a quarter and hoping you can figure out why it failed and fix it for next quarter is a nightmare. And running it multiple times with a human watching to watch logs and understand why its failing requires someone working a weekend or taking down the registry during business hours.

> If you're running the same process manually during a patch window, what exactly will be the difference?

- Put registry into read-only
- Run prune operation
- Verify no errors in the logs
  - If errors, use wetware to resolve and rerun pruner or otherwise get registry into healthy state
- Put registry into read-write mode

The current process is "Oops, something went wrong", then devs cant push until one of us shows up at 9am the next business day. We investigate and can't figure out why it failed from the logs. We can't re-run the automation while observing to attempt to reproduce the error. So we just add some more monitoring and hope it works better next quarter.

**Comment by jefkel** [comment]
It seems like the manual step comment is missing the registry read-only remediation steps you take?

From my understanding, the remediation steps are 
a) check state of job - (seems like it's usually "failed" by 9am?)
b) manually change deployment variable back to RW mode, and redeploy
c) confirm registry in RW mode (service restored)
d) gather as many logs as possible for failure investigation...

If the above is the case, I'm not sure what would be stopping us from adding the automation for steps a,b,c and possibly even a lot of d?  To solve the issue of waiting until 9:00am, it feels like we can create monitoring/alerting on the job itself - and if no progress/etc by a specific window or time frame, then we assume failure, stop/kill job, recover registry as per steps above, and if those don't work.. page?

The goal here is NOT to create additional manual effort - but rather to create an automated process that can help reduce the manual effort.  By adding a manual run of the hard prune to a quarterly effort, it feels like we're going the opposite direction to where we want to go.

**Comment by jefkel** [comment]
hmm.. or.. we can do a short term compromize?

Continue to run an auto-schedule
time it to start in a specific weekend window (instead of running between midnight and 5am?)
page if there are errors that end the job with a fail
page if the job goes longer than X hours

Ideally, if you're paging for a failure, you could also automate the service restart (either to be manually triggered by the on-call person, or possibly to be triggered by a monitoring tool?)

**Comment by StevenBarre** [comment]
Built in soft pruner is enabled. But it fails to restart the registry to clear the caches.

Attempts to manually perform a restart fail due to the deployment being controlled by the operator.

Case 02694771 is open with Red Hat to track that the built in pruner fails to restart the registry as per the docs and the RFE.

Moving to blocked waiting on the RFE.

**Comment by StevenBarre** [comment]
Result of RFE

> The blob caches now operate on a 10 minute TTL in 4.4+.
>
> This will greatly reduce the risk of hitting this issue.
>
> Engineering points of view is that because of how the cache works, you can not eliminate 100% of the risk as something could be pruned cached and re-pushed while the pruner is still running and before any restart / ttl takes place.
>
> The TTL reduced the need to have to restart things and gives a maximum of 10 minutes before the caches are updated.

Since we run the soft-prune at 5am there's very little risk of pushing images then.
