### ISSUE TITLE
Default namespace NetworkPolicy

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#226]
Implement (partial) Zero trust network policy as the default for namespaces in the clusters.

Base Allow (for cluster operations):
- [ ] OpenShift monitoring access
- [ ] OpenShift ingress access **(?)**
- [ ] more ... ?

**Comment by j-pye** [comment]
I believe this has been tacked now but I'll leave it for you to close since you're the author @jefkel
