### ISSUE TITLE
Automate F5 Virtual Server to Service Mapping

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#227]
Automation is required for creating non-http ingress, but should not allow direct manipulation of the F5 resource by development teams.

Current idea:
CR in app namespace requesting F5 server mapping to specific service.
Operator creates F5 Server -> namespace service ingress (using specific IP/port from a managed pool)
Operator updates app namespace CR with external IP:Port assignment.

Assumes that F5 configuration can be in a cluster-managed namespace and is not required to be in the same namespace as the application service.

**Comment by mitovskaol** [comment]
@jleach Is this still relevant or it has been addressed through KNPs?

**Comment by j-pye** [comment]
@mitovskaol  Still relevant. This is to make CLAB to KLAB and Calgary Gold to Kamloops Gold non-http traffic possible for teams.

**Comment by wmhutchison** [comment]
Adding to Sprint Backlog for now to investigate more fully since it'll be part of the whole GOLD solution (GOLD/GOLD DR).

**Comment by jleach** [comment]
I think this is probably a duplicate of a ticket @j-pye created to write an operator to do this work. He's 99.9% done.

**Comment by mitovskaol** [comment]
@j-pye Can you please confirm this is the duplicate and if yes, close it, please.

**Comment by j-pye** [comment]
Yes, it is.
