### ISSUE TITLE
SDN Compartment is Available- Klab

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/OpenShift4-RollOut#228]
This is the external dependency to track the status of the SDN Compartment that is being built by the Hosting Branch and needs to be available before the OCP 4 Clusters can be deployed there.

- [x] VLAN for hosts and F5 for NATing
- [x] Public IP addresses routing to the new VLAN

**Comment by tosazuwa** [comment]
@stregear to update with dates and % completion
