### ISSUE TITLE
Determine Implementation design pattern for Artifactory in OCP 4 (SPIKE)

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/OpenShift4-RollOut#230]
Explore the use case of using Artifactory as a primary production image repository 

Design Elements:
- [ ] Integration with AQUA for Artifactory use enforcement for production deployments
- [ ] Cross cluster sync for image repositories
- [x] Pull-Through/Caching repository for external repo sources (dockerhub/redhat/etc)
- [x] Additional project provisioning requirements

**Comment by mitovskaol** [comment]
Moving to the Backlog to discuss in the next Sprint Planning.

**Comment by caggles** [comment]
closed as out-dated

**Comment by jefkel** [comment]
Please update with tickets that capture the design requirements for the following:
- Aqua integration design
- cross cluster sync (ie: multi-cluster artifactory deployment designs)
