### ISSUE TITLE
Move Azure Diagram to Documize

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#234]
- [x] put the following diagram under the protected space in Documize together with the rest of the OCP 4 diagrams
- [x] remove from github content
https://github.com/BCDevOps/OpenShift4-RollOut/blob/master/openshift4-azure/docs/azure-ocp4-network-diagram.png

**Comment by tosazuwa** [comment]
Move to Archive folder in Documize-Tolu
