### ISSUE TITLE
Separate OPS from Developer logs

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#235]
RedHat Recommendation for our OCP deployment was to look at separating the operational logs from the developer logs.  To design a split logging system, the following pieces of information are for planning purposes:

**DoD:**
- [x] Gather current log utilization averages for future planning
- [x] Determine internal log support for splitting log services as described.

**Outcomes**
No separation of logging is supported with OCP4, so will not be implemented for any cluster-internal logging.

Current usage and base requirements for future planning.
**Log Ingestion Rate**
Specific for Elastisearch node and storage sizing
- Avg Operational log amount per day --- *21 Gi*
- Shards / day --- *2*
- Target Number of days of Retention --- *14 days*

- Avg Developer log amount per day --- *115 Gi*
- Shards / day --- *2 per namespace = ~1600 - 2000 / day*
- Target Number of days of Retention --- *14 days*

**concurrent users**
approx. number of concurrent users (to help with Kibana and loadbalancer sizing)
Calculating based on 1/2 of the # of project sets as a concurrent access (could be 1/4?)
*50 - 100 concurrent users*

**backup requirements**
No platform specific backup requirements at this time (other than the expected resilient data storage)
Separating out Audit logs (both API audit and Node auditd logs) for export will be a need.

**Comment by jefkel** [comment]
@sbarre-esit could you update this ticket with the current ingestion averages for the OCP3 platform, storage size/consumed, shards, etc?

**Comment by StevenBarre** [comment]
Ops logs per day average. Total storage required would be double as there are two copies of the data.
```
$ oc -n logging exec $ES_POD -c elasticsearch -- curl -s -k --cert /etc/elasticsearch/secret/admin-cert --key /etc/elasticsearch/secret/admin-key https://logging-es:9200/_cat/indices/.operations.*?v | grep -E '2020.05.2[2-7]' | awk 'BEGIN { SUM=0 } {if ($10 ~ "gb") $10=$10*1024"mb"; if ($10 ~ "mb") $10=$10*1024"kb"; if ($10 ~ "kb") $10=$10*1024; SUM+=$10} END { print SUM/1024/1024/1024/6"gb"}'
20.8333gb
```

Developer logs per day average. Total storage required would be double as there are two copies of the data.
```
$ oc -n logging exec $ES_POD -c elasticsearch -- curl -s -k --cert /etc/elasticsearch/secret/admin-cert --key /etc/elasticsearch/secret/admin-key https://logging-es:9200/_cat/indices/project.*?v | grep -E '2020.05.2[2-7]' | awk 'BEGIN { SUM=0 } {if ($10 ~ "gb") $10=$10*1024"mb"; if ($10 ~ "mb") $10=$10*1024"kb"; if ($10 ~ "kb") $10=$10*1024; SUM+=$10} END { print SUM/1024/1024/1024/6"gb"}'
111.43gb
```

Plus account for some free space, as ES gets grumpy above about 80% per node.

**Comment by StevenBarre** [comment]
We should also take into consideration the number of ES nodes needed. Matt has previously told me ES doesn't scale much past 64G of Memory. Half of that is for the Java heap. [ES recommends](https://www.elastic.co/guide/en/elasticsearch/reference/current/scalability.html) 20 shards per GB of heap. There are 2 shards per namespace per day.

**Comment by StevenBarre** [comment]
As ops logs are fairly small, if we are separating them out I'd prefer we look at a longer retention, say 30 days, as finding stuff in Kibana can be quite helpful for debugging cases with Red Hat. Cases aren't always resolved in under 7 days and we need to look back further.

**Comment by StevenBarre** [comment]
I've opened a case with Red Hat to double check some of my previous assumptions around ES pod sizing.

**Comment by StevenBarre** [comment]
Here are some details around logging config and scale.

Tested with: GCP n1-standard-64 for ElasticSearch nodes
GCP: 64 core, 240GB RAM

Worker nodes: n1-standard-4
GCP: 4CPU, 15GB RAM

ElasticSearch configured with 3 nodes, SingleRedundancy, 61GB pod memory request and limit and 36 cpu request and limit and 200GB storage
fluentd: Pods producing increasing rates of messages to stdout from 1000 1KB messages/second up to 4000 1KB messages/second/node

ES creates 1 shard per index per ES node - in prod with 3 nodes, you get 3 indexes per shard and maintain full redundancy with a 1 node failure using SingleRedundancy
ES: 50000 1KB messages/second indexed reliably at 54 G average RSS and 18 cores

Pods and messages spread across 150 namespaces

You can find some more details on the Logging CR and the difference SingleRedundancy modes here: https://docs.openshift.com/container-platform/4.4/logging/config/cluster-logging-configuring-about.html

You can find some details on recommended host best practices here and some more interesting data that gets updated by the perf scale team in the rest of the scale section:
https://docs.openshift.com/container-platform/4.4/scalability_and_performance/recommended-host-practices.html#recommended-node-host-practices

**Comment by StevenBarre** [comment]
In OCP 4.5 ES will be changed to not use an index per project, so ES should be much more efficient with its resource usage. See https://github.com/openshift/enhancements/blob/master/enhancements/cluster-logging/cluster-logging-es-rollover-data-design.md for more details.

I think going with 3 nodes at 64Gi memory as we have in OCP3 should be fine for OCP4

**Comment by StevenBarre** [comment]
https://docs.openshift.com/container-platform/4.4/logging/cluster-logging-deploying-about.html#cluster-logging-deploy-storage-considerations_cluster-logging-deploying-about

>Therefore, consider how much data you need in advance and that you are aggregating application log data. Some Elasticsearch users have found that it is necessary to keep absolute storage consumption around 50% and below 70% at all times. This helps to avoid Elasticsearch becoming unresponsive during large merge operations.
>
>By default, at 85% Elasticsearch stops allocating new data to the node, at 90% Elasticsearch attempts to relocate existing shards from that node to other nodes if possible. But if no nodes have free capacity below 85%, Elasticsearch effectively rejects creating new indices and becomes RED.

**Comment by StevenBarre** [comment]
I'm not even sure OCP4 supports separating the ops and apps logs? Opened a case with RH to ask.

**Comment by StevenBarre** [comment]
>  The answer from the logging team is that an ops cluster is not a feature that will be added in 4.x.

**Comment by StevenBarre** [comment]
@jefkel can you help me create a DoD for this ticket?

I think we are done based on
1. OCP4 does not support separating Ops and Apps logs
2. OCP 4.5 switches to using one index for all logs, allowing better scaling
3. We've decided that 3 ES nodes with 64Gi RAM will be sufficient for our needs
4. I documented the current log volume
5. We've got log forwarding to the province SIEM set up via another ticket

**Comment by jefkel** [comment]
updated description with clear DoD as well as summary of planning information gathered.
