### ISSUE TITLE
Vault Automation Design for OCP 4

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#238]
- Work with Jeff/Marek to determine Vault design.

**Comment by j-pye** [comment]
We still need to figure out the definition of done for this but the initial design and implementation can be found at:

https://github.com/BCDevOps/platform-services/tree/feature/hc-vault/security/vault

**Comment by manderson-it** [comment]
test comment

**Comment by manderson-it** [comment]
- @j-pye, Steven Barre (DXC), and I discussed the initial draft for the traffic flow through the load balancer into the OCP cluster today. I am updating the diagram right now and will post the updated version in our rocketchat channel

**Comment by manderson-it** [comment]
- @stewartshea reached out to Shea P. to provision Azure Key Vaults, which are used to provide Auto-Unseal to HashiCorp Vault.

**Comment by stewartshea** [comment]
I've had to reach out to Andy to get an SP created in Azure which will then allow us to use tf cloud to build the key vaults

**Comment by manderson-it** [comment]
The initial design is completed. Future efforts will be captured in a new Vault Deployment Validation issue.
