### ISSUE TITLE
Create Platform Services Azure Deployment Plan (Terraform + Ansible)

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#25]
Deployment and post deployment configuration of the OCP4 cluster in Azure should be as automated as possible. The installer is pretty automated with the use of an install-config.yaml. There may be some issues with terraform calling the terraform installer.

- [x] install-config.yaml settings & process documented
- [x] Post install config process ,finalized. TF? Ansible?
- [x] Everything documented
- [x] Post deployment github config

**Comment by filiy** [comment]
Work has been started. Terraform local-exec calling the openshift installer doesn't work well (terraform calling terraform). May need to use a ansible as the wrapper.

Post-install config started with terraform. Using local exec and `oc` commands for now. Will need to add storage account creation for the file SC.

**Comment by filiy** [comment]
Made some more updates to TF post config. Will need to test this with an new cluster install.

**Comment by filiy** [comment]
This is done. Needs a final test.

**Comment by tosazuwa** [comment]
Completed
