### ISSUE TITLE
Update Cluster Hardware documentation

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#253]
**Purpose: **
Keep the shared *BCGov OCP4 Cluster Worksheets* spreadsheet up to date with hardware assignments

**Background:**
Found in the shared Google Drive:
`Openshift 4 Buildout Project`->`Technical Diagrams/Design/Architecture`->`BCGov OCP4 Cluster Worksheets`

**Release 2: Cluster Infrastructure** tab reflects current (pre-migration) cluster hardware lists.
**Release 3: Cluster Infrastructure** tab reflects end state (post-migration) cluster hardware lists.

These lists need to be kept up to date with the ordered hardware.

**Comment by StevenBarre** [comment]
@stregear @Joe-Craig can one of you take this on? I don't know the details of the 8 new hosts.

**Comment by jefkel** [comment]
@mitovskaol , @Joe-Craig Quick question re: 8 new hosts (and 6 VM's for existing 3.11 too I guess)

Have additional RedHat OCP entitlements been ordered with the VMs and the 8 additional hosts?  (Those extra cores are NOT covered under the existing core entitlement counts we have available)

**Comment by Joe-Craig** [comment]
@jefkel We have not received any request to purchase more RedHat subscriptions. Either for the 8 new nodes or the 6 Vms.

**Comment by StevenBarre** [comment]
The "Gold SCO" includes 3 masters and 19 worker/infras. @jefkel and @mitovskaol to discuss early next week how many are going into Gold and how many into Silver. GoldDR will be sized to match Gold.

**Comment by StevenBarre** [comment]
Docs updated.
