### ISSUE TITLE
Request second set of Internal Cluster IP Ranges

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#255]
An extra set of Internal Cluster IP Ranges has been recommended:
https://github.com/BCDevOps/OpenShift4-RollOut/blob/master/docs/Cluster-Internal-networks.md

- [x] 2 new Private, Non-Routable /16 networks to be requested.  These networks will be the internal cluster networks for the Calgary DC (Region) clusters.
- [x] Architecture documentation updated with new networks

**Comment by StevenBarre** [comment]
Requested. Got some pushback and provided some more details.

**Comment by jefkel** [comment]
Had a call with David Ell, seems like we reached a go forward:

- Separate /16's for Kamloops and Calgary works better for OCIO tracking of private network usage
- We get different internal IP blocks for potential service discovery in the future (across regions)

win/win for us I think?

**Comment by jefkel** [comment]
From Brian Price:
>Thanks Jeff and Steven for providing more details on this request.
>
>I’ve submitted a request for these blocks of private IPs and will forward the addresses once they’ve been reserved.

**Comment by StevenBarre** [comment]
OCIO has supplied the two new OCP Cluster Networks for use on Calgary clusters.

@jefkel which docs specifically need updating? How do I effect those changes?

**Comment by StevenBarre** [comment]
Added Cluster and Service Networks to https://docs.google.com/spreadsheets/d/17TEPNx5_UbH-ZbPMChcw9Px6vbyR1-gIIuAc9D7ae-I/edit#gid=0
