### ISSUE TITLE
Hashicorp Vault Points of Contact

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#256]
Who are our points of contact for Hashicorp Vault:

- Subscriptions/Licensing/Access?
- Enterprise Support contact?

**Comment by mitovskaol** [comment]
Assigning to @stewartshea who is our inital point of contact for Hashicorp licenses. Shea, can you please respond to Justin's questions above. Thanks!

**Comment by stewartshea** [comment]
I've sent an introductory email :)
