### ISSUE TITLE
ARO DNS Decision for Canadian Deployment

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#259]
We will need a subdomain created and delegated to Azure for ARO related clusters. 
- [x] Determine subdomain
- [x] Create delegation records to Azure DNS

**Comment by StevenBarre** [comment]
@jefkel @mitovskaol any ideas what we are naming this cluster?

**Comment by stewartshea** [comment]
@sbarre-esit I don't think it's about the specific cluster name yet,  but more about the subdomain it will belong to. I'm thinking something like aro.devops.gov.bc.ca?

**Comment by mitovskaol** [comment]
I like the aro.devops.gov.bc.ca!

**Comment by StevenBarre** [comment]
Done!
