### ISSUE TITLE
Obtain Azure account access determine account credential management strategy

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#26]
- [x] Phil user access to Azure portal
- [x] SP account for OCP4 cluster
- [x] SP account permission set up
- [x]  Store creds in Azure KeyVault

**Comment by filiy** [comment]
We have a test Azure subscription that is more open that we are using to test Azure deployments `DevOps Platform Services`. 

There is also another subscription and RG that is more locked down that sounds like will be the final install place. Permissions are still being sorted out for this.

**Comment by filiy** [comment]
Azure keyvault seems to be working well for storing cluster related creds.

**Comment by filiy** [comment]
Need to test OCP 4.3 installer in Azure to see if it is more flexible that 4.2 installer.

**Comment by filiy** [comment]
Need to finalize this with Jon

**Comment by filiy** [comment]
This is done and documented.
