### ISSUE TITLE
Discuss Alternatives for Handling Aporeto Failure

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#261]
The purpose of this ticket is to track our plan for Aporeto Outages (partial and complete)

We need to monitor that an Aporeto enforcer on a node is up and healthy:

 - [ ] move Aporeto enforcers daemon set as well as Aporeto and bcgov operators into the **"openshift-advsol-aporeto-*"** namespace so that it can be monitored automatically by the built-in Openshift and Kubernetes monitoring. (@j-pye)

- [ ] Configure notification for failed Aporeto pods (@sbarre-esit) [Ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/474)
The Aporeto enforcer runs a single pod per node so it is no redundancy. If any of the Aporeto pods running in **"openshift-advsol-aporeto-*"**  namespace fails and cannot recover in **15 minutes**, the pre-built OCP monitoring mechanism will send a notification to Rocketchat (Severity = INFO and above) and an email will be sent to the on-call team (Severity = CRITICAL). The on-call team will **manually** cordone the node with the failed Aporeto pod, drain it and migrate worklods to another node with a healthy enforcer.

Aporeto Namespace Migration Steps (High Level):
    - Change Ansible playbook to use an alternative namespace name and node label for the 3 enforcer daemonsets (master,infra,worker)
    - Add Old Label Removal to node labeling playbook
    - Run deploy playbook against cluster
    - Run Node Labeling Playbook against cluster -- This playbook will drain and cordon each node (1 at a time), remove the old label bringing down the existing enforcer pod in the old namespace, and add the new label bringing up the enforcer pod in the new namespace, then do a health check and uncordon the node so the playbook can move onto the next node.  
- [ ] Implement label removal into Node Labeling Playbook

- [ ] Create a custom script (in a separate ticket) to monitor that the number of running Aporeto pods and compare to the number of nodes in the cluster and if the numbers do not match, raise an alarm (RC + email on-call team). (@sbarre-esit) [Ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/475)

@j-pye To reach out to Aporeto to ask if there are other recommendaiton for monitoring Aporeto health.

**Comment by j-pye** [comment]
Meeting scheduled for July 28th at 11am.

**Comment by j-pye** [comment]
**Meeting Notes: (July 28th, 2020)**
- On August 4th, we have a meeting with PANW to discuss ongoing support, recommendations for handling enforcer/defender failure, prisma cloud features, etc.
- (ACTION) - Open a support case with PANW to get information on recommended practices for network policy and handling outages. 
- An automated solution is needed for handling a full outage and possibly a partial outage. This automation may be manually triggered or automatically triggered if concern for automation failure can be addressed.

 
**Partial Outage:**
- Suggested actions for a partial outage are currently to use Taints and/or Cordon/Drain the node. Treating it like standard maintenance to ensure there are no tenant applications on an un-enforced / un-defended node. 

**Full Outage:**
Fail Closed - In the case of a full outage it may be desirable to block inbound communication to the node from external sources. Internal communication with DXC and OpenShift Core components would be left intact in order to maintain cluster stability.  During this time tenant apps could be scaled to zero if desired.

Once a solution is put in place to secure the cluster, communication with the outside world can be opened again. 

Fail Open - **NO!**

Mixed - As an alternative for handling a full outage, it was suggested that we allow Inbound communication to continue but lock down inter-namespace communication. This gives tenants the option to scale down their secure applications but leaves room for applications that don't require a zero-trust environment to continue running. (Automation and Effort will likely be much higher for this option but could allow for an opt-in / opt-out for scaling down)

**Additional Notes:**
- Many of the suggestions here may change based on upcoming discussions with PANW.
- Istio needs to be investigated for cluster-to-cluster app communication and has the benefit of mTLS.
- Namespace isolation (Similar to OCP 3.11) could be implemented in OCP4, however, this will most likely require DXC or Platform-Services involvement when tenants need multiple namespaces to be able to communicate without the use of OpenShift Routes. (In OCP4 there may be a simpler way to achieve this, investigation required.)

If I missed something please let me know :)

cc: @mitovskaol @jefkel @NickCorcoran @stewartshea @sbarre-esit @juhewitt

**Comment by j-pye** [comment]
Moving to the backlog. Meeting scheduled for September 21st @ 11am

**Comment by j-pye** [comment]
Meeting was Rescheduled for September 22nd due to our Aporeto Contact being unavailable.

September 22, 2020
Meeting Notes / Action Items: 
- Recommend policy backups to git on a nightly basis - Done
- Test backup restore process - ToDo
- Generate list of email recipients to subscribe to aporeto releases - ToDo
- Recommend node evac/cordon on enforcer failure
- Recommend Fail Closed on Enforcer Failure
- Aporeto SaaS failure will result in the enforcers continuing to enforce policies that have already been applied before the failure.
- Aporeto SaaS provides 99.9% uptime through Google Cloud Platform
- Policy Review with PANW/Aporeto Engineers planned for Tuesday, September 29th.

External Action Items:
- Update Helm Chart
- Update Documentation around Managed Networks
- Update Releases page with Release Versions
- Investigate queue drop errors in Enforcer logs

**Comment by mitovskaol** [comment]
thank you for capturing the meeting notes @j-pye !
A couple of comments:
re:  Recommend Fail Closed on Enforcer Failure 

- when an enforcer fails on a node, a monitoring script will detect the failure (how?) and will force evac all pods from the impacted node to another healthy node.
- when all enforcers fail on all the nodes, the monitoring scripts will detect that and will trigger the switch in the custom bcgov operators to fail over to using the Openshift native security policies. To Do: development effort is required to update the operator with the switch functionality and to create high level Openshift-native NSPs with the same rules that Aporeto NSPs have, and that will be activated when Aporeto is down.

**Comment by mitovskaol** [comment]
@j-pye Can you please confirm that the actions listed in my previous comment have been implemented (maybe at least the first one ?) in SILVER?

**Comment by jefkel** [comment]
Looking through the tasks, I am unable to find implementation tasks associated with the output of this ticket, I would expect to see:
Ticket: Monitor enforcer daemonset on each node
Ticket: Monitoring of enforcer daemonset to add additional action to add a taint label to a node when the enforcer is in a "failed" state.

Those would be the implementation steps I could see for your first bullet.

As for your second bullet, there would be a very large amount of effort to implement this.  The designs and estimates for this work have not been started.  The last conversation I can recall for this point was that we were not planning on implementing this at this time.

**Comment by StevenBarre** [comment]
Switching namespaces was abandoned due to difficulty.

Monitoring pod counts was implemented in Silver.

Additional prometheus based monitoring was done in KLAB, but not promoted to Silver.

Suggest we close this ticket now that we are moving towards SDN instead of Aporeto.
