### ISSUE TITLE
CCM Integrations for DevSecOps Tools

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#270]
EPIC to track the deployment of the platform operations tools/services required for a working cluster.

- [x] SysDig
- [ ] AdvSol Monitoring
- [ ] Vault
- [ ] Artifactory
- [x] Aqua

**Comment by j-pye** [comment]
Vault is in progress. 
Can't speak to AdvSol Monitoring
Artifactory hasn't be done. The app or Archeobot (operator)

**Comment by mitovskaol** [comment]
This work will tracked in separate tickets for each individual tool.
