### ISSUE TITLE
Network Policy updates

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/OpenShift4-RollOut#278]
Work with hosting on updates to network policy to include details on software defined networking to support new network zone and use on OpenShift.

**Comment by tosazuwa** [comment]
@NickCorcoran , is this a duplicate ticket?

**Comment by NickCorcoran** [comment]
@tosazuwa, I closed it on the other board and created here since moving between boards strips anything useful anyhow.

**Comment by mitovskaol** [comment]
@NickCorcoran is this still relevant?

**Comment by NickCorcoran** [comment]
@mitovskaol I think w/ Hosting working on the SDN Zone and AG's involvement there, my contributions will be less as they should be doing the heavy lifting on policy updates.  Will lower estimate, but is still something that will at least need my review cycles.

**Comment by mitovskaol** [comment]
No longer relevant. if needed, the new work will be tracked in a different ticket.
