### ISSUE TITLE
DNS Names and SSL Certs for Vault

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#279]
In order to get Vault into a production ready state we need to setup DNS records for Vault as a Service and request the appropriate SSL Certs for those DNS entries.

**Additional Information**
Prod
```
vault.developer.gov.bc.ca
one.vault.developer.gov.bc.ca (Silver)
two.vault.developer.gov.bc.ca (ARO - PS)
```
Lab
```
vault-lab.developer.gov.bc.ca
one.vault-lab.developer.gov.bc.ca (CLAB/Thetis)
two.vault-lab.developer.gov.bc.ca (KLAB)
```

**Definition of Done**
- [x] DNS Entries Requested
- [x] DNS Entries Set (Steven)
- [x] SSL Certs Requested
- [x] SSL Certs Received

**Comment by manderson-it** [comment]
- Suggested FQDNs were accepted by Justin Pye, Jeff Kelly, Marek Anderson
- Justin Pye moving ahead to file DNS name requests

**Comment by manderson-it** [comment]
- @j-pye has a meeting on Monday, Jul 27 about the certificate requests

**Comment by j-pye** [comment]
iStore orders have been submitted requesting a cert for the lab and prod.

Prod
```
vault.developer.gov.bc.ca
one.vault.developer.gov.bc.ca
two.vault.developer.gov.bc.ca
```
Lab
```
vault-lab.developer.gov.bc.ca
one.vault-lab.developer.gov.bc.ca
two.vault-lab.developer.gov.bc.ca
```

**Comment by j-pye** [comment]
Still waiting on SSL certs.
iStore order is being processed. CSRs have been provided for both vault and vault-lab certificates.

**Comment by j-pye** [comment]
SSL Certs received for Vault and Vault-Lab.

**Comment by StevenBarre** [comment]
DNS records created

| Name                              | Type | Data           |
|-----------------------------------|------|----------------|
| one.vault-lab.developer.gov.bc.ca | A    | 142.34.151.118 |
| two.vault-lab.developer.gov.bc.ca | A    | 142.34.50.62   |
| one.vault.developer.gov.bc.ca     | A    | 142.34.194.118 |
| two.vault.developer.gov.bc.ca     | A    | 40.82.162.100  |
