### ISSUE TITLE
Design Structure within Vault

### ISSUE THREAD

**Issue by manderson-it** [BCDevOps/OpenShift4-RollOut#284]
Namespaces and Mount Points are Vaults within Vault and are meant for consumption by applications/app-teams with strong isolation between them.
This design will outline the structure of these namespaces and Mount Points and potential structure/naming conventions, e.g., dev, qa, and prod.

Definition of done:
- [X] Design structure documented
- [x] Peer-reviewed

**Comment by manderson-it** [comment]
- @j-pye and I have a session scheduled on Thu Jul 30

**Comment by tosazuwa** [comment]
Timeboxed for full sprint

**Comment by manderson-it** [comment]
Nick, Justin, Jeff, and I discussed the structure within Vault today. Getting closer to the finish line.

**Comment by manderson-it** [comment]
@j-pye can you peer-review [structue-within-vault.md](https://github.com/BCDevOps/platform-services/blob/feature/hc-vault/security/vault/docs/structure-within-vault.md) please?

**Comment by j-pye** [comment]
@manderson-it The doc looks good to me. My only note would be that the random 5 char string for the `AppName` could be replaced with the App license plate. It's essentially the same thing but it's one less thing to update if we decide to change the license plate length.

**Comment by j-pye** [comment]
Docs look good. No extra notes at this time.

**Comment by manderson-it** [comment]
Final review with @j-pye completed.
