### ISSUE TITLE
Plat-Image Jenkins

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#286]
Problem: Platform managed Jenkins image needs to have an automated build/deployment pipeline created.

DoD:
- [ ] Jenkins image(s) built on a regular basis in a Lab environment
- [ ] Jenkins image(s) pipeline deploy/test through lab->azure->silver->gold clusters

**Comment by lukegonis** [comment]
Jenkins comes with the platform and works as expected
