### ISSUE TITLE
Plat-Image patroni

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#287]
Problem: Platform managed patroni image needs to have an automated build/deployment pipeline created.

DoD:
- [ ] patroni image(s) built on a regular basis in a Lab environment
- [ ] patroni image(s) pipeline deploy/test through lab->azure->silver->gold clusters

**Comment by jleach** [comment]
Patroni is done. When we create new clusters we just need to make sure we import all our images.

**Comment by jefkel** [comment]
Is there a link to a flow document that describes the automatic build schedule and the automated image promotion between clusters?

**Comment by jleach** [comment]
I posted a video of the solution to the image management discussion for feedback before I do any docs. So far crickets.
