### ISSUE TITLE
Plat-image caddy

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#288]
Problem: Platform managed caddy image needs to have an automated build/deployment pipeline created.

DoD:
- [ ] caddy image(s) built on a regular basis in a Lab environment
- [ ] caddy image(s) pipeline deploy/test through lab->azure->silver->gold clusters

**Comment by jleach** [comment]
Still thinking about this one. I have S2I version working with Caddy / Node but I'm not sure including node is a good thing. I'm tending to think it should just be an S2I for Caddy and teams can chain in Node / Python / Bla as needed.

**Comment by mitovskaol** [comment]
@jleach Where did your thinking about this lead you ?

**Comment by jleach** [comment]
I’d close it. We don’t offer Casddy as an image and I’m would prefer not to offer more. Also, In this specific case a chained build is the right way to go.

Regards,

Jason Leach
