### ISSUE TITLE
CLAB Networking issues | SPIKE

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#291]
**Describe the issue**
The most consistent thing I've seen is API Request Success Rate on the overview screen will randomly drop and show no data. The console itself has been inaccessible but sometimes works if you refresh a couple of times. Connections between pods occasionally time out.

On both pods and cluster Events pages.
I see messages in red that say Error connecting ... Connection didn't close properly That's not exact, it started working again before I could copy it.

Application is not available seems to be common among anything I'm trying to access with a route. Sometimes a refresh resolves it and other times I just get a white screen.

Getting to the copy login command page results in. (The following image) A refresh fixed it but now I'm trying to get the Deploy Token link to work.

**Definition of done Checklist (where applicable)**
Cluster networking is stable again

**Comment by StevenBarre** [comment]
Opened a case with RH for "OCP4: Prometheus metrics scraping issues" which seems to have solved itself, all Prom targets are now up.

Opened a case with RH for "OCP4: errors in etcd-operator" as there are events and errors in the logs of that operator indicating connection issues to the etcd pods.

Opened a case with RH for "OCP4: clusteroperator/authentication degraded" as there are events and errors in the log of that operator indicating trouble getting the route object.

**Comment by StevenBarre** [comment]
Attempting an upgrade to 4.4.11 to see if that resolves anything

**Comment by StevenBarre** [comment]
Upgrade did not solve the issues. Seeing 503 errors in browser console when using webgui. Uploaded a must-gather to one of the Red Hat cases Friday evening.

Opened a case with PANW 01526415 about seeing Dropped packets in `apoclt stats query packets` but the enforcers are still in Discovery Mode.

**Comment by StevenBarre** [comment]
Worked with Red Hat and @j-pye to troubleshoot. At one point Justin adjusted Aporeto host protection policy to handle the kubelet and a lot of the errors seemed to go away. Monitoring for now as Justin finishes up Aporeto testing.

**Comment by tosazuwa** [comment]
@j-pye , please add a summary of outcomes and conclusions from the fix if it has been resolved

**Comment by j-pye** [comment]
This appears to be resolved.
Root cause is still unknown but pointed towards a policy issue between Kubelet(s) and Pods. 
After adding the Kubelet Egress policy many of the networking issues went away. Remaining issues were solved by a restart of the SDN pod on impacted nodes.

Note: Aporeto's Discovery mode should not be used at the cluster namespace level as it does not appear to reliably allow any:any connections.
