### ISSUE TITLE
Deploy Artifactory to clab

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#292]
**Describe the issue**
Deploy Artifactory and Artifactory Operator to clab Cluster

**Which Sprint Goal is this issue related to?**

**Done**

- [ ] Artifactory is deployed and functional (without image repository certificates)
- [ ] Operator is managing repo and service account creation
- [ ] Caching repos have been verified (dockerhub and redhat image registry specifically)

• All tests passed (specify what kind of testing is done)
• Design / Solution accepted by Product Owner
• Test coverage acceptable (LAB & PROD)
• Peer Reviewed

**Comment by jefkel** [comment]
Deployment has begun, but ran into an issue with Patroni image builds not building appropriated (tied to current issue Clecio is experiencing).

Started SPIKE to investigate whether deploying via Patroni based Postgresql-Operator would be an appropriate direction.

If not, then will resume troubleshooting patroni build issue.

**Comment by caggles** [comment]
@jefkel are we actually planning to do this or should i just close it because we're deploying straight into klab?

**Comment by jefkel** [comment]
Artifactory will need to be deployed to both (in order to start testing site replication), but for troubleshooting purposes while we work through Artifactory 7 issues, it would make sense to focus on klab for now (and put the updates in that ticket.).  This ticket should NOT be closed, but can be put back in the backlog.

**Comment by mitovskaol** [comment]
I think it has been complete.
