### ISSUE TITLE
Deploy Artifactory to klab

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#295]
**Describe the issue**
Deploy Artifactory and Artifactory Operator to klab Cluster

**Which Sprint Goal is this issue related to?**

**Additional context**
Add any other context, attachments or screenshots

**Definition of done Checklist (where applicable)**
- [x] Artifactory service deployed and configured
  - [x] remote docker registries (caching) configured (basic usage documented)
  - [x] other remote registries (caching) configured (maven, etc?)
  - [x] default security groups updated
- [x] Operator deployed and functionally validated

• All tests passed (specify what kind of testing is done)
- [ ] Artifactory service account provisioning tested
- [ ] Artifactory repository creation/access tested (docker, npm, maven, other?)
- [ ] Docker pull through caching tested (redhat, docker.io, etc?)

• Design / Solution accepted by Product Owner
• Test coverage acceptable (LAB & PROD)
• Peer Reviewed

**Comment by jefkel** [comment]
@caggles Focus for artifactory on OCP 4 troubleshooting:
- differences in the scripted commands for the statefulSet initContainers (between the new manifests and the old version).
- differences in the securityContext settings to bring the "run as a random UID" forward from the old version.

**Comment by caggles** [comment]
Artifactory is now running in KLAB, but requires some finesse to actually get it working.

Still to do:

- [x] clean up the helm manifest to use proper actual variables
- [x] clean up the installation playbook to rollback and stuff
- [x] figure out what the _heck_ is up with the fact that the installation works but only after you kill the pod 5 times?!?!?
- [x] install operator on klab
