### ISSUE TITLE
F5 Virtual Edition License

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#296]
**Description**
We are currently using the free LAB license for the F5 Virtual Editions used in KLAB and eventually CLAB. The LAB license has a 10Mbps limit on all traffic.  Previously this wasn't an issue as only the API and Apps traffic was traversing the F5, both of which are fairly low bandwidth. Now that all traffic to the nodes is NAT'ed via the F5 the limit is much more impact-full.

**DoD**:
- [x] Install a trial license without bandwidth limits
- [x] Record network usage during build/upgrade operations tasks
- [x] Create a recommendation for license purchase
- [x] Approved/procured and applied

**Comment by StevenBarre** [comment]
Started discussions with F5 and DXC about options for a license. F5 has provided a 30 day eval.

**Comment by jefkel** [comment]
(Pulled extra detail from description)

Download speed of a 100MB file in Calgary DMZ
![pic2.jpg](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/be81b982-1f18-4f8a-abb9-9d7bfd7276a7)

Download speed of a 100MB file in KLAB SDN
![pic1.jpg](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/3ccc0360-2e62-4a89-853b-76cf08d34a61)

As building a new node or doing an OCP upgrade includes 2-3GB of container images per node, this can cause quite a hindrance. 3GB at these speeds is 40+ minutes.

**Comment by StevenBarre** [comment]
![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/e4809a7f-6ad4-4e2b-b136-1c2aa618a987)
![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/747f1f30-1d8b-4876-8de6-da9106d41f37)

Attempting to start the Trident pods is erroring out due to the slow network.

**Comment by StevenBarre** [comment]
Upgrade from 4.3.0 to 4.3.28 with the Eval license (good till Aug 17th)

![pic3.jpg](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/c07b3107-82e9-4d0e-9d38-d2147869bdae)

License sizes available are 200M, 1G, 3G, 5G and 10GB. We've requested quotes for 200M and 1G.

**Comment by StevenBarre** [comment]
Set throttling on the F5 to 200M and ran an upgrade. It only throttled at a few spots. Appears the Red Hat Registry caps out around 100M for any individual TCP stream and so only a few spots were multiple nodes pulling DaemonSet images or CoreOS images at the same time.

```
# oc get clusterversion -o json|jq ".items[0].status.history"
[
  {
    "completionTime": "2020-07-27T17:55:36Z",
    "image": "quay.io/openshift-release-dev/ocp-release@sha256:1b15aef0cf352b49be0b22f273663719dfdc111737e58a9080595623e47d7dd8",
    "startedTime": "2020-07-27T17:01:33Z",
    "state": "Completed",
    "verified": true,
    "version": "4.4.13"
  },
```

**Comment by Joe-Craig** [comment]
Brief Note written for additional licenses
David Ell/ Olena approved the BN on 25th Aug.
Waiting for approval to arrive so we can produce a SCO.

**Comment by Joe-Craig** [comment]
SCO pricing done.
SCO being written by contracts department.

**Comment by Joe-Craig** [comment]
SCO has been signed off and procurement process started - ETA before 12th Oct when the temporary licenses run out.
