### ISSUE TITLE
Set roadmap milestones

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/OpenShift4-RollOut#3]
**December 1 - Release 1**
-OCP 4.2 Labs stood up in Calgary and Kamloops DMZ
-Includes NetApp storage, DNS, F5
-Production cluster running in DMZ

**January 2 - Release 2**
-Operational tools (Aporeto, Sysdig etc) deployed to all clusters

**January 15 - Release 3**
-Redeploy of OCP Lab Clusters with version 4.3
-Prod redeployed to 4.3 as well

**January 31 - Release 4**
-Labs redeployed to Cloud Zone, including F5, storage, networks
-Prod redeployed to cloud zone

**February 28 - Release 5**
-Operationalize production
-Application/team migrations begin

**Comment by tosazuwa** [comment]
![image.png](https://images.zenhubusercontent.com/5d547d685cc9f75541f33187/efde97bc-b6ad-4ac5-be79-3b08c609d75f)

**Comment by sheaphillips** [comment]
I'd like to discuss the roadmap and where it came from - there are more releases than previously discussed. I think it would make sense to capture the roadmap using the roadmap feature in ZenHub.  We already have "releases" defined, so it's really a matter of replicating those over into the roadmap (I believe "projects" is the equivalent construct on the roadmap side)

**Comment by tosazuwa** [comment]
![OPC 4 Roadmap.PNG](https://images.zenhubusercontent.com/5d547d685cc9f75541f33187/d2e91908-3eb0-408a-84a8-466344f4f5f3)
