### ISSUE TITLE
INC0038813 Trident creating corrupted volumes

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#301]
**Describe the issue**
Sometimes, newly created block volumes fail to mount and never recover.

**Definition of done Checklist (where applicable)**
- [x] Jeff is able to deploy patroni statefulsets with new storage reliably

**Comment by StevenBarre** [comment]
Opened a case with NetApp.

Appears that sometimes new volumes are detected as being already formatted and so the code doesn't format them. But they are not validly formatted and thus can't be mounted.

```
time="2020-07-20T20:27:06Z" level=debug msg="LUN already formatted." fstype=xfs volume=block_standard_pvc_ba0296af_c113_4ed0_89c3_60dbc3412ffa
time="2020-07-20T20:27:06Z" level=debug msg="<<<< osutils.execCommand." command=mount error="exit status 32" output="mount: /var/lib/kubelet/pods/acd013b9-b25c-40b1-9595-763e7450849f/volumes/kubernetes.io~csi/pvc-ba0296af-c113-4ed0-89c3-60dbc3412ffa/mount: wrong fs type, bad option, bad superblock on /dev/mapper/3600a09805a5065762d5d4f742f6d6b78, missing codepage or helper program, or other error."
```

```
# blkid /dev/mapper/3600a09805a5065762d5d4f742f6d6b78
/dev/mapper/3600a09805a5065762d5d4f742f6d6b78: UUID="bf3636ea-43b2-49ca-97d6-12dea2fe77                        e8" TYPE="xfs"
# xfs_info /dev/mapper/3600a09805a5065762d5d4f742f6d6b78
Metadata CRC error detected at 0x563048ba0c62, xfs_agf block 0x8/0x1000
xfs_info: cannot init perag data (74). Continuing anyway.
meta-data=/dev/mapper/3600a09805a5065762d5d4f742f6d6b78 isize=512    agcount=4, agsize=                        65536 blks
         =                       sectsz=4096  attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=1
data     =                       bsize=4096   blocks=262144, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=2560, version=2
         =                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
```

**Comment by StevenBarre** [comment]
Some more testing has shown that the volumes are failing to unmount when the pod is deleted.

```
3600a09805a5065764a2b4f7331435652 dm-1 ##,##
size=1.5G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=0 status=enabled
| `- #:#:#:# sdc 8:32 failed faulty running
`-+- policy='service-time 0' prio=0 status=enabled
  `- #:#:#:# sdd 8:48 failed faulty running
``

Sent more logs and details to NetApp

Reproduced on KLAB.

**Comment by StevenBarre** [comment]
This appears to be a race condition. If you scale down without deleting the PVCs then they clean up fine. Only if you delete the PVC first, or on the same command line as the scaledown does it fail.

Provided this info to NetApp and opened a case with Red Hat to see if they have any insights. Though they do mention "With CSI, all of that code around mount / unmount etc.. that was in k8s is now owned aspart of trident via their CSI implementation."

**Comment by StevenBarre** [comment]
NetApp believes this will be fixed in their September release when they move to the v1.19 CSI container sidecar.

**Comment by StevenBarre** [comment]
Poked NetApp for a ETA.

**Comment by StevenBarre** [comment]
NetApp says

> As far as I am aware, the patch is expected to be available possibly by end of next week or soon thereafter.
As soon as it is available, I will let you know

**Comment by StevenBarre** [comment]
https://github.com/NetApp/trident/releases/tag/v20.07.1

**Comment by StevenBarre** [comment]
KLAB upgraded and some tests run https://github.com/bcgov-c/platform-ops/pull/296

Passing to @jefkel to verify before closing

**Comment by jefkel** [comment]
I have not been able to replicate the issue in klab (with multiple deploy/destroy cycles of 3 separate patroni clusters.)

Looks good to me.
