### ISSUE TITLE
Aporeto installation on SILVER

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#304]
**Describe the issue**
Aporeto is required to be installed on SILVER with all enforcement policies verified. 

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [ ] Aporeto installed
- [ ] Aporeto Operator installed
- [ ] All tests passed (specify what kind of testing is done) *Detail to be added for tests/validation required*

**Comment by StevenBarre** [comment]
@j-pye I think this can be closed?

**Comment by jleach** [comment]
Closing. Aporeto was installed and is now removed. This ticket is no longer needed.
