### ISSUE TITLE
Installation of Aporeto on CLAB

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#305]
**Describe the issue**
Aporeto is required to be installed on CLAB with all enforcement policies verified. 

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] Aporeto installed
- [x] Aporeto Operator installed
- [x] All tests passed (specify what kind of testing is done) *Detail to be added for tests/validation required*

**Comment by j-pye** [comment]
CLAB is currently out of commission as it moves to the SDN Compartment

**Comment by j-pye** [comment]
This is waiting on CLAB availability which is waiting on CCM to be ready.

Edit:
- OIDC Cluster Auth needs to be setup
- CCM Needs to be setup for CLAB so that aporeto can be installed.

**Comment by j-pye** [comment]
Closing. Aporeto install but only until complete removal.
