### ISSUE TITLE
Deploy lab Vault service

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#307]
**Describe the issue**
A lab deployment of the vault service

**Which Sprint Goal is this issue related to?**
Deploy lab Vault service

**Additional context**

**Definition of done Checklist (where applicable)**
Functional deployment of the vault service.

**Comment by manderson-it** [comment]
- Two working sessions scheduled and confirmed for Thursday, July 30 with @j-pye

**Comment by manderson-it** [comment]
- One working session scheduled but unconfirmed for Friday, July 31 with @j-pye and @jefkel

**Comment by manderson-it** [comment]
Pending approval by @NickCorcoran for the MVP stage. Send out an invite for Friday 21st.

**Comment by manderson-it** [comment]
After discussing the structure within Vault with @NickCorcoran, @j-pye and I deployed the MVP on the thetis cluster, including auto unseal with Azure Key Vault. It is an exciting first step on this journey. Thanks, everyone, for all your support! Once the FQDNs resolve and we get the TLS certificates, we will make the next steps.

**Comment by manderson-it** [comment]
DNS entries are created (see closed ticket [279](https://app.zenhub.com/workspace/o/bcdevops/openshift4-rollout/issues/279)).
TLS certificates received. Need to be implemented on appropriate OCP routes.
