### ISSUE TITLE
Create StorageMigration tool (migrate between clusters)

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#308]
**Describe the issue**
Extend the existing https://github.com/bcdevops/StorageMigration tool for a cross cluster data copy.

**Definition of done Checklist (where applicable)**
- [ ] Update the image and a deployment manifest to add in:
 - Remote cluster secret (should include namespace, service account and pod label to connect to)
 - deployment for each cluster (ocp 3 and ocp 4)
- [ ] Updated operational process documentation
  - first ops process is for copying a DB backup location (OCP3) to a DB backup location (OCP4)
  - Add automation as stretch

**Comment by arendej** [comment]
https://github.com/BCDevOps/StorageMigration/pull/53 is in for initial push.
Continuing to iterate.

**Comment by mitovskaol** [comment]
@funixz What is the status of this work? Has the MVP been released yet? If so, I will close the ticket.

**Comment by jefkel** [comment]
Sorry @mitovskaol , I'm reviewing and validating instructions, and aim to release this week.

**Comment by mitovskaol** [comment]
MTC has been successfully installed and use to migrate multiple projects from OCP 3 to OCP 4
