### ISSUE TITLE
Rename routes for default cluster services

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#309]
**Describe the issue**
Default cluster service names (routes) could be more friendly (current naming convention is service-namespace.apps.{cluster}.devops.gov.bc.ca).  

The following names may need updating:
Developer facing:
`console-openshift-console.apps.{cluster}.devops.gov.bc.ca` - OpenShift web UI
`downloads-openshift-console.apps.{cluster}.devops.gov.bc.ca` - OpenShift CLI tool downloads
`kibana-openshift-logging.apps.{cluster}.devops.gov.bc.ca` - OpenShift log visualization tool

OPS facing (rename is not required, but may be wanted? - DXC input requested)
`alertmanager-main-openshift-monitoring.apps.{cluster}.devops.gov.bc.ca` - OpenShift alertmanager tool (Ops only?)
`grafana-openshift-monitoring.apps.{cluster}.devops.gov.bc.ca` - OpenShift graphana (Ops Team only?)
`prometheus-k8s-openshift-monitoring.apps.{cluster}.devops.gov.bc.ca` - Prometheus data query interface (Ops Team only)
`thanos-querier-openshift-monitoring.apps.{cluster}.devops.gov.bc.ca` - Long term Prometheus data query interface (Ops Team only)

**Definition of done Checklist (where applicable)**
- [x] **Rename:** *console-openshift-console.apps.{cluster}.devops.gov.bc.ca* to `console.apps.{cluster}.devops.gov.bc.ca`
- [ ] New endpoint URL names for Developer facing services are defined
  - [ ] OPTIONAL: new endpoint URL names for OPS facing services defined
- [ ] Cluster build automation configures names for each of the services defined above.

**Comment by StevenBarre** [comment]
I'm not sure this is possible looking at the docs. I've opened a case with Red Hat to ask about it.

**Comment by StevenBarre** [comment]
> You can chnage the console URL with OCP 4.5, but the docs are not done yet.
> 
> If you look at the spec, you can see the new settings:
> oc explain console.spec.route --api-version=operator.openshift.io/v1
> 
> For example, you could:
> 
> oc patch consoles.operator.openshift.io cluster --patch '{"spec":{"route":{"hostname":"console.example.com}}}' --type=merge
> 
> For the rest of the components, there is an RFE: https://issues.redhat.com/browse/RFE-718
> 
> I'll add this case to the RFE list of customers

**Comment by StevenBarre** [comment]
The console route has been added (the old one remains as well). The rest are not currently possible to change.

**Comment by StevenBarre** [comment]
Moving to Blocked waiting on future feature updates to complete.

**Comment by lukegonis** [comment]
closing this issue without updating the CLI download tools URL because it is not currently a supported configuration option for the openshift operator
