### ISSUE TITLE
Create Migration related documentation hub

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#312]
**Describe the issue**
public hub of migration related documentation and links to external sources to be published via devhub

**Which Sprint Goal is this issue related to?**

**Additional context**
*Updates needed*

**Definition of done Checklist (where applicable)**
*Updates needed*

**Comment by jefkel** [comment]
started in https://github.com/BCDevOps/openshift-wiki/pull/58

**Comment by mitovskaol** [comment]
The information hub for OCP 4 migration has been created in the OCP 4 Migration Repo where we also leverage the GitHub Issues to capture problems and their solutions in the Q&A format.

https://github.com/BCDevOps/OpenShift4-Migration
