### ISSUE TITLE
Enable ETCD Encryption in OCP 4

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/OpenShift4-RollOut#315]
ETCD Encryption is available in OCP 4 and is recommended to be enabled in all OCP 4 production clusters (Silver, Gold, Gold DR and ARO). This feature has been dicussed between Shea, Steven, Nick and Olena on Aug 10 and the decision has been made to enable it in OCP 4 Platform.

It is to be determined if this feature have to be enabled manually or will be added to cluster configuration management playbooks.

Historical context for this ticket that was previously opened in Platform Experience board:
https://trello.com/c/L9X7N0Cy/112-etcd-encryption
https://docs.openshift.com/container-platform/4.4/security/encrypting-etcd.html
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/299

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-ops/pull/290
