### ISSUE TITLE
Move Backup Storageclass  Readme from #155 into DevHub

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#317]
The backup storage class exists with a readme file. This file needs to be transferred into the devhub and developer friendly content. 

**Definition of Done** 
Documentation exists at developer.gov.bc.ca that developers can use to obtain their own backup storage volume / storage class.

**Comment by StevenBarre** [comment]
Current doc location https://github.com/bcgov-c/platform-ops/blob/ocp4-base/ocp4/docs/Backup.md

**Comment by StevenBarre** [comment]
https://github.com/BCDevOps/openshift-wiki/pull/60

**Comment by StevenBarre** [comment]
Blocked while Patrick fixes up the DevHub content contribution system.

**Comment by StevenBarre** [comment]
Done! https://developer.gov.bc.ca/OCP4-Backup-and-Restore
