### ISSUE TITLE
Vault Disaster Replication Traffic Flow

### ISSUE THREAD

**Issue by manderson-it** [BCDevOps/OpenShift4-RollOut#318]
**Describe the issue**
Establish whether Vault cross-cluster disaster recovery replication traffic can flow through an OpenShift route (Layer 7) versus a TCP (Layer 4) load balancer.

**Which Sprint Goal is this issue related to?**
This relates to the epic Vault on OCP4.

**Additional context**
Details shared with the vendor.

**Definition of done Checklist (where applicable)**
• Get definitive answer on the OCP route feasibility
• Evaluate TCP load balancer as alternative traffic flow (Alternative to OCP route)
• Verify the Disaster Recovery traffic flows between the two Vault sites
• Peer Reviewed

**Comment by manderson-it** [comment]
I sent an email with a supporting diagram to the vendor describing the current traffic flow design.

**Comment by manderson-it** [comment]
Waiting on the final answer from the vendor.

**Comment by manderson-it** [comment]
Sent out another email to the vendor today.
We are currently blocked here.

**Comment by manderson-it** [comment]
Blocked.
Have not received a final answer from the vendor yet.
Will re-evaluate the TCP load balancer as an alternative traffic flow (Alternative to OCP route).

**Comment by manderson-it** [comment]
Meeting with @jefkel @sbarre-esit @pfischer8989 on Sep 10 about F5 upcoming ingress options.
The issue with F5 is here https://github.com/F5Networks/k8s-bigip-ctlr/issues/1443
Timeline unknown. One due date shows Oct 21 though.
Also, there is an Enterprise Architecture Team assigned at HashiCorp to resolve this.

**Comment by manderson-it** [comment]
Two sessions with HashiCorp engineers/architects Sam Gabrail and James Anderton. The issue remains unresolved.

**Comment by mdditt2000** [comment]
@manderson-it i can provide a CIS image later this week for F5Networks/k8s-bigip-ctlr#1443

**Comment by manderson-it** [comment]
Also opened tickets with HashiCorp support today https://support.hashicorp.com/hc/en-us/requests/35007
and https://support.hashicorp.com/hc/en-us/requests/35008
@j-pye has access to the HashiCorp support portal.

**Comment by j-pye** [comment]
This ticket will remain open until Gold and GoldDR are available with F5 CIS support for Cross Cluster Communication to support Vault's DR replication.

**Comment by michaelshire** [comment]
@j-pye  Had conversations with Marek on this topic before he left.  From my understanding, we should be able to use a Route with "TLS with SNI".  I have it generally documented.  I've used this pattern before to expose native Kafka ports (non HTTPS, but still TLS traffic).  If we have time tomorrow I can show you.

Is there a non-production environment where we could test out this solution?

**Comment by j-pye** [comment]
@michaelshire we have two lab cluster, KLAB and CLAB which are located in Kamloops and Calgary respectively. 
We have domains and certs for both Lab installations (Primary and Secondary (DR) sites)

Happy to discuss the SNI approach. And if you have any info or docs you can share then I can look over those before we meet.

**Comment by j-pye** [comment]
Closing as this appears to be working as expected now in both directions with the F5 CIS operator allowing for TCP traffic between the two clusters.
