### ISSUE TITLE
OCP 4 iStore orders (pending)

### ISSUE THREAD

**Issue by tosazuwa** [BCDevOps/OpenShift4-RollOut#319]
iStore orders submitted by Olena - Aug 18, 2020

- [x] `*apps.silver.devops.gov.bc.ca` (Critical) 
- [x] `*.apps.klab.devops.gov.bc.ca` (Critical)
- [x] `*.apps.clab.devops.gov.bc.ca` (Normal)
- [x] `*.apps.gold.devops.gov.bc.ca` (Normal)
- [x] `api.silver.devops.gov.bc.ca` (Critical)
- [x] `api.klab.devops.gov.bc.ca` (Critical)
- [x] `api.clab.devops.gov.bc.ca` (Normal)
- [x] `api.gold.devops.gov.bc.ca` (Normal)

**Comment by StevenBarre** [comment]
Followed up with CITZ Service Desk on status of `*.apps.clab.devops.gov.bc.ca` and found out it needs to be re-entered with correct Expense Authority.

**Comment by StevenBarre** [comment]
Got the last one. Closing.
