### ISSUE TITLE
Auto Unseal with Azure Key Vault

### ISSUE THREAD

**Issue by manderson-it** [BCDevOps/OpenShift4-RollOut#323]
**Describe the issue**
Deploy Azure Key Vault for each Vault cluster.

**Which Sprint Goal is this issue related to?**
Related to the epic Vault MVP on OCP4

**Additional context**
The Azure Key Vault allows each Vault pod to be automatically unsealed and therefore eliminate the manual unseal process per pod.
An unseal operation is mandatory when a pod starts for the first time and on any pod restart scenario be it maintenance or failure.

**Definition of done Checklist (where applicable)**
• Vault LAB deployment is verified to be auto-unsealed with Azure Key Vault
• Vault PROD deployment is verified to be auto-unsealed with Azure Key Vault
• Peer-Reviewed

**Comment by manderson-it** [comment]
Keeping track of different tasks on a more granular level with this.
@stewartshea already began the work with the appropriate teams in the previous sprint.

**Comment by stewartshea** [comment]
@manderson-it  I've worked with the cloud pathfinder team and now have a key vault provisioned for the lab. We can sync up on the sensitive details in a private meeting. 

![image](https://user-images.githubusercontent.com/18314168/90802195-df992d00-e2e4-11ea-9b41-c30fbb6f881e.png)

**Comment by manderson-it** [comment]
I can confirm that the provided Azure Key Vault is functional to auto unseal HashiCorp Vault.
Next step: Test the Azure Key Vault with the initial lab deployment of Vault.

**Comment by manderson-it** [comment]
The first part of the Definition of Done has been achieved. Justin and I did a screen share session for this.
- [X]  Vault LAB deployment is verified to be auto-unsealed with Azure Key Vault

**Comment by manderson-it** [comment]
The other two Azure Key Vaults are captured in a separate issue #405.
This one is tested and done. Closing.
