### ISSUE TITLE
Vault Backup solution

### ISSUE THREAD

**Issue by manderson-it** [BCDevOps/OpenShift4-RollOut#325]
**Describe the issue**
The Vault backup mechanism needs to be established and verified end-to-end.

**Which Sprint Goal is this issue related to?**
Related to epic Vault MVP on OCP4.

**Additional context**
@j-pye mentioned the pattern is to write the backed up data to an NFS endpoint.

**Definition of done Checklist (where applicable)**
- [ ] Backup solution documented
- [x] Backup verified to arrive in NFS / final storage endpoint
- [ ] Peer-Reviewed

**Comment by manderson-it** [comment]
Send the CronJob definition to @j-pye. Justin will look into the NFS / final storage endpoint piece.

**Comment by manderson-it** [comment]
@j-pye can you finish this before the end of Sprint? Happy to help.

**Comment by j-pye** [comment]
Vault Backup Install role updated. We'll likely need to make some minor changes in the future. CLAB/Thetis is currently down so I was unable to test with our current Lab deployment but I did test in a local k8s cluster.

Doc updates to come.

**Comment by manderson-it** [comment]
Update the Kubernetes CronJob to use a sidecar with Vault's Kubernetes Authentication Method. Update docs accordingly.

**Comment by manderson-it** [comment]
Work will continue once @j-pye is back on Monday Oct 26th.

**Comment by j-pye** [comment]
Explore Vault 1.6.0 new backup method and evaluate whether we can continue with our current solution or should switch to the new method.

**Comment by manderson-it** [comment]
@j-pye This is complete. Reopen if you feel otherwise.
