### ISSUE TITLE
Create detailed architecture for Kamloops Prod

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#33]
Current documentation is for an MVP deployment of the production migration target.

With changes to the procurement timelines, adjustments need to be made to the MVP architecture.

**Comment by jefkel** [comment]
Initial Architecture complete, updates expected as we build and make additional decisions.
Closed.

**Comment by jefkel** [comment]
Updated architecture to reflect changes in app node count and NetApp physical appliance decision.

**Comment by jefkel** [comment]
Update documentation with additional kamloops cluster
Breaking Prod cluster into Tools-Dev-Test cluster and Prod cluster.

**Comment by mitovskaol** [comment]
@jefkel Can you please update the BCGov OCP4 Cluster Worksheets spreadsheet with the new 8 nodes that we have ordered recently so that we know whether they will be used for the Silver cluster and/or Gold.

**Comment by jefkel** [comment]
@mitovskaol I was not involved in the direct planning for those hosts when they were ordered, but I would recommend that they are included in the Silver cluster to bump up the capacity for that cluster.  The initial migration will not include any Gold cluster project targets, so we can minimize the App Node hardware in the Gold cluster until the migration is well underway.

I have created ticket #253 to track this request, and would like to defer to DXC to keep the documentation up to date with the new hardware (Dell host info) and physical mix between the clusters based on the last known capacity management plans.

**Comment by mitovskaol** [comment]
@sbarre-esit Can you please update the spreadsheet with the details of the new 8 nodes. Thanks!

**Comment by jefkel** [comment]
Closing this as the initial architecture work is complete, and further updates to the documentation will be covered in their own tasks.

Archiving the individual cluster documents in favor of a broader platform architecture document.  Individual cluster details will be found within this 1 document, or within additional tracking documentation.

Platform Architecture document:
https://docs.google.com/document/d/1U7OGhR1lCpxASZFfoZwPLSJJyU23W25lX1p5PRldcnA/edit?usp=sharing

Current cluster build tracking (for host detail):
https://docs.google.com/spreadsheets/d/1cOJu-_y8MmVixJGBVk4lbfmfyV2rQfU0U1M1PWccmkQ/edit?usp=sharing
