### ISSUE TITLE
Upgrade Artifactory Operator base image

### ISSUE THREAD

**Issue by caggles** [BCDevOps/OpenShift4-RollOut#342]
Upgrade the base image for the artifactory operator, build, deploy and test to make sure it all works as expected in OCP4.
Also add the docker cert to the operator.

**Comment by jefkel** [comment]
Failed deployment issue narrowed down to klab netapp-file-standard issue (unable to replicate on other clusters, or with netapp-block-standard).

Additional testing to isolate the storageClass issue to be completed
Afan (Arctiq) will validate installation/testing for Cailey and provide feedback for improvements/fixes.

**Comment by caggles** [comment]
I have the operator successfully updated to v0.19 - v1.0.0 upcoming!

**Comment by caggles** [comment]
We're going to name operator groups like this:

[product].devops.gov.bc.ca
do not pick shortnames that overlap with existing openshift objects.

**Comment by caggles** [comment]
Still to do: add docker cert to the operator.
