### ISSUE TITLE
Develop Plan to integrate Artifactory and Project Provisioner

### ISSUE THREAD

**Issue by caggles** [BCDevOps/OpenShift4-RollOut#345]
It's likely that artifactory will need to be integrated into the project provisioner (likely this will involve creating an artifactory service account as part of project creation, with basic access that allows the project team to pull from artifactory's caching repos).

- [x] provision artifactory service account and configure default registry credentials for artifactory in each namespace for a project set

We will be leveraging the custom Artifactory Operator to provision an Artifactory service account in each new namespace (via project-provisioner).
Required items to provision:
- [ ] naming convention for auto-provisioned service accounts
- [ ] CRD created in each namespace with appropriate name (above)

**Comment by jefkel** [comment]
Blocked pending working Artifactory deployment and Artifactory operator.

**Comment by jefkel** [comment]
decision complete to use existing operator functionality, and provision new namespaces with an appropriate customResource.
