### ISSUE TITLE
Design a process for project quota increase in OCP 4

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/OpenShift4-RollOut#347]
In the new Openshift 4 Platform all new namespaces will be provisioned with the small size default quota that includes a certain amounts of each of the 3 resource categories CPU/RAM/Storage as defined here

https://app.zenhub.com/workspaces/openshift-4-build-out-5db73142897668000144f22b/issues/bcdevops/openshift4-rollout/254

DOD:
- [x] Document a process product teams would need to follow to request a quota increase in the OCP 4 Platform

Decision:
- **We currently do not support quota increases for a specific resource (i.e. just RAM, or just CPU, or just Storage) or for a specific namespace (i.e. prod only).** Teams requiring more resources in **any of the 3 resource categories** such as CPU/RAM/Storage **in any of the 4 namespaces** (dev, test, tool or prod), will have to submit a standard quota increase request through the Project Registry. 
Once approved (see the approval process below),  **all 4 namespaces in a project set** will be upgraded to the next quota size which includes a double amount of resources in  **all 3 categories**. 
 
Example: If your prod namespace needs more storage and you request a standard quota increase from small to medium, the resource allocations for all 4 of your namespaces will be upgraded to the medium size quota as per [the OCP 4 quota definitions](https://app.zenhub.com/workspaces/openshift-4-build-out-5db73142897668000144f22b/issues/bcdevops/openshift4-rollout/254)

- The upgrade path will only be available **in this order**: from small -> medium -> large. You cannot skip medium and upgrade from small to large.

-  Quota increase approval process
 When requesting a quota increase from **small** to **medium**, contact Olena in RocketChat to explain why more resources are needed. If the explanation is deemed satisfactory, the request will be approved. 

 When requesting a quota increase from **medium** to **large**, book a 30 min meeting with the Platform Services Team (send the invite to Olena and she will be pull in team's operations experts as needed). The Platform Services Team will be looking for an overview of the application design and architecture that clearly demonstrate why more resources are required for its operations.

**Comment by mitovskaol** [comment]
The following has been decided in a group meeting on Nov 5, 2020:
 - Quota increases will only be allowed in this order: small -> medium -> large. No jumping from small to large will be allowed.
- There will be two separate processes for quota increases - one for CPU quota increase and the other for storage quota increase.
-  all quota increases will be  for a **specific namespace**  and not for the entire project set at once. 

Storage Quota Increase: 
- we will have to rely on a PO/Tech Lead's word that the app will be storing a larger amount of data that can fit into a small size storage quota. There will be a button on the project edit page in the Project Registry where a PO/Tech Lead can request a storage quota increase **for a particular namespace**. The PR would have to be approved by a Platform Admin before it is actioned by the GitOps part.

CPU Quota increase:
- Before a PO/Tech Lead can request a CPU quota increase for a namespace, they have to present an app profile that shows the increased CPU consumption by a namespace over the period of time (48 hrs). Another ticket will be created to check if this data is already available in the OCP Console or a custom Prometheus query needs to be developed and uploaded into a namespace to generate the historic CPU consumption chart.
- There will be a button on the project edit page in the Project Registry where a PO/Tech Lead can request a CPU quota increase **for a particular namespace**. The PR would have to be approved by a Platform Admin **after they verified in the app profile (see above) that the namespace has indeed been running out of the CPU resources provided in the default small size quota.** After the PR is approved, it will be actioned by the GitOps part.

**Comment by j-pye** [comment]
@mitovskaol I know it's not as common but I think we should also include the option for requesting memory quota increases as well. Not necessarily as apart of the registry yet but at least on the pipeline side of things so the templates are consistent.

**Comment by StevenBarre** [comment]
I would think memory would be tied to CPU and increased in lockstep?

**Comment by mitovskaol** [comment]
@j-pye @sbarre-esit Happy to discuss it further, but I would suggest to keep the memory quota increase as a separate process to allow for more fine tune increase of resources on the Platform. If a team needs a memory increase, let them ask for it specifically in a separate request. Looking for ideas for what justification we will ask for for a memory quota increase request? We can take their word for it or write another Prometheus query that can generate historic data of memory use by a namespace that shows memory shortage.

**Comment by mitovskaol** [comment]
The quota increase request feature will be available to product teams in  Project Registry. Tere

The quotas have been discussed and approved by the PS team and is documented [here](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/254)  representatives of the Developer Community. It was decided that going with a more granular approach when teams can request quota increases in each category for a specific namespace in a project set, will generate too much administrative overhead to manage it while no creating any particular positive impact on overall system capacity/utilization. Therefore, we will be going with one size for all 3 resource categories ("pre-packaged" solution) that will apply to the entire project set (dev, test, prod and tools).

**Comment by jefkel** [comment]
Looks like the summary (as of Dec 7, 2020) captures the detail of the meeting, excluding the escalation process for requesting a quota change to something that is not a current t-shirt size.  (the conversation about involving David Ell, etc in a larger conversation about architecture and possible use of other DC services.)

That said, could I suggest that a markdown file get's created in a repository to track the documentation/decision instead of tracking through the Issue description?  This would allow for better tracking of changes to the decision (as well as be easier to collaborate with suggestions).  This issue could then contain a link to the markdown file in question.  (I would also suggest that the quota sizing detail be put into a markdown file as well - this could then be published in the devhub?)

**Comment by mitovskaol** [comment]
@jefkel  All decisions pertaining to the OCP 4 Platform that impact product teams are documented as issues in the OCP 4 Migration repo and are searchable in DevHub.

**Comment by jefkel** [comment]
Typically, an issue description is written as the issue, and solutions/workarounds/etc are documented as comments within that structure.  The current use of the "issues" seems to be a mix of that approach, along with specific solutions documented in the Issue description.

The previous suggestion is specific to Solutions/Decisions written as Github "Issue descriptions".  These decisions do not have a consistent change history, do not allow for content collaboration (ie: merging/etc) and as such, context/content/history could be lost if the issue description becomes the normal decision tracking location.

If those requirements are not important for the decision documentation, then the suggestion can be disregarded.

**Comment by mitovskaol** [comment]
@jefkel I find it easier to find the solution if it is documented in the body of the issue vs scrolling down and looking for it buried somewhere in the comments as it might not even be the last one. I agree that it is important to preserve the thought process that led us to the final solution so instead of deleting and replacing the solution  in the issue body with a new approach, we will be using the ~striking~ to indicate the solution that was abandoned and will also include an explanation of why.
