### ISSUE TITLE
Implement Quotas into Project Provisioning Workflow

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#348]
**Describe the issue**
Along with namespaces and rbac for the admin of a project, we need to also generate quotas and limits for each Project namespace.

**Which Sprint Goal is this issue related to?**
N/A - Sprint 14/15

**Additional context**
Quotas should be taken from this ticket.
https://app.zenhub.com/workspaces/openshift-4-build-out-5db73142897668000144f22b/issues/bcdevops/openshift4-rollout/254

**Definition of done Checklist (where applicable)**
- [x] Templates for Quotas and Limits added to Project Provisioner
- [x] Default Quotas/Limits set to `small` when not specified in the NATS message
- [ ] Workflow should support custom quotas sent via NATS
- [ ] PR Reviewed by Team

**Comment by StevenBarre** [comment]
The cluster config ansible already handles some of this, and will later be moved into Argo. Specifically it sets the new-project template with the default small quotas. https://github.com/bcgov-c/platform-ops/tree/ocp4-base/ocp4/roles/quota

Out of scope of this ticket, but I think we also need a way to reconcile the quotas and limitranges for all projects on a daily basis to ensure they are what we expect them to be. Also to allow us to update the definitions of small, medium, large and mass apply to all projects.

**Comment by j-pye** [comment]
>The cluster config ansible already handles some of this, and will later be moved into Argo. Specifically it sets the new-project template with the default small quotas. https://github.com/bcgov-c/platform-ops/tree/ocp4-base/ocp4/roles/quota

Thanks -- Looks like we can take the quotas there and just turn them into templates for the project provisioner. 

>Out of scope of this ticket, but I think we also need a way to reconcile the quotas and limitranges for all projects on a daily basis to ensure they are what we expect them to be. Also to allow us to update the definitions of small, medium, large and mass apply to all projects.

If we need to change the defaults for the 3 sizes that will be a simple vars change in ansible, and a workflow run of all namespaces. (part of the project provisioning workflow(s))

The reconciliation will be continuous through ArgoCD, so there's no need for another workflow or cron. Whatever is in the git repository will be true. (At least for GitOps controlled tenant resources with automated sync / self-heal enabled -- default in the current plan)

**Comment by mitovskaol** [comment]
Decided to add a label to a namespace when it gets provisioned/update to indicate what quota is was assigned ie.`small-RAM`, `small-CPU` and `small-storage`

**Comment by j-pye** [comment]
Workflow now supports default quotas/limits (small). Would it be worth closing this in favor of a new ticket to track the registry and pipeline work for custom quotas?

**Comment by mitovskaol** [comment]
The change has been implemented in the Silver cluster before the early access go live on Oct 14.
