### ISSUE TITLE
Deliver F5 components for Kamloops Silver

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#35]
- [x] Provision Network requirements
  - [x] Order / SCO additional Transceivers to connect the F5 to the core switches
  - [x] Create additional VLANs
  - [x] Update routing to flow traffic from the WAN to the VCMP and bypass the Firewall
- [x] Provision F5 components
    - [x] Stand up VCMP and configure
- [x] Hand access keys off to Cluster Deployment team
- [x] Test/Validate F5
  - [x] Validate service account roles and access
  - [x] Validate logging in F5 environment
  - [ ] Validate and test integration and creation of require F5 things when a project or pod is created.

**Comment by DanDeane** [comment]
on hold pending results of testing and Lab configuration.
Also requires conversations with DXC Network team on support and design going forward

**Comment by StevenBarre** [comment]
A plan has been developed for setting up a VCMP on the leveraged BIG-IP HA Pair in Kamloops and approved by OCIO.

**Comment by StevenBarre** [comment]
Tested NAT access via Silver VCMP. Can connect to the internet, but not back into the DMZ due to firewall rules. Network team advises they need a week to complete re-purposing the vlans and getting the firewall rules updated.

**Comment by StevenBarre** [comment]
VIPs and NAT configured on the Silver VCMP and appear to be working.

Once we get a cluster up and running we can test the CIS integration.
