### ISSUE TITLE
Document Vault Secret Management Service Definition - DevHub

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/OpenShift4-RollOut#352]
- [x] Create a description of the Vault Secret Management Service and intended use for users.
- [x]  Link description to DevHub for visibility

**Comment by NickCorcoran** [comment]
- [x] Reviewed by J-Pye.
- [x] Reviewed by Marek

**Comment by manderson-it** [comment]
Reviewed. Good as-is. 👍  Minor edit suggestions send per RC DM.

**Comment by NickCorcoran** [comment]
Published to Documize.  To be exposed to general community when service available.
https://docs.pathfinder.gov.bc.ca/s/bn6v0ac6f9gue7hhirbg/protected-platform-services/d/bulfciuipagu115fllm0/vault-service-description?currentPageId=bulfd0uipagu115fllmg

**Comment by j-pye** [comment]
Can this be closed? @NickCorcoran 
Or should it be grouped with #353 ?

**Comment by mitovskaol** [comment]
@NickCorcoran  Can you please move this Service Definition out of Documize and to https://github.com/BCDevOps/openshift-wiki/tree/master/docs where the other Service Definitions are stored. This way we will keep them all in one place and they are searchable in DevHub. Once this migration is finished and doc can be found in DevHub , this ticket can be closed.

**Comment by NickCorcoran** [comment]
Will do! - @mitovskaol - documented in that repo, just have to do PR on DevHub repo.
https://github.com/BCDevOps/openshift-wiki/blob/master/docs/OCP/VaultServiceDescription.md

**Comment by NickCorcoran** [comment]
PR made to DevHub
