### ISSUE TITLE
Document the onboarding process for teams/applications incl integration design patterns in DevHub (place in the Vault repo)

### ISSUE THREAD

**Issue by manderson-it** [BCDevOps/OpenShift4-RollOut#353]
**Describe the issue**
Developer documentation required (including developer integration/use samples) to describe access and use of the vault service.

**Which Sprint Goal is this issue related to?**
Related to the epic Vault MVP on OCP4.

**Additional context**

**Definition of done Checklist (where applicable)**
• Document completed
• Peer-Reviewed
• Document approved

**Comment by mitovskaol** [comment]
This work is tracked in a different issue,
