### ISSUE TITLE
Entitlements Issue

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#357]
**Describe the issue**
We are currently unable to build images in any of our OpenShift 4 clusters if the image is performing a package install that requires the Red Hat Subscription Manager. 

**Additional context**
Jenkins Dockerfile 
https://github.com/BCDevOps/openshift-components/blob/fix/issue-51/cicd/jenkins-basic/docker/Dockerfile
Error
```
(microdnf:152): librhsm-WARNING **: 22:49:00.703: Found 0 entitlement certificates
error: repo rhel-7-server-rpms not found
```

**Definition of done Checklist (where applicable)**
- [x] Confirmation on whether OCP4 supports cluster wide entitlements
- [x] Solution that allows teams to either build images with packages requiring entitlements or a workaround is in place
- [x] Update provisioning pipeline with build entitlements / subscriptions
- [x] Peer Review 
- [ ] Roll out to tools namespaces that have already been provisioned

**Comment by j-pye** [comment]
Official Docs outlining how to enable builds with entitlements on a per namespace basis:
https://docs.openshift.com/container-platform/4.5/builds/running-entitled-builds.html#builds-source-input-subman-config_running-entitled-builds

Potential Workaround (Although comments suggest this might not work):
https://access.redhat.com/solutions/4908771

**Comment by StevenBarre** [comment]
Opened a case with RH to track this as well https://access.redhat.com/support/cases/#/case/02748561

**Comment by StevenBarre** [comment]
Matt says
> The per namespace solution was more of a temporary stopgap because the CoreOS nodes don't subscribe in the same way as RHEL nodes did in 3.11 and you're no longer working with a "docker in docker" type build with buildah. It was done per namespaces because there was no facility to allow for the global mounting / sharing of a secret to build pods.
There is an RFE in progress for this: https://github.com/openshift/enhancements/pull/384

**Comment by StevenBarre** [comment]
https://github.com/openshift/enhancements/blob/master/enhancements/subscription-content/subscription-content-access.md

**Comment by StevenBarre** [comment]
@j-pye can you check out https://github.com/bcgov-c/platform-tools/pull/17 for directions and a secret to enable build entitlements in a namespace.

**Comment by StevenBarre** [comment]
Moving this to Backlog as something to get the Project Registry / Argo to handle setting up the secret for all projects.

**Comment by j-pye** [comment]
@sbarre-esit just to confirm this still needs to be done via project provisioning correct? if so, I'll add a task to this ticket to update the provisioning pipeline with the required templates.

**Comment by StevenBarre** [comment]
> this still needs to be done via project provisioning correct?

Correct.

**Comment by j-pye** [comment]
This has been implemented and merged. We still need to sync to existing namespaces.
https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/7

**Comment by StevenBarre** [comment]
@j-pye has this been synced to existing namespaces?

**Comment by garywong-bc** [comment]
It still hasn't been fixed as we non-admins don't have access to the `entitlements.yml` file... can we please update https://github.com/BCDevOps/OpenShift4-Migration/issues/15#issue-736283810 to put back in the 'thou shalt talk to PlatformOps to do this..'?  /cc @StevenBarre

**Comment by wmhutchison** [comment]
@garywong-bc The `entitlements.yml` file is deprecated since the contents are synced by the Project Registry into your -tools namespace. 

```
oc -n <name>-tools get cm,secret | grep platform-services-controlled
configmap/platform-services-controlled-rhsm-ca               1      93d
configmap/platform-services-controlled-rhsm-conf             1      93d
secret/platform-services-controlled-etc-pki-entitlement   Opaque                                2      93d
```
