### ISSUE TITLE
Re-Locate Google Drive contents (OpenShift 4 Buildout Project)

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#359]
**Describe the issue**
A project folder (and subfolders) exist in a personal google drive and contain project specific documentation.  This folder (and contents) need to be re-located to a BCGov owned location.

**Which Sprint Goal is this issue related to?**
unknown

**Additional context**

**Definition of done Checklist (where applicable)**
All documents managed in private google drive are either migrated to a new location, or deleted (if no longer required).

**Comment by mitovskaol** [comment]
I've added @lukegonis  to this ticket who will be working with @tosazuwa to move the content
