### ISSUE TITLE
Order NetApp devices for Kamloops/Calgary Prod

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#36]
Physical NetApp Appliances to be ordered/delivered (loading dock) before end of fiscal.

- [x] Decision on physical vs virtual
- [x] SCO for NetApp Physicals approved
- [x] Hardware ordered from Vendor
- [x] Hardware confirmed on loading dock

**Comment by jefkel** [comment]
Blocked (vacations)

**Comment by Joe-Craig** [comment]
ROM pricing sent to client for approval and decision on whether to use physical or virtual.
Client has responded that Physical is the preferred choice.

Move to building an SCO for the physical solution.

**Comment by Joe-Craig** [comment]
Met with the storage team yesterday to confirm that we are moving ahead with a full quote/SCO for the physical solution. They will speak to NetApp and get updated quotes.

We are deciding on where any costs for upgrading the network bandwidth should fall, either this SCO or the second request from David Ell for future proofing the data center network.

**Comment by jefkel** [comment]
@Joe-Craig 
Are we tracking multiple tickets for ordering NetApp Physicals? (ie: one for Kamloops Prod, and one for Calgary DR?) or are we ordering/tracking both with a single SCO/order?

**Comment by tosazuwa** [comment]
ONTAP Physical Storage Solution has been priced and the SCO is being drawn up by DXC – Over to Province by EOD Friday Jan 31st.

**Comment by Joe-Craig** [comment]
SCO-194 NetApp for OpenShift has been submitted to OCIO. @tosazuwa Can you chase on your end, I have sent out an email to Todd/David to keep them informed.

**Comment by Joe-Craig** [comment]
Delivery to Kamloops by end of march 2020..

**Comment by Joe-Craig** [comment]
Appliances delivered to both datacenters.

**Comment by Joe-Craig** [comment]
Appliances cannot be commissioned currently. Due to the COVID-19 pandemic there has been a freeze at the datacenter and the new racks cannot be energized.
