### ISSUE TITLE
Configure the samples operator to exclude the following sample images

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-RollOut#367]
Configure the production clusters to only show a subset of sample images and templates.

## OpenShift Image Catalog

| Remove  | Name |
| :---: | :------------------------- |
| [x] | apicast-gateway
| [x] | apicurito-ui
| [ ] | cli
| [ ] | cli-artifacts
| [ ] | dotnet
| [ ] | dotnet-runtime
| [x] | eap-cd-openshift
| [x] | eap-cd-runtime-openshift
| [x] | fis-java-openshift
| [x] | fis-karaf-openshift
| [x] | fuse-apicurito-generator
| [x] | fuse7-console
| [x] | fuse7-eap-openshift
| [x] | fuse7-java-openshift
| [x] | fuse7-karaf-openshift
| [ ] | golang
| [x] | httpd
| [ ] | installer
| [ ] | installer-artifacts
| [ ] | java
| [ ] | jboss-amq-62
| [ ] | jboss-amq-63
| [x] | jboss-datagrid65-client-openshift
| [x] | jboss-datagrid65-openshift
| [x] | jboss-datagrid71-client-openshift
| [x] | jboss-datagrid71-openshift
| [x] | jboss-datagrid72-openshift
| [x] | jboss-datagrid73-openshift
| [x] | jboss-datavirt64-driver-openshift
| [x] | jboss-datavirt64-openshift
| [x] | jboss-decisionserver64-openshift
| [ ] | jboss-eap64-openshift
| [ ] | jboss-eap70-openshift
| [ ] | jboss-eap71-openshift
| [ ] | jboss-eap72-openshift
| [x] | jboss-fuse70-console
| [x] | jboss-fuse70-eap-openshift
| [x] | jboss-fuse70-java-openshift
| [x] | jboss-fuse70-karaf-openshift
| [x] | jboss-processserver64-openshift
| [ ] | jboss-webserver30-tomcat7-openshift
| [ ] | jboss-webserver30-tomcat8-openshift
| [ ] | jboss-webserver31-tomcat7-openshift
| [ ] | jboss-webserver31-tomcat8-openshift
| [ ] | jboss-webserver50-tomcat9-openshift
| [ ] | jenkins
| [ ] | jenkins-agent-maven
| [ ] | jenkins-agent-nodejs
| [x] | mariadb
| [x] | modern-webapp
| [ ] | mongodb
| [ ] | must-gather
| [ ] | mysql
| [ ] | nginx
| [ ] | nodejs
| [ ] | oauth-proxy
| [ ] | openjdk-11-rhel7
| [ ] | openjdk-11-rhel8
| [ ] | openjdk-8-rhel8
| [x] | perl
| [x] | php
| [ ] | postgresql
| [ ] | python
| [ ] | redhat-openjdk18-openshift
| [x] | redhat-sso70-openshift
| [x] | redhat-sso71-openshift
| [x] | redhat-sso72-openshift
| [x] | redhat-sso73-openshift
| [ ] | redis
| [x] | rhdm-decisioncentral-rhel8
| [x] | rhdm-kieserver-rhel8
| [x] | rhdm-optaweb-employee-rostering-rhel8
| [x] | rhpam-businesscentral-monitoring-rhel8
| [x] | rhpam-businesscentral-rhel8
| [x] | rhpam-kieserver-rhel8
| [x] | rhpam-smartrouter-rhel8
| [ ] | ruby
| [ ] | sso74-openshift-rhel8
| [ ] | tests
| [ ] | tools

**Comment by jleach** [comment]
Configure the production clusters to only show a subset of sample images and templates.

## OpenShift Image Catalog

| Remove  | Name |
| :---: | :------------------------- |
| [x] | apicast-gateway
| [x] | apicurito-ui
| [x] | cli
| [x] | cli-artifacts
| [ ] | dotnet
| [ ] | dotnet-runtime
| [x] | eap-cd-openshift
| [x] | eap-cd-runtime-openshift
| [x] | fis-java-openshift
| [x] | fis-karaf-openshift
| [x] | fuse-apicurito-generator
| [x] | fuse7-console
| [x] | fuse7-eap-openshift
| [x] | fuse7-java-openshift
| [x] | fuse7-karaf-openshift
| [ ] | golang
| [x] | httpd
| [x] | installer
| [x] | installer-artifacts
| [ ] | java
| [ ] | jboss-amq-62
| [ ] | jboss-amq-63
| [x] | jboss-datagrid65-client-openshift
| [x] | jboss-datagrid65-openshift
| [x] | jboss-datagrid71-client-openshift
| [x] | jboss-datagrid71-openshift
| [x] | jboss-datagrid72-openshift
| [x] | jboss-datagrid73-openshift
| [x] | jboss-datavirt64-driver-openshift
| [x] | jboss-datavirt64-openshift
| [x] | jboss-decisionserver64-openshift
| [ ] | jboss-eap64-openshift
| [ ] | jboss-eap70-openshift
| [ ] | jboss-eap71-openshift
| [ ] | jboss-eap72-openshift
| [x] | jboss-fuse70-console
| [x] | jboss-fuse70-eap-openshift
| [x] | jboss-fuse70-java-openshift
| [x] | jboss-fuse70-karaf-openshift
| [x] | jboss-processserver64-openshift
| [ ] | jboss-webserver30-tomcat7-openshift
| [ ] | jboss-webserver30-tomcat8-openshift
| [ ] | jboss-webserver31-tomcat7-openshift
| [ ] | jboss-webserver31-tomcat8-openshift
| [ ] | jboss-webserver50-tomcat9-openshift
| [ ] | jenkins
| [ ] | jenkins-agent-maven
| [ ] | jenkins-agent-nodejs
| [x] | mariadb
| [x] | modern-webapp
| [ ] | mongodb
| [x] | must-gather
| [ ] | mysql
| [ ] | nginx
| [ ] | nodejs
| [ ] | oauth-proxy
| [ ] | openjdk-11-rhel7
| [ ] | openjdk-11-rhel8
| [ ] | openjdk-8-rhel8
| [x] | perl
| [x] | php
| [ ] | postgresql
| [ ] | python
| [ ] | redhat-openjdk18-openshift
| [x] | redhat-sso70-openshift
| [x] | redhat-sso71-openshift
| [x] | redhat-sso72-openshift
| [x] | redhat-sso73-openshift
| [ ] | redis
| [x] | rhdm-decisioncentral-rhel8
| [x] | rhdm-kieserver-rhel8
| [x] | rhdm-optaweb-employee-rostering-rhel8
| [x] | rhpam-businesscentral-monitoring-rhel8
| [x] | rhpam-businesscentral-rhel8
| [x] | rhpam-kieserver-rhel8
| [x] | rhpam-smartrouter-rhel8
| [ ] | ruby
| [ ] | sso74-openshift-rhel8
| [x] | tests
| [x] | tools

**Comment by jleach** [comment]
These images are required for cluster ops:

cli
cli-artifacts
installer
installer-artifacts
must-gather
oauth-proxy
tests
tools

**Comment by jleach** [comment]
@j-pye @sbarre-esit @jefkel @cvarjao Hey, what do you think of the remove (marked with an X) list above?

**Comment by StevenBarre** [comment]
No objections to the list from me

**Comment by jleach** [comment]
Replaced by #462
