### ISSUE TITLE
Wrap Artifactory credential creation into our GitOps process

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-RollOut#370]
Since every team will most likely need to access Artifactory either as pull through or as a place to store their production images we would like to simplify the process. We will create the Artifactory credential as part of namespace provisioning so that it is easy and ready for use as soon as they on-board to the platform.

**Comment by jefkel** [comment]
Duplicate of #345?

**Comment by jleach** [comment]
Yup. Closing.
