### ISSUE TITLE
Implement mechanics so we can build images with licensed entitlements

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-RollOut#371]
On OCP3 we were able to build images with RH entitlements (RPMs) because the "licence" information was embedded as a shared file within docker. This meant that each team using entitlements would not need to do anything, like register credentials or licence details. On OCP4, because we no longer use docker this is not possible. We need to monitor RH for a solution to this.

**Comment by StevenBarre** [comment]
Is this a duplicate of #357 ?

**Comment by jleach** [comment]
Probably. Closing.
