### ISSUE TITLE
Configure the samples operator to exclude the following templates

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-RollOut#373]
| REMOVE|NAME                                            |DESCRIPTION                                                                     |  
|:---:|:-----------------------------------------------|:-------------------------------------------------------------------------------|
| [x] |3scale-gateway                                  |3scale's APIcast is an NGINX based API gateway used to integrate your interna...|  
| [x] |amq63-basic                                     |Application template for JBoss A-MQ brokers. These can be deployed as standal...|  
| [x] |amq63-persistent                                |An example JBoss A-MQ application. For more information about using this temp...|  
| [x] |amq63-persistent-ssl                            |An example JBoss A-MQ application. For more information about using this temp...|  
| [x] |amq63-ssl                                       |An example JBoss A-MQ application. For more information about using this temp...|  
| [ ] |apicurito                                       |Design beautiful, functional APIs with zero coding, using a visual designer f...|  
| [x] |cache-service                                   |Red Hat Data Grid is an in-memory, distributed key/value store.                 |  
| [x] |cakephp-mysql-example                           |An example CakePHP application with a MySQL database. For more information ab...|  
| [x] |cakephp-mysql-persistent                        |An example CakePHP application with a MySQL database. For more information ab...|  
| [x] |dancer-mysql-example                            |An example Dancer application with a MySQL database. For more information abo...|  
| [x] |dancer-mysql-persistent                         |An example Dancer application with a MySQL database. For more information abo...|  
| [x] |datagrid-service                                |Red Hat Data Grid is an in-memory, distributed key/value store.                 |  
| [x] |datavirt64-basic-s2i                            |Application template for JBoss Data Virtualization 6.4 services built using S2I.|  
| [x] |datavirt64-extensions-support-s2i               |An example JBoss Data Virtualization application. For more information about... |  
| [x] |datavirt64-ldap-s2i                             |Application template for JBoss Data Virtualization 6.4 services that configur...|  
| [x] |datavirt64-secure-s2i                           |An example JBoss Data Virtualization application. For more information about... |  
| [x] |decisionserver64-amq-s2i                        |An example BRMS decision server A-MQ application. For more information about... |  
| [x] |decisionserver64-basic-s2i                      |Application template for Red Hat JBoss BRMS 6.4 decision server applications... |  
| [ ] |django-psql-example                             |An example Django application with a PostgreSQL database. For more informatio...|  
| [ ] |django-psql-persistent                          |An example Django application with a PostgreSQL database. For more informatio...|  
| [ ] |dotnet-example                                  |An example .NET Core application.                                               |  
| [ ] |dotnet-pgsql-persistent                         |An example .NET Core application with a PostgreSQL database. For more informa...|  
| [ ] |eap-cd-basic-s2i                                |An example JBoss Enterprise Application Platform continuous delivery applicat...|  
| [ ] |eap-cd-starter-s2i                              |An example JBoss Enterprise Application Platform continuous delivery applicat...|  
| [ ] |eap72-basic-s2i                                 |An example Red Hat JBoss EAP 7 application. For more information about using... |  
| [ ] |eap72-https-s2i                                 |An example Red Hat JBoss EAP 7 application configured with secure communicati...|  
| [ ] |eap72-mongodb-persistent-s2i                    |An example Red Hat JBoss EAP 7 application with a MongoDB database. For more... |  
| [ ] |eap72-mongodb-s2i                               |An example Red Hat JBoss EAP 7 application with a MongoDB database. For more... |  
| [ ] |eap72-mysql-persistent-s2i                      |An example Red Hat JBoss EAP 7.2 application with a persistent MySQL database...|  
| [ ] |eap72-mysql-s2i                                 |An example Red Hat JBoss EAP 7 application with a MySQL database. For more in...|  
| [ ] |eap72-postgresql-persistent-s2i                 |An example Red Hat JBoss EAP 7 application with a persistent PostgreSQL datab...|  
| [ ] |eap72-postgresql-s2i                            |An example Red Hat JBoss EAP 7 application with an PostgreSQL database config...|  
| [ ] |eap72-sso-s2i                                   |An example Red Hat JBoss EAP 7 application Single Sign-On application. For mo...|  
| [ ] |eap72-third-party-db-s2i                        |An example Red Hat JBoss EAP 7 application. For more information about using... |  
| [x] |fuse75-console                                  |The Red Hat Fuse Console eases the discovery and management of Fuse applicati...|  
| [x] |fuse76-console                                  |The Red Hat Fuse Console eases the discovery and management of Fuse applicati...|  
| [x] |httpd-example                                   |An example Apache HTTP Server (httpd) application that serves static content....|  
| [x] |jenkins-ephemeral                               |Jenkins service, without persistent storage....                                 |  
| [x] |jenkins-ephemeral-monitored                     |Jenkins service, without persistent storage. ...                                |  
| [x] |jenkins-persistent                              |Jenkins service, with persistent storage....                                    |  
| [x] |jenkins-persistent-monitored                    |Jenkins service, with persistent storage. ...                                   |  
| [ ] |jws31-tomcat7-basic-s2i                         |Application template for JWS applications built using S2I.                      |  
| [ ] |jws31-tomcat7-https-s2i                         |An example JBoss Web Server application configured for use with https. For mo...|  
| [ ] |jws31-tomcat7-mongodb-persistent-s2i            |An example JBoss Web Server application with a MongoDB database. For more inf...|  
| [ ] |jws31-tomcat7-mongodb-s2i                       |Application template for JWS MongoDB applications built using S2I.              |  
| [ ] |jws31-tomcat7-mysql-persistent-s2i              |An example JBoss Web Server application with a MySQL database. For more infor...|  
| [ ] |jws31-tomcat7-mysql-s2i                         |Application template for JWS MySQL applications built using S2I.                |  
| [ ] |jws31-tomcat7-postgresql-persistent-s2i         |An example JBoss Web Server application with a PostgreSQL database. For more... |  
| [ ] |jws31-tomcat7-postgresql-s2i                    |Application template for JWS PostgreSQL applications built using S2I.           |  
| [ ] |jws31-tomcat8-basic-s2i                         |An example JBoss Web Server application. For more information about using thi...|  
| [ ] |jws31-tomcat8-https-s2i                         |An example JBoss Web Server application. For more information about using thi...|  
| [ ] |jws31-tomcat8-mongodb-persistent-s2i            |An example JBoss Web Server application with a MongoDB database. For more inf...|  
| [ ] |jws31-tomcat8-mongodb-s2i                       |Application template for JWS MongoDB applications built using S2I.              |  
| [x] |jws31-tomcat8-mysql-persistent-s2i              |An example JBoss Web Server application with a MySQL database. For more infor...|  
| [x] |jws31-tomcat8-mysql-s2i                         |Application template for JWS MySQL applications built using S2I.                |  
| [ ] |jws31-tomcat8-postgresql-persistent-s2i         |Application template for JWS PostgreSQL applications with persistent storage... |  
| [ ] |jws50-tomcat9-basic-s2i                         |An example JBoss Web Server application. For more information about using thi...|  
| [ ] |jws50-tomcat9-https-s2i                         |An example JBoss Web Server application. For more information about using thi...|  
| [ ] |jws50-tomcat9-mongodb-persistent-s2i            |An example JBoss Web Server application with a MongoDB database. For more inf...|  
| [ ] |jws50-tomcat9-mongodb-s2i                       |Application template for JWS MongoDB applications built using S2I.              |  
| [ ] |jws50-tomcat9-mysql-persistent-s2i              |An example JBoss Web Server application with a MySQL database. For more infor...|  
| [x] |jws50-tomcat9-mysql-s2i                         |Application template for JWS MySQL applications built using S2I.                |  
| [ ] |jws50-tomcat9-postgresql-persistent-s2i         |Application template for JWS PostgreSQL applications with persistent storage... |  
| [x] |mariadb-ephemeral                               |MariaDB database service, without persistent storage. For more information ab...|  
| [x] |mariadb-persistent                              |MariaDB database service, with persistent storage. For more information about...|  
| [ ] |mongodb-ephemeral                               |MongoDB database service, without persistent storage. For more information ab...|  
| [ ] |mongodb-persistent                              |MongoDB database service, with persistent storage. For more information about...|  
| [x] |mysql-ephemeral                                 |MySQL database service, without persistent storage. For more information abou...|  
| [x] |mysql-persistent                                |MySQL database service, with persistent storage. For more information about u...|  
| [x] |nginx-example                                   |An example Nginx HTTP server and a reverse proxy (nginx) application that ser...|  
| [ ] |nodejs-mongo-persistent                         |An example Node.js application with a MongoDB database. For more information... |  
| [ ] |nodejs-mongodb-example                          |An example Node.js application with a MongoDB database. For more information... |  
| [ ] |openjdk-web-basic-s2i                           |An example Java application using OpenJDK. For more information about using t...|  
| [ ] |postgresql-ephemeral                            |PostgreSQL database service, without persistent storage. For more information...|  
| [ ] |postgresql-persistent                           |PostgreSQL database service, with persistent storage. For more information ab...|  
| [x] |processserver64-amq-mysql-persistent-s2i        |An example BPM Suite application with A-MQ and a MySQL database. For more inf...|  
| [x] |processserver64-amq-mysql-s2i                   |An example BPM Suite application with A-MQ and a MySQL database. For more inf...|  
| [x] |processserver64-amq-postgresql-persistent-s2i   |An example BPM Suite application with A-MQ and a PostgreSQL database. For mor...|  
| [x] |processserver64-amq-postgresql-s2i              |An example BPM Suite application with A-MQ and a PostgreSQL database. For mor...|  
| [x] |processserver64-basic-s2i                       |An example BPM Suite application. For more information about using this templ...|  
| [x] |processserver64-externaldb-s2i                  |An example BPM Suite application with a external database. For more informati...|  
| [x] |processserver64-mysql-persistent-s2i            |An example BPM Suite application with a MySQL database. For more information... |  
| [x] |processserver64-mysql-s2i                       |An example BPM Suite application with a MySQL database. For more information... |  
| [x] |processserver64-postgresql-persistent-s2i       |An example BPM Suite application with a PostgreSQL database. For more informa...|  
| [x] |rails-pgsql-persistent                          |An example Rails application with a PostgreSQL database. For more information...|  
| [x] |rails-postgresql-example                        |An example Rails application with a PostgreSQL database. For more information...|  
| [ ] |redis-ephemeral                                 |Redis in-memory data structure store, without persistent storage. For more in...|  
| [ ] |redis-persistent                                |Redis in-memory data structure store, with persistent storage. For more infor...|  
| [x] |rhdm77-authoring                                |Application template for a non-HA persistent authoring environment, for Red H...|  
| [x] |rhdm77-authoring-ha                             |Application template for a HA persistent authoring environment, for Red Hat D...|  
| [x] |rhdm77-kieserver                                |Application template for a managed KIE Server, for Red Hat Decision Manager 7...|  
| [x] |rhdm77-prod-immutable-kieserver                 |Application template for an immutable KIE server in a production environment,...|  
| [x] |rhdm77-prod-immutable-kieserver-amq             |Application template for an immutable KIE server in a production environment... |  
| [x] |rhdm77-trial-ephemeral                          |Application template for an ephemeral authoring and testing environment, for... |  
| [x] |rhpam77-authoring                               |Application template for a non-HA persistent authoring environment, for Red H...|  
| [x] |rhpam77-authoring-ha                            |Application template for a HA persistent authoring environment, for Red Hat P...|  
| [x] |rhpam77-kieserver-externaldb                    |Application template for a managed KIE Server with an external database, for... |  
| [x] |rhpam77-kieserver-mysql                         |Application template for a managed KIE Server with a MySQL database, for Red... |  
| [x] |rhpam77-kieserver-postgresql                    |Application template for a managed KIE Server with a PostgreSQL database, for...|  
| [x] |rhpam77-managed                                 |Application template for a managed HA production runtime environment, for Red...|  
| [x] |rhpam77-prod                                    |Application template for a managed HA production runtime environment, for Red...|  
| [x] |rhpam77-prod-immutable-kieserver                |Application template for an immutable KIE server in a production environment,...|  
| [x] |rhpam77-prod-immutable-kieserver-amq            |Application template for an immutable KIE server in a production environment... |  
| [x] |rhpam77-prod-immutable-monitor                  |Application template for a router and monitoring console in a production envi...|  
| [x] |rhpam77-trial-ephemeral                         |Application template for an ephemeral authoring and testing environment, for... |  
| [x] |s2i-fuse75-spring-boot-camel                    |Spring Boot and Camel QuickStart. This example demonstrates how you can use A...|  
| [x] |s2i-fuse75-spring-boot-camel-rest-3scale        |Spring Boot, Camel REST DSL and 3Scale QuickStart. This example demonstrates... |  
| [x] |s2i-fuse75-spring-boot-camel-xml                |Spring Boot and Camel Xml QuickStart. This example demonstrates how you can u...|  
| [x] |s2i-fuse76-spring-boot-camel                    |Spring Boot and Camel QuickStart. This example demonstrates how you can use A...|  
| [x] |s2i-fuse76-spring-boot-camel-rest-3scale        |Spring Boot, Camel REST DSL and 3Scale QuickStart. This example demonstrates... |  
| [x] |s2i-fuse76-spring-boot-camel-xml                |Spring Boot and Camel Xml QuickStart. This example demonstrates how you can u...|  
| [x] |sso72-https                                     |An example RH-SSO 7 application. For more information about using this templa...|  
| [x] |sso72-mysql                                     |An example RH-SSO 7 application with a MySQL database. For more information a...|  
| [x] |sso72-mysql-persistent                          |An example RH-SSO 7 application with a MySQL database. For more information a...|  
| [x] |sso72-postgresql                                |An example RH-SSO 7 application with a PostgreSQL database. For more informat...|  
| [x] |sso72-postgresql-persistent                     |An example RH-SSO 7 application with a PostgreSQL database. For more informat...|  
| [x] |sso73-https                                     |An example application based on RH-SSO 7.3 image. For more information about... |  
| [x] |sso73-mysql                                     |An example application based on RH-SSO 7.3 image. For more information about... |  
| [x] |sso73-mysql-persistent                          |An example application based on RH-SSO 7.3 image. For more information about... |  
| [x] |sso73-ocp4-x509-https                           |An example application based on RH-SSO 7.3 image. For more information about... |  
| [x] |sso73-ocp4-x509-mysql-persistent                |An example application based on RH-SSO 7.3 image. For more information about... |  
| [x] |sso73-ocp4-x509-postgresql-persistent           |An example application based on RH-SSO 7.3 image. For more information about... |  
| [x] |sso73-postgresql                                |An example application based on RH-SSO 7.3 image. For more information about... |  
| [x] |sso73-postgresql-persistent                     |An example application based on RH-SSO 7.3 image. For more information about... |  
| [ ] |sso74-https                                     |An example application based on RH-SSO 7.4 on OpenJDK image. For more informa...|  
| [ ] |sso74-ocp4-x509-https                           |An example application based on RH-SSO 7.4 on OpenJDK image. For more informa...|  
| [ ] |sso74-ocp4-x509-postgresql-persistent           |An example application based on RH-SSO 7.4 on OpenJDK image. For more informa...|  
| [ ] |sso74-postgresql                                |An example application based on RH-SSO 7.4 on OpenJDK image. For more informa...|  
| [ ] |sso74-postgresql-persistent                     |An example application based on RH-SSO 7.4 on OpenJDK image. For more informa...|

**Comment by jleach** [comment]
@j-pye @sbarre-esit @jefkel @cvarjao Hey, what do you think of the remove (marked with an X) list above?

**Comment by jleach** [comment]
All Jenkins removed because we'll replace the templates with our own version with "sane" defaults for resource usage.

**Comment by StevenBarre** [comment]
LGTM. Once we've pruned everything I think I'll test creating all the templates that remain to ensure they all still work and we didn't over prune imagestreams needed by templates.

**Comment by StevenBarre** [comment]
Some of the templates that are marked to be kept depend on images marked for removal in #367 . Can someone double check this list?

**Comment by jleach** [comment]
Replaced by #462
