### ISSUE TITLE
Rename the thetis cluster to clab

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-RollOut#375]
The `thetis` cluster has its old project name and should be renamed to alight to our naming convention. Please rename to `clab`?

**Comment by jleach** [comment]
@sbarre-esit @j-pye Created this so we don't loose track of this task. Not sure who can pound this issue into submission.

**Comment by StevenBarre** [comment]
Duplicate of #205. Cluster is being renamed as its rebuilt from DMZ to SDN compartment.
