### ISSUE TITLE
Remove developer access to openshift "NetworkPolicies" objects

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#376]
**Describe the issue**
In order to reduce the confusion between openshift networkpolicy (a built in sdn implementation object) and our Aporeto network policies, we could remove RBAC access to networkpolicy objects in developer namespaces.

**Comment by matthieu-foucault** [comment]
+1 for this. Some helm charts in the wild come with the option to enable network policies, which to the untrained eye looks similar enough to a NetworkSecurityPolicy. cc @dleard 
In addition to that, the Web Console UI has a Network Policies section, which adds to the confusion. I wonder if there is a way to hide that section?

**Comment by jefkel** [comment]
cancelled (will be leveraging networkpolicy objects after aporeto removal)
