### ISSUE TITLE
Deploy CAM Tool in Klab/pathfinder Lab for migration tool testing

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/OpenShift4-RollOut#378]
**Describe the issue**
Deploy and verify the RH Cluster Application Migration tool (CAM) to a lab environment, and document a simple namespace migration.

**Definition of done Checklist (where applicable)**
- [ ] CAM Tool successfully deployed to klab and lab.pathfinder clusters
- [ ] namespace migration successfully completed for a sample app.  (rc or other 2-piece application)

**Comment by mitovskaol** [comment]
The Migration Toolkit for Containers tool has been successully implemented and use for Openshift 3 to 4 migration.
