### ISSUE TITLE
Decide on the authentication options for access to OCP 4 Console and Clusters

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/OpenShift4-RollOut#387]
As a Platform user I would like to have mutliple options available to accessing the Openshift 4 clusters and the console.  At this moment only GitHub 2FA authentication is supported for accessing the Openshift 4 Platform.

Github (bcdevops Organization with 2FA enforced at the GitHub org)
IDIR (leverage SSO realm to add IDIR authentication to the cluster)

See [PR718](https://github.com/BCDevOps/platform-services/pull/718) for additional detail

**Comment by jefkel** [comment]
This feels like multiple tickets to cover all the scope:
1: Choose implementation option for SSO integration (technical deployment choice to be made with business input re: pro's and con's)
2: Document provisioning steps to illustrate the developer team control of authorizations.

**Comment by jefkel** [comment]
Original ticket: 

> As a Platform user I would like to have mutliple options available to accessing the Openshift 4 clusters and the console. Flexible approach is also needed to create a robust RBAC model around the namespace access where only IDIR users (gov employees) have a permission to grant access to a namespace to other users. At this moment only GitHub 2FA authentication is supported for accessing the Openshift 4 Platform.

Scope for this ticket narrowed to multiple options for accessing openshift 4.
Ticket created to address scope: Robust RBAC model [OpenShift4-Buildout board: 395](https://app.zenhub.com/workspaces/openshift-4-build-out-5db73142897668000144f22b/issues/bcdevops/openshift4-rollout/395)
Linked existing ticket for IDIR and 2FA support [PlatformExperience Board: 568](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/568)

**Comment by mitovskaol** [comment]
The decision has been made and documented.
