### ISSUE TITLE
Configure NetApp devices for Kamloops Silver

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#39]
- [x] Establish Cluster Name - MCS-KPROD-NETAPP
- [x] Order gear under #36
- [x] Plan network design
- [x] Reserve IP Addresses and DNS Names from Network Team
- [x] Storage Team - Download latest ONTAP firmware and install and configure
  - [ ] Submit request for SMTP to Infrastructure Group
  - [ ] Configure AutoSupport for HTTPS  (Firewall requests)
  - [ ] Configure Timezone and NTP
  - [ ] Create SVM for Trident/OpenShift
  - [ ] Create SVM for CORP Login
  - [ ] Create Aggregates on both nodes
  - [ ] Configure Aggregate Delegation
  - [ ] Disable FSID
  - [ ] Configure NFS Protocol and NFS Data LIF
  - [ ] Configure iSCSI Protocol and iSCSI Data LIFs on each node
  - [ ] Add cluster to Unified Manager
- [ ] Setup Trident on the cluster and test

**Comment by StevenBarre** [comment]
Completed
