### ISSUE TITLE
SG - Vault Service Implemented and Operationalized in KLAB

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/OpenShift4-RollOut#398]
Vault is a secret management tools that will be available for product teams on the new Platform.

This Sprint we aim to implement the Vault Shared Service in a KLAB environment (our sandbox cluster) and build automation for building, deployment and configuration of the service.  Another deliverable will include  development of developer self-help documentation on how to integrate and use the Vault Secret Management Service  on the Platform.

**Comment by mitovskaol** [comment]
The Vaultt Service has been implemented in KLAB and Silver for internal use (Platform Services team only) in Feb 2021.
