### ISSUE TITLE
Artifactory Operator Cluster Admin action for Silver Cluster

### ISSUE THREAD

**Issue by caggles** [BCDevOps/OpenShift4-RollOut#401]
Please head on over to https://github.com/BCDevOps/developer-experience/tree/cailey/artifactory/operator-upgrade/apps/artifactory/artifactory-operator/install and run the clusterAdmin.yml playbook that you find there. There is a little more detail on how to do this in the Readme.

Quick rundown of what it does:

1. adds the artifactoryrepository CRD
2. adds the artifactoryserviceaccount CRD
3. aggregates "view artifactoryrepository" privilege to the admin/edit/view/cluster-reader roles
3. aggregates "edit artifactoryserviceaccount" privilege to the admin/edit roles
4. aggregates "view artifactoryserviceaccount" privilege to the view/cluster-reader roles
5. creates a role and rolebinding that allows the operator to watch for the creation of these two CRDs across the cluster
6. creates a role and rolebinding that allows the bcdevopsadmin service account to administer the CRDs across the cluster.

Let me know if there's anything more you need from me!

**Comment by StevenBarre** [comment]
Done! Please verify and close the ticket.

**Comment by caggles** [comment]
hey @sbarre-esit - i just updated clusterAdmin.yaml to include the creation of the role that's causing me problems. Please run the playbook again!
