### ISSUE TITLE
Cluster SSO Implementation

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#404]
Definition of Done:
- [x] Authentication flows created for Github Org Restriction in Test Realm
- [x] Authentication flows created for Github Org Restriction in Prod Realm
- [x] OAuth Ansible Role for CCM

**Comment by jefkel** [comment]
Integrations for cluster authentication have been completed for KLAB and SILVER clusters (and OAuth settings have been added to CCM flow to connect)

Question: 
- Is the CCM role listed above just the OAuth configuration role for the cluster? (in which case it's done as well, and the ticket can be closed)
- or is the CCM role listed above related to codifying the SSO Realm configuration?

**Comment by jefkel** [comment]
Note: limitation in SSO implementation that forces lowercase for all usernames.
https://issues.redhat.com/browse/RHBPMS-2882?attachmentViewMode=list

PR 1 - https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/1
to fix project auto-provisioning in place, but additional documentation for Application Team RBAC is needed to ensure clarity on lowercase requirements for usernames.

**Comment by j-pye** [comment]
>Is the CCM role listed above just the OAuth configuration role for the cluster? (in which case it's done as well, and the ticket can be closed)

Yes. 

Should we move the remaining documentation and keycloak automation to other tickets?

**Comment by jefkel** [comment]
Either create tickets for them separately, or explicitly add the documentation and sso realm configuration automation to this ticket as part of the definition of done.

my feeling is that the configuration automation is a specific enough piece of work that it could have it's own ticket, but if there are manual steps to configure the realm (for now), that documentation needs to be part of this ticket before we can close (or we haven't left any breadcrumb trail to repeat our work if we need to.)

**Comment by ShellyXueHan** [comment]
### Automation ticket:
Here's the ticket for automation on sso/keycloak: https://github.com/BCDevOps/OpenShift4-RollOut/issues/417

### manual steps to setup OCP4 Cluster login KeyCloak flow:
1. create the app KeyCloak realms with `IDIR` and `GitHub` IDP, setup duplicate email and theme
2. Configure GitHub organization to role mapper:
  - in `_github` realm, go to IDP and add a `Role Importer` mapper (if not exist yet) with prefix as `org:`
  - create realm roles for each target GitHub org with the format `org:<org_name>` (case sensitive)
  - and then, find the app realm client and create a new client mapper `User Realm Role`, with prefix as `github:` and claim role name as `roles`, type as string
3. Configure app realm IDP to take the mapper:
  - in your app realm, create realm/client roles for each target GitHun org
  - then go to GitHub IDP and create a `Two Way Claim to Role` mapper
    - claim as `roles`
    - claim value as `github:org:<org_name>`
    - select the role created just now to map on
4. Setup a Post Broker Login flow that filters GitHub org roles:
  - start with a new flow
  - have a sub execution of type `Required Role By Client`
  - config the execution with target client, role to filter on, and a URL to redirect to if user does not have the required role
5. Setup First Broker Login flow for GitHub IDP:
  - take a copy of the original flow
  - disable the user review profile config execution, which helps to avoid unauthorized users to waste the time
  - also disable OTP sub flow to avoid triple factor auth
6. Config GitHub IDP flows
  - override the first and post broker login flows in the IDP settings
7. IDIR OTP (depends on IDIR service)

**Comment by j-pye** [comment]
@jefkel @ShellyXueHan should the manual steps posted be moved to the keycloak or ocp4 repo before closing this ? or are we okay with referencing this ticket until automation is completed in the ticket Shelly linked?

**Comment by jefkel** [comment]
Breadcrumb added to find this detail, I'm happy to close this.

**Comment by j-pye** [comment]
Thanks for the breadcrumb :) Closing.
