### ISSUE TITLE
Azure Key Vault for Auto-Unsealing Vault DR sites

### ISSUE THREAD

**Issue by manderson-it** [BCDevOps/OpenShift4-RollOut#405]
Describe the issue
Deploy Azure Key Vault for each Vault DR cluster.

Which Sprint Goal is this issue related to?
n/a

Additional context
The Azure Key Vault allows each Vault pod to be automatically unsealed and therefore eliminate the manual unseal process per pod.
An unseal operation is mandatory when a pod starts for the first time and on any pod restart scenario be it maintenance or failure.

Definition of done Checklist (where applicable)
• DR Vault LAB deployment is verified to be auto-unsealed with Azure Key Vault
• DR Vault PROD deployment is verified to be auto-unsealed with Azure Key Vault
• Peer-Reviewed

**Comment by j-pye** [comment]
We can still provision the Azure key vaults and Vault itself, but we can't activate the DR piece yet.

**Comment by mitovskaol** [comment]
@j-pye Can you please update the status of the ticket and if we are still awaiting the response from the vendor as per [this ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/318) , please let me know and I can escalate.
