### ISSUE TITLE
Add a logo to the GitHub oAuth app so it looks more polished.

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-RollOut#407]
## Story

As a user of OCP4 I'd like to authenticate with my GitHub ID and know that authentication is more legitimate.

## Description

The default icon for our GitHub oAuth app looks pretty lame - like its a haxor site. It would be good to give it a proper name and icon so it looks polished.

![Screen Shot 2020-10-09 at 10.46.52 AM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/0d1427a6-9d98-41ae-99dc-e2fd80bc385b)

# Done When

A users sees the GitHub authentication screen and it has a proper BCGov LOGO and name associated with what they're logging into.

**Comment by StevenBarre** [comment]
@jleach I think we can close this now that SSO is being used?

**Comment by jefkel** [comment]
When I log into the clusters, it shows a BCGov logo (seems super small logo inside a large logo space?), and the text says:
![image.png](https://images.zenhubusercontent.com/5c37a278f6ef6263f5aa9cbe/a57e9f1e-5060-4f86-8f99-0a0c8a2f2f6d)

Would it make sense to keep this ticket until the "continue to" target is updated to reflect `oidc.gov.bc.ca`? (and maybe a larger BC gov logo in the circle?)

**Comment by mitovskaol** [comment]
@ShellyXueHan Can you please change *pathfinder-rh-sso-prod* to *oidc.gov.bc.ca* or *BC Gov KeyCloak SSO*

**Comment by ShellyXueHan** [comment]
Done.
