### ISSUE TITLE
Pen test Remediation

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/OpenShift4-RollOut#409]
Conduct the following remediation items.  See report for specific details.

- [x] Secure cookie [02817747](https://access.redhat.com/support/cases/#/case/02817747)
- [ ] Password autocomplete [02817749](https://access.redhat.com/support/cases/#/case/02817749)
- [ ] Strict Transport Security [02817751](https://access.redhat.com/support/cases/#/case/02817751)
- [ ] CSRF [02817754](https://access.redhat.com/support/cases/#/case/02817754)
- [ ] Frameable Response [02817757](https://access.redhat.com/support/cases/#/case/02817757)

Test that all fixes have been applied
- [ ] Tested in KLAB
- [ ] Tested in SILVER

**Comment by StevenBarre** [comment]
Looks like most of these are in OCP software, I'll have to make some tickets with RH for each of them.

**Comment by StevenBarre** [comment]
Initial estimate of 1 point to create all the tickets with Red Hat about these fixes. Will likely change once we get more details on what is needed to implement the fixes.

**Comment by StevenBarre** [comment]
Red Hat responses

## Secure cookie 02817747

I'll take a look at this, but the console should already leverage secure cookies.

## Password autocomplete 02817749

I will open an RFE for this. I do not see anything currently on the roadmap.

## Strict Transport Security 02817751

There is an RFE for this already

This will be in 4.7 or 4.8 - I will let you know

## CSRF 02817754

This looks very narrow in relation to prometheus and thanos. Its been implemented throughout the console as I thought.

I will open a BZ for those 2 components.

## Frameable Response 02817757

There are 2 RFEs open in this area

**Comment by StevenBarre** [comment]
Moving to blocked while we wait on RH to release fixes.

**Comment by StevenBarre** [comment]
# Secure cookie 02817747
Turns out this was Artifactory and not part of OpenShift

**Comment by NickCorcoran** [comment]
Secure cookie issue moved to reflect Artifactory 
- bcdevops/developer-experience/1087

**Comment by michaelshire** [comment]
@StevenBarre @NickCorcoran 
> Strict Transport Security 02817751
> There is an RFE for this already
> 
> This will be in 4.7 or 4.8 - I will let you know

This is just an annotation that needs to be configured on the route.  Perhaps Aqua could have a policy to enforce the annotation on all routes?
https://docs.openshift.com/container-platform/4.6/networking/routes/route-configuration.html#nw-enabling-hsts_route-configuration

**Comment by lukegonis** [comment]
Closing this issue, as these items are low impact/low risk.
