### ISSUE TITLE
Upgrade F5 CIS to 2.2.0

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#413]
**Describe the issue**
The F5 CIS is used to automate the F5 load balancer. A new version has been released and should be installed in KLAB and tested.
https://clouddocs.f5.com/containers/latest/reference/release-notes.html

**Which Sprint Goal is this issue related to?**

**Additional context**
This is needed for Vault to replicate properly

**Definition of done Checklist (where applicable)**
- [x] Ansible playbooks for F5 CIS updated
- [x] CIS 2.2.0 installed in KLAB
- [x] Test new CRD for non-http VIPs
- [ ] Create new ticket to upgrade SILVER

**Comment by wmhutchison** [comment]
Staying in Backlog for now since it's not clear yet if this is a dependency for GOLD DR or not.

**Comment by wmhutchison** [comment]
Issue no longer valid, since other tickets involving F5 integration work have taken us to newer versions of the operator across the board. Closing this off.
