### ISSUE TITLE
SG - OCP 4- Aporeto Service Operationalization Part 1

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/OpenShift4-RollOut#416]
As the Aporeto Network Security Service became a critical service running on the Silver cluster in the Openshift 4 Platform controlling all communications across the Platform, its namespaces and pods , the Platform Services Team want to look at the opportunities to further improve the stability and performance of the Service through automation of currently manual tasks and adding monitoring for the Service uptime and performance.

**Comment by j-pye** [comment]
@mitovskaol this should be able to be closed now as the spike has been resolved.
