### ISSUE TITLE
Validate cluster availability for Ops

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#42]

**Comment by StevenBarre** [comment]
@stewartshea @jefkel could we get a better DoD on this? What exactly is "availability for Ops" mean?

**Comment by jefkel** [comment]
My take is that all tasks/configuration the operational team (DXC) need to have in place to be comfortable with supporting this as a production platform.

What were your ideas for a DoD?

**Comment by StevenBarre** [comment]
Should we just close this and all the other "validate cluster availability for ops" tasks as duplicates of Develop Day 2 tasks #223 [EPIC] ? I had no ideas for a DoD since I didn't create this ticket and was unsure what it was referring to. I can't read Shea's mind from last November :P

**Comment by stewartshea** [comment]
Haha neither can I, I mean, these were all high level initial cards that we
knew would change. I'd vote to close it.

--
Shea Stewart (He/Him), Partner
Arctiq: Intelligent Architecture
shea.stewart@arctiq.ca
+1-647-972-5191
http://www.arctiq.ca

**Comment by jefkel** [comment]
I like the Day 2 Epic ... way more detail in that that feels appropriate

**Comment by StevenBarre** [comment]
Closing in favor of  #223
