### ISSUE TITLE
Load Balancer config changes for OCP4

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#421]
**Describe the issue**
Originally the VIPs for the OCP4 environments were set up with simple TCP health checks and long timeouts. This causes lots of errors in the logs like `http: TLS handshake error from 142.34.194.2:50532: EOF`. It also causes some issues when the endpoints are cycled during patching as the VIP doesn't fail over fast enough to new endpoints.

[The docs](https://docs.openshift.com/container-platform/4.5/installing/installing_bare_metal/installing-bare-metal.html#installation-network-user-infra_installing-bare-metal) also mention which urls should be checked for the API. Some testing shows the URL for the 22623 port check as well. And for the ingress pods we can use the readyness check they come with.

The docs also mention that

> Session persistence is not required for the API load balancer to function properly.

and that

> If the true IP address of the client can be seen by the load balancer, enabling source IP-based session persistence can improve performance for applications that use end-to-end TLS encryption.

**Which Sprint Goal is this issue related to?**
SG - Sprint 19 Platform Hot Fixes

**Additional context**
For the VIPs for *.apps.cluster change to source IP stickiness instead of no stickiness

Check the pool members on port 1936, even though the traffic being balanced is on 80/443
HTTP :1936
Interval 5
Timeout 16
Send String GET /healthz/ready HTTP/1.1
Receive String HTTP/1.1 200 OK header

For the VIPs for api.cluster change the health check to HTTPS.
HTTPS :6443
Interval 5
Timeout 16
Send String GET /readyz HTTP/1.1
Receive String HTTP/1.1 200 OK header

For the VIPs for api-int.cluster change the health check to HTTPS.
HTTPS :22623
Interval 5
Timeout 16
Send String GET /healthz HTTP/1.1
Receive String HTTP/1.1 200 OK header

**Definition of done Checklist (where applicable)**
- [x] Submit tickets to Network team to make the changes
- [x] Test in KLAB and CLAB
- [x] Create CHG to make change in Silver - arrange with Platform Services team when they would like it to occur
- [x] Confirm Silver VIPs are all functional

**Comment by StevenBarre** [comment]
Change was made to KLAB and CLAB this morning. So far seems to be working well.

![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/32d8d8e8-a092-4260-99f2-6c907e2fdf7f)

@mitovskaol when would you like this scheduled for in SILVER? There should be no impact to running services. The usual change window for load balancers is 6am on weekdays but I'm sure we could do another time if you'd prefer.

**Comment by mitovskaol** [comment]
@sbarre-esit  if you have a standard time for this change, lets go with it. Just post a notice in the #devops-ocp4-migration channel today and a day before the change is implemented

**Comment by StevenBarre** [comment]
CHG0019238 created for Oct 27th at 9am.

**Comment by StevenBarre** [comment]
Notification PR https://github.com/BCDevOps/platform-services-status-page-notifications/pull/96

**Comment by StevenBarre** [comment]
Completed in Silver
