### ISSUE TITLE
OCP4 Web Console Asthetic Improvements

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#425]
**Describe the issue**
The web console should look different between each cluster. It should also have a useful `<title>` tag in the HTML.

**Additional context**
We can change the title tag with https://github.com/bcgov-c/platform-ops/blob/ocp4-base/ocp4/roles/web-console/tasks/main.yaml#L35

We can have a custom logo for each cluster.

We can add custom banners as we already do in LAB.

**Definition of done Checklist (where applicable)**
Add a title for each Cluster as shown in the attached images. Titles for LAB Clusters will be "KAMLOOPS LAB CLUSTER" and "CALGARY LAB CLUSTER". The ALT Text of the browser window should match the title of the concole. 

![GoldCluster.png](https://images.zenhubusercontent.com/5ae096c24b5806bc2bd09c0f/2f399b8d-fdf0-4bd4-b8b6-6780d7e03dc9)

![SilverCluster.png](https://images.zenhubusercontent.com/5ae096c24b5806bc2bd09c0f/844095e1-e8b2-4842-8494-2bcc32ea3934)

**Comment by StevenBarre** [comment]
I think the best way to get what you are looking for is to just make that logo image really wide with the color and title in it.

We can only make changes in the ways supported by the operator. See the docs for all the options https://docs.openshift.com/container-platform/4.6/web_console/customizing-the-web-console.html

We should also look at maybe adding some links to docs to the little tick-tac-toe icon on the top right. Perhaps the dev hub?

Our previous discussions were in https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/88

**Comment by StevenBarre** [comment]
https://www.openshift.com/blog/blog-openshift-console-customization

**Comment by StevenBarre** [comment]
@mitovskaol is someone going to generate the images for me? I'm not much of a designer.

Did we make any decisions about extra links to add? Maybe to the dev hub?

**Comment by mitovskaol** [comment]
If I remember correctly  @sbathgate  volunteered to help with the images. In terms of the links, lets make the BCDevExchange logo clickable and point to DevHub.

**Comment by StevenBarre** [comment]
>lets make the BCDevExchange logo clickable

As stated before:

>We can only make changes in the ways supported by the operator. See the docs for all the options https://docs.openshift.com/container-platform/4.6/web_console/customizing-the-web-console.html
>
>We should also look at maybe adding some links to docs to the little tick-tac-toe icon on the top right.

**Comment by sbathgate** [comment]
I can put something together for you. Wouldn't consider myself a designer but I can make something up in Photoshop that should work.

**Comment by StevenBarre** [comment]
Proposed solution is to use the banner thingy.

```yaml
apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: kamloops-silver-cluster
spec:
  text: "KAMLOOPS SILVER CLUSTER |"
  location: BannerTop
  link:
    href: 'https://developer.gov.bc.ca'
    text: DevHub
  color: '#000'
  backgroundColor: '#C0C0C0'
```

Other cluster colors are

- ![](https://via.placeholder.com/300x35/C0C0C0/000000?text=KAMLOOPS+SILVER+CLUSTER) SILVER #C0C0C0 / #000000
- ![](https://via.placeholder.com/300x35/FF0000/FFFFFF?text=KAMLOOPS+LAB+CLUSTER) KLAB #FF0000 / #FFFFFF
- ![](https://via.placeholder.com/300x35/FFD700/000000?text=KAMLOOPS+GOLD+CLUSTER) Gold #FFD700 / #000000
- ![](https://via.placeholder.com/300x35/A38A00/000000?text=CALGARY+GOLD+DR+CLUSTER) GoldDR #A38A00 / #000000
- ![](https://via.placeholder.com/300x35/FFC0CB/000000?text=CALGARY+LAB+CLUSTER) CLAB #FFC0CB / #000000 
- ![](https://via.placeholder.com/300x35/00D100/000000?text=KAMLOOPS+LAB+CLUSTER+NSXT) KLAB2 #00D100 / #000000

**Comment by StevenBarre** [comment]
@mitovskaol Looks like we also need a colour chosen for GOLDDR / Calgary Gold Cluster

**Comment by StevenBarre** [comment]
PR is ready to merge for SILVVER https://github.com/bcgov-c/platform-gitops-kamloops-silver/pull/15/files

I don't think we need a CHG for this do we? or a post in the alerts channel?

**Comment by mitovskaol** [comment]
@sbarre-esit it is a minor chage, so just a post in #devops-alerts should be sufficient

**Comment by StevenBarre** [comment]
Merged and tested in SILVER. Will close this now and revisit once more clusters get into CCM to get their colors.

**Comment by j-pye** [comment]
> @mitovskaol Looks like we also need a colour chosen for GOLDDR / Calgary Gold Cluster?

Just following up on this. Making a diagram and it would be helpful to have the right color for GoldDR :)

**Comment by mitovskaol** [comment]
@j-pye  We will go with  #FFD700 for Gold.

**Comment by StevenBarre** [comment]
@mitovskaol Calgary GOLD DR should be a different color than Kamloops GOLD though?

**Comment by mitovskaol** [comment]
@sbarre-esit How about we show a thin red horizontal strip on the top of the Gold DR banner (the banner colour will be gold as in Gild cluster)?

**Comment by StevenBarre** [comment]
@mitovskaol that is not something the `ConsoleNotification` object supports. As shown above it only accepts values for text, text color, and background color.

**Comment by mitovskaol** [comment]
What do you think of darker gold color #A38A00?

**Comment by StevenBarre** [comment]
![](https://via.placeholder.com/300x35/A38A00/000000?text=CALGARY+GOLD+DR+CLUSTER) Works for me
