### ISSUE TITLE
Move Trident to new namespace

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#426]
**Describe the issue**
OCP4 comes with a bunch of great built in monitoring, but a bunch of it only monitors namespaces prefixed with `kube-` or `openshift-` . We should move important ops things we want on-call teams to respond to into namespaces with those prefixes.

**Which Sprint Goal is this issue related to?**
TBD

**Additional context**
Aporeto will also need to be updated to go with this change

**Definition of done Checklist (where applicable)**
TBD

**Comment by j-pye** [comment]
@sbarre-esit are we aiming for next sprint for this ticket? 

Aporeto upgrade ticket that will include the added exclusion of the new trident namespace from enforcement.
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/430

**Comment by StevenBarre** [comment]
I had no particular sprint in mind. Just wanted to get the idea out of my head and into a ticket before I forgot.

Should we call the namespace `openshift-trident` or `openshift-advsol-trident` and put some of our other stuffs into `openshift-advsol-*` namespaces? Other stuffs wouldn't need Apo changes mind you.

**Comment by StevenBarre** [comment]
Working in Draft PR https://github.com/bcgov-c/platform-ops/pull/346 on the namespace rename to `openshift-bcgov-trident`. Justin has updated the Apo policy in KLAB and I cycled all the enforcers.

I discovered some gotchas with namespace renaming and operators and am working to make a playbook to properly handle migrating all the CRs needed.

**Comment by StevenBarre** [comment]
Testing stalled waiting for Apo to be re-installed in KLAB. Currently it has some reconcile issues with the trident namespace in OCP, vs the CRs in the apo namespace, and the objects in the cloud backend. This is preventing creation of trident related namespaces.

**Comment by StevenBarre** [comment]
Moving to Blocked until the Aporeto Enforcers can be restarted.

**Comment by StevenBarre** [comment]
Completed via
CHG0022281 MCS SILVER - Move and Upgrade Trident to v20.10.1
