### ISSUE TITLE
CCM: Upgrade ArgoCD

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/OpenShift4-RollOut#429]
We need to move to a more controllable ArgoCD deployment so that we can tune and upgrade ArgoCD as needed

ArgoCD Changelog:
https://github.com/argoproj/argo-cd/blob/master/CHANGELOG.md

Definition of Done:
- [x] Playbook written for removing ArgoCD operator
- [x] CCM ArgoCD role upgraded to support ArgoCD 2.0.1 
- [x] CCM ArgoCD role upgraded to support a fresh install without the operator
- [x] Upgrade process tested and documented

Tracking rollout here : https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1252

**Comment by StevenBarre** [comment]
> Starting in OpenShift Container Platform 4.6, the Red Hat-provided default catalogs used by Operator Lifecycle Manager (OLM) and OperatorHub are now shipped as index images specific to the minor version of OpenShift Container Platform. This allows Operator providers to ship intentional ranges of Operator versions per cluster version.

https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-operator-catalogs-per-version

Will the new ArgoCD version work on OCP 4.6? Does this upgrade need to happen BEFORE we can upgrade OCP?

**Comment by j-pye** [comment]
Base Upgrade PR: https://github.com/bcgov-c/platform-gitops-gen/pull/175
Misc fixes after testing in KLAB: https://github.com/bcgov-c/platform-gitops-gen/pull/176
