### ISSUE TITLE
Validate cluster availability for Dev / Apps for Silver Cluster

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#43]
Platform Services confirmed:

- [ ] Artifactory Image Pull Through
- [ ] Artifactory Private Repositories
- [ ] bcgov managed images
- [ ] openshift managed images?
- [ ] project provisioning
- [ ] Network Security Policies (aporeto operator)

**Comment by mitovskaol** [comment]
This has been implemented as Silver cluster MVP.
