### ISSUE TITLE
OpenShift 4.6 Upgrade

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#431]
**Describe the issue**
This is an EPIC to track all the sub tasks needed to get all the clusters updated to 4.6. Subsets of these tasks can be added to Sprint Goals as we worth through this work which may take several sprints.

**Additional context**
- [Release Notes](https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html)
- [What's New Webinar](https://youtu.be/0ZyPHC-7V_0) and [slides](https://speakerdeck.com/redhatopenshift/whats-new-in-openshift-container-platform-4-dot-6)

**Comment by wmhutchison** [comment]
Closing off this Epic since remaining tasks were not technically part of an upgrade process but more akin to activities that can take place once you have upgraded to 4.6.
