### ISSUE TITLE
OCP4.6 - New Ignition version spec

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#432]
**Describe the issue**
OCP 4.6 moves to [Ignition v3](https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-ignition-spect-updated-v3). 

Migration guide: <https://coreos.github.io/ignition/migrating-configs/#from-version-230-to-300>

**Which Sprint Goal is this issue related to?**

**Definition of done Checklist (where applicable)**
- [x] Does this impact the existing Machine Config ? NO - MACHINE CONFIG OPERATOR IS BACKWARDS COMPATIBLE
- [ ] Are any changes needed to the [install playbooks](https://github.com/bcgov-c/rhcos-ignition-builder)?

**Comment by wmhutchison** [comment]
When using openshift-install binary to create bootstrap for the BOOTSTRAP VM, the written Ignition for OCP4.6 is version 3.1.0.

**Comment by wmhutchison** [comment]
Closing this off as no longer needed - has been superceded by https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1553
