### ISSUE TITLE
Update Cluster Metering Operator

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#434]
**Describe the issue**
As was previously done for [Cluster Logging](https://github.com/bcgov-c/platform-ops/pull/301) the Cluster Metering operator does not auto upgrade with OCP and so needs Ansible code to manage that upgrade path.

**Which Sprint Goal is this issue related to?**

**Definition of done Checklist (where applicable)**
- [ ] PR for ansible playbook to upgrade Cluster Metering
- [ ] Test in labs
- [ ] Create a CHG for SILVER to upgrade CM to 4.5
- [ ]  Perform upgrade in SILVER

**Comment by StevenBarre** [comment]
@jefkel @mitovskaol We installed the Cluster Metering operator back in [265](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/265), but haven't done any work to operationalize it. Thoughts on just removing it for now until we have the cycles to revisit figuring out what it does and if it has any use to us beyond just consuming memory and disk space?

**Comment by mitovskaol** [comment]
@stewartshea @jefkel  Unless we have an immediate need for the Operator, I suggest removing it until we figure out an overall approach to monitoring the Platform - what gets monitored , what tools are used for this and what kind of dashboards get created

**Comment by StevenBarre** [comment]
It is now [deprecated](https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-metering-operator-deprecated) in OCP 4.6. Guess I'll remove it then.

**Comment by StevenBarre** [comment]
Opened another [ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/453) to track the removal. Closing this ticket.
