### ISSUE TITLE
OCP4.6 - Operator upgrades BEFORE cluster upgrade

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#435]
**Describe the issue**
[Important Operator upgrade requirements](https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-operator-catalogs-per-version)

> Starting in OpenShift Container Platform 4.6, the Red Hat-provided default catalogs used by Operator Lifecycle Manager (OLM) and OperatorHub are now shipped as index images specific to the minor version of OpenShift Container Platform. This allows Operator providers to ship intentional ranges of Operator versions per cluster version.

> Cluster administrators must ensure all Operators previously installed through Operator Lifecycle Manager (OLM) are updated to their latest versions in their latest channels before upgrading to OpenShift Container Platform 4.6.

**Which Sprint Goal is this issue related to?**

**Additional context**
Currently installed Operators
- ArgoCD (has a [ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/429) for update already)
- Cluster Application Migration Operator
- Cluster Logging
- Elasticsearch Operator
- Metering ( has a [ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/434) already)
- Package Server
- Prometheus Operator (for ArgoCD)

**Definition of done Checklist (where applicable)**
- [x] Determine which Operators need manual intervention for upgrades before the cluster can be upgraded
- [x] Document the upgrade procedure for those Operators
- [x] If reasonable, automate with Ansible the upgrade

**Comment by mrobson** [comment]
comment

**Comment by StevenBarre** [comment]
@mrobson we've already upgraded ES to elasticsearch-operator.4.5.0-202010161522.p0 and CL to clusterlogging.4.5.0-202010161522.p0 . Do any of our other operators need an upgrade before moving to 4.6?

**Comment by StevenBarre** [comment]
Confirmed that all our operators are sufficiently new to upgrade OCP.
