### ISSUE TITLE
OCP4.6 - Document developer facing changes

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#436]
**Describe the issue**
Document what is new for developers and present a quick overview at the Nov 10th Sprint Review.

**Which Sprint Goal is this issue related to?**
SG - OCP 4 - Sprint 19 Platform Hot Fixes

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] Documentation of new features
- [x] Presentation at Sprint Review

**Comment by StevenBarre** [comment]
Customize columns on resource pages https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-web-console-column-management

Changes to the Developer Perspective https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-web-console-developer-perspective

**Comment by StevenBarre** [comment]
Monitoring user-defined projects https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-monitoring-for-user-defined-projects

**Comment by StevenBarre** [comment]
https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-notable-technical-changes

**Warnings when using deprecated APIs**

Warnings are now visible in client-go and oc on every invocation against a deprecated API. Calling a deprecated API returns a warning message containing the target Kubernetes removal release and replacement API, if applicable.

For example:

```
warnings.go:67] batch/v1beta1 CronJob is deprecated in v1.22+, unavailable in v1.25+
```

This is new functionality included with Kubernetes 1.19.

**COPY and ADD build instructions improved**

The performance of COPY and ADD instructions in OpenShift Container Platform builds are improved. The initial implementation of COPY and ADD instructions in buildah had noticeable performance regressions compared to docker. With this enhancement, builds now run more quickly, especially with large source repositories. ([BZ\#1833328](https://bugzilla.redhat.com/show_bug.cgi?id=1833328))

Previously, the logic that handled COPY or ADD instructions for copying content from the build context did not efficiently filter when a `.dockerignore` file was present. COPY and ADD would be noticeably slowed by the cumulative overhead of evaluating whether each item in the source location needed to be copied to the destination. This bug fix rewrote the logic and the presence of a `.dockerignore` file will no longer noticeably slow the speed at which COPY and ADD instructions are handled during a build. ([BZ\#1828119](https://bugzilla.redhat.com/show_bug.cgi?id=1828119), [BZ\#1813258](https://bugzilla.redhat.com/show_bug.cgi?id=1813258))

**Jenkins Node.js agent upgrade**

The default Jenkins Node.js agent has been upgraded to Node.js version 12.

**Comment by StevenBarre** [comment]
All [MongoDB](https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-mongodb-removed) sample templates and images have been removed. @jleach

**Comment by jleach** [comment]
> All [MongoDB](https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-mongodb-removed) sample templates and images have been removed. @jleach

The notes say "All MongoDB-based samples have been replaced, deprecated, or removed." Have you confirmed they were removed?

**Comment by StevenBarre** [comment]
@jleach I haven't confirmed anything. Just reading the Release Notes. Once we get a LAB upgraded we can confirm.

**Comment by StevenBarre** [comment]
Created a PowerPoint of all the changes noted above.

**Comment by StevenBarre** [comment]
Closing as I'll be demoing this today.
