### ISSUE TITLE
OCP4.6 - Configure OAuth Token timouts

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#438]
**Describe the issue**
The OAuth server provides tokens to use for logging in via the CLI and browser. The lifespan of these tokens is adjustable. New in 4.6 is [inactivity timeouts](https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-oauth-token-inactivity-timeout). We need to work with the security team to determine appropriate timeouts.

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] Determine correct value for [token duration](https://docs.openshift.com/container-platform/4.6/authentication/configuring-internal-oauth.html#oauth-configuring-internal-oauth_configuring-internal-oauth) Default: 24h
- [x] Determine correct value for default [inactivity timeout](https://docs.openshift.com/container-platform/4.6/authentication/configuring-internal-oauth.html#oauth-token-inactivity-timeout_configuring-internal-oauth) Default: none
- [x] Determine correct values for individual [OAuth Client inactivity timeouts](https://docs.openshift.com/container-platform/4.6/authentication/configuring-oauth-clients.html#oauth-token-inactivity-timeout_configuring-oauth-clients)
- [x] If changes are needed, create playbooks to implement
- [x] Test changes in LAB
- [x] Promote changes to SILVER

**Comment by NickCorcoran** [comment]
Began consult w/ OCIO ISB on suggested token lifespans.

**Comment by NickCorcoran** [comment]
For the default token value, I don't see a standard or recommended duration.  I suggest we set to 18 hrs and see how that goes.

For the inactivity timeouts:
https://www2.gov.bc.ca/assets/gov/government/services-for-government-and-broader-public-sector/information-technology-services/standards-files/05_-_access_control_security_standard_v10pdf.pdf
- indicates: "The session must be terminated or require re-authentication after a period of no more than 15 minutes of inactivity."
- suggest we try that and adjust if necessary. 

**Summary:**
Determine correct value for token duration: 18 hrs
 Determine correct value for default inactivity timeout Default: 15 mins
 Determine correct values for individual OAuth Client inactivity timeouts: 15 mins

**Comment by NickCorcoran** [comment]
@sbarre-esit - can you help with playbook creation?  I have never done this before.

**Comment by StevenBarre** [comment]
Yup, I'll take it from here.

**Comment by StevenBarre** [comment]
@NickCorcoran I can confirm that 15m timeouts in the browser is a real pain in the butt :P

**Comment by StevenBarre** [comment]
Blocked on the 2021Q2 Silver upgrade CHG

**Comment by StevenBarre** [comment]
Completed via CHG0025038 - MCS SILVER - 2021 Q2 Patching - Upgrade to OCP 4.6.21
