### ISSUE TITLE
OCP4.6 - Update Aporeto Policy

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#440]
**Describe the issue**
OCP4.6 add some new `openshift-*` namespaces. Test the tools installed in those NS to see if they need to be excluded by Aporeto policy, or if we can write them some custom NSP rules.

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [ ] Determine list of new namespaces
- [ ] Test if each of them need any Aporeto policy changes in LAB
- [ ] Deploy new policy rules to be picked up by SILVER when the nodes reboot during the upgrade
- [ ] Verify namespaces are working successfully after upgrade

**Comment by j-pye** [comment]
Add `openshift-oauth-apiserver` to excluded namespaces

**Comment by j-pye** [comment]
The aporeto service is being removed in from the platform and will not be installed in OCP4.6. Closing.
