### ISSUE TITLE
OCP4.6 - Rebuild Nagios Ops Tool

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#444]
**Describe the issue**
The [Nagios](https://github.com/bcgov-c/platform-tools/tree/ocp4-base/ocp4/nagios) image is built on the clusters cli image and should be rebuilt as part of the upgrade.

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] Rebuild the nagios container image
- [x] Deploy to LAB and test
- [x] Deploy to SILVER

**Comment by wmhutchison** [comment]
Moving to Backlog for now  - we need to get a successful 4.6 upgrade completed first.

**Comment by StevenBarre** [comment]
Blocked on the 2021Q2 Silver upgrade CHG

**Comment by StevenBarre** [comment]
Completed by CHG0025038 - MCS SILVER - 2021 Q2 Patching - Upgrade to OCP 4.6.21
