### ISSUE TITLE
OCP4.6 - Rebuild the Pruner Ops Tool

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#445]
**Describe the issue**
The build and deployment [pruner](https://github.com/bcgov-c/platform-tools/tree/ocp4-base/ocp4/pruner) image is built on the clusters cli image and should be rebuilt as part of the upgrade.

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] Rebuild the pruner container image
- [x] Deploy to LAB and test
- [x] Deploy to SILVER

**Comment by wmhutchison** [comment]
Will review once KLAB reaches a completely successful upgrade state regarding 4.6 upgrade.

**Comment by StevenBarre** [comment]
Blocked on the 2021Q2 Silver upgrade CHG

**Comment by StevenBarre** [comment]
Completed by CHG0025038 - MCS SILVER - 2021 Q2 Patching - Upgrade to OCP 4.6.21
