### ISSUE TITLE
Order Servers for Kamloops Lab

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#45]
VM Hosts ordered for the Kamloops Lab cluster, tracking delivery and availability here:

- [x] iStore submitted for 14 VMs (part of large initial VM order)
- [x] 1 x VM delivered (bootstrap small host)
- [x] 10 x VMs delivered (3 masters, 3 infra, 4 app)

**Comment by jefkel** [comment]
Pending confirmation of VMs from @sbarre-esit

**Comment by tosazuwa** [comment]
@sbarre-esit , could you confirm these orders please?

**Comment by jefkel** [comment]
VMs confirmed, just holding ticket open until network provisioning is completed (to be able to begin the provision tasks)

**Comment by StevenBarre** [comment]
Progress!
![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/94a066de-7f75-45be-b0f5-9a997046b719)

**Comment by StevenBarre** [comment]
Storage vlan completed
