### ISSUE TITLE
OCP4.6 - Update Log Forwarding

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#450]
**Describe the issue**
OCP 4.6 makes the [LogForwarding CR](https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-logging) generally available. We need to set it up again and ensure logs are being properly forwarded to the SIEM Hadoop cluster.

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] PR to add LogForwarding object that sends logs to SIEM
- [x] Test in LAB
- [x] Confirm with SIEM team they are getting the logs and they are properly formatted
- [x] Verify [audit logs](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/419) are being captured
- [ ] Apply to SILVER

**Comment by StevenBarre** [comment]
Added to https://github.com/bcgov-c/platform-ops/pull/351 and tested in CLAB

**Comment by StevenBarre** [comment]
Blocked awaiting @NickCorcoran confirming Audit logs are being captured

**Comment by NickCorcoran** [comment]
Audit logs are captured by SIEM.
