### ISSUE TITLE
OCP4.6 - Confirm new Insight Data Collection metrics are acceptable

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#452]
**Describe the issue**
OCP4.6 adds some [new metrics](https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-insights-operator-data-collection-enhancements) to the telemetry sent back to Red Hat. Need to confirm there are no issues with this.

**Which Sprint Goal is this issue related to?**

**Additional context**
The two that jump out at me are

- The latest pod logs from pods that are not healthy
- JSON dumps for pods that have crash looping containers

It is unclear to me if these are for just operations namespaces, or tenant namespaces.

**Definition of done Checklist (where applicable)**
- [x] Have Nick sign off on keeping telemetry enabled
OR
- [ ] Adjust ansible playbooks to disable telemetry

**Comment by NickCorcoran** [comment]
- [x] Ask RH what namespaces JSON dumps apply to for this purpose.
- [x] inspect JSON dumps for an app in Lab once 4.6 is up there.  Then we can make the call whether to keep enabled or not.

**Comment by StevenBarre** [comment]
Emailed @NickCorcoran some JSON dumps from KLAB

**Comment by NickCorcoran** [comment]
JSON dumps reviewed.  Content acceptable to send to RedHat.
