### ISSUE TITLE
Create a new URL for RocketChat

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-RollOut#454]
Please create a new subdomain `chat.developer.gov.bc.ca` and use a CNAME to point it at `chat.pathfinder.gov.bc.ca`. I will do some testing to make sure the redirection work with Web, Desktop and Mobile clients. This will be a preliminary step on the way to RC migration to the Silver OCP4 cluster.

**Comment by StevenBarre** [comment]
Done!
