### ISSUE TITLE
Integrate Vault and Terraform Cloud into Project Registry Provisioner

### ISSUE THREAD

**Issue by manderson-it** [BCDevOps/OpenShift4-RollOut#457]
**Describe the issue**
The Platform Registry Provisioning Tool must be able to communicate with the appropriate Terraform Cloud Workspaces through the lab and prod vault terraform repositories. The Terraform Cloud Workspace will subsequently provision the Vault artifacts into Vault, e.g., Vault Policies, etc.

**Additional context**
Requires changes to the Platform Registry Provisioning Container Image.

**Definition of done**
- [x] Platform Registry Provisioning Container Image adapted to communicate with Terraform Github Repositories for Vault
- [x] End-to-end test, meaning Platform Registry Provisioner deploys Vault artifacts into Vault

**Comment by j-pye** [comment]
Testing in LAB was successful. Vault was Rolled into prod on July 6th @ 1PM. Registry Sync on Prod has been started and this ticket will be closed once success is confirmed.
