### ISSUE TITLE
Publish and Test Terraform Cloud Module for Vault Resources

### ISSUE THREAD

**Issue by manderson-it** [BCDevOps/OpenShift4-RollOut#458]
**Describe the issue**
Modules in Terraform Cloud require a connection to a GitHub organization. Each Terraform Module has to be in its own GitHub repository conforming to the Terraform naming convention, e.g., **terraform-vault-resources**

**Additional context**

**Definition of done**
- [ ] Terraform Cloud Organization is connected to the GitHub organization
- [ ] Terraform Cloud can consume Terraform modules from a specified GitHub repository

**Comment by j-pye** [comment]
@manderson-it Think we can close this since we're no longer using TF Cloud for the modules portion.

**Comment by manderson-it** [comment]
@j-pye agreed, this has changed in the Terraform module is now cloned inside the GitHub Actions container. Closing.
