### ISSUE TITLE
Create GitHub repository for Terraform Cloud

### ISSUE THREAD

**Issue by manderson-it** [BCDevOps/OpenShift4-RollOut#459]
**Describe the issue**
Terraform Cloud is backed by GitHub repositories to enforce the GitOps approach.
At least three GitHub repositories are required:
- One for the lab environment
- One for the production environment
- One for the Terraform Module, which is used to provision the initial resources to Vault for a new OpenShift project. This GitHub repository must follow the Terraform naming convention **terraform-PROVIDER-NAME**, e.g., **terraform-vault-resources**

**Additional context**

**Definition of done**
- [x] All three GitHub repositories are created
- [x] The GitHub repository for the Terraform module must follow the naming convention **terraform-PROVIDER-NAME**, e.g., **terraform-vault-resources**

**Comment by j-pye** [comment]
These three github repositories have been created as apart of our private org. 

terraform-vault-module
terraform-vault-lab
terraform-vault-prod

Closing ticket.
