### ISSUE TITLE
Please create an additional DNS entry for dev and test RC instances

### ISSUE THREAD

**Issue by jleach** [BCDevOps/OpenShift4-RollOut#463]
Please add an additional DNS CNAME records pointing:

`dev.chat.developer.gov.bc.ca` to `chat-dev.pathfinder.gov.bc.ca`.
`test.chat.developer.gov.bc.ca` to `chat-test.pathfinder.gov.bc.ca`.

**Comment by ShellyXueHan** [comment]
this is for earlier when migrating RC to OCP4. Ticket already done, closing
