### ISSUE TITLE
Aporeto pod count monitoring

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/OpenShift4-RollOut#475]
**Describe the issue**
Create a custom script to monitor that the number of running Aporeto pods and compare to the number of nodes in the cluster and if the numbers do not match, raise an alarm.

**Which Sprint Goal is this issue related to?**
Aporeto Monitoring

**Additional context**
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/261

**Definition of done Checklist (where applicable)**
- [x] Tested on KLAB
- [x] Deployed to SILVER

**Comment by StevenBarre** [comment]
Started messing with my Nagios/Ansible pod again and ran into a bug. https://github.com/openshift/openshift-restclient-python/issues/389

**Comment by StevenBarre** [comment]
Will resume work in the new year.

**Comment by StevenBarre** [comment]
PR https://github.com/bcgov-c/platform-tools/pull/24

I might rewrite this from bash to ansible in the future, but it's a start!

**Comment by StevenBarre** [comment]
@mitovskaol this is now deployed to SILVER. We'll be adding some additional monitoring under other tickets.

**Comment by mitovskaol** [comment]
thank you for awesome new @sbarre-esit it will definitely help me sleep better at night :)
