### ISSUE TITLE
Deploy OpenShift 4 on Virtuals in Kamloops Lab

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#48]
- [x] Deploy OCP
- [x] Configure storage (This is mostly working, issues are being tracked in #50)
- [x] Configure authentication
- [x] Confirm all 3 LB access points are working (api, api-int, *.apps)

**Comment by StevenBarre** [comment]
Working on docs for setup of auth and moving stuff to Infra nodes. More research needed on moving all components possible to infra.

Working on creating machine configs to set needed config for NetApp integration.

**Comment by StevenBarre** [comment]
Discovered that the clusters APIs are not accessible from outside the datacenter. Opened an INC with networks to investigate.

**Comment by StevenBarre** [comment]
Wrote a playbook to configure the infra nodes, instead of doing it by hand.

Wrote a playbook to generate the MachineConfig files and apply them, instead of doing it by hand.

**Comment by StevenBarre** [comment]
Calling this done for now and tracking further work in other tickets.
