### ISSUE TITLE
OCP GOLD - Configure Nagios monitoring for the cluster

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/OpenShift4-RollOut#482]
**Describe the issue**
Automation currently exists in the form of an image which when build/provisioned, allows us to configure agentless monitoring for all available Openshift nodes within the cluster said image is ran on.

The DXC tools team has re-issued APIs for use with Nagios going forward, and thus will require us to first update the repo with new vault values.

**Which Sprint Goal is this issue related to?**

**Additional context**
Location of Nagios image and instructions on how to install: https://github.com/bcgov-c/platform-tools/tree/ocp4-base/ocp4/nagios

**Definition of done Checklist (where applicable)**
- [x] Create PR to update repo with new Nagios API.
- [x] Deploy Nagios into `advsol-nagios` project
- [x] If necessary due to adding remaining APP nodes, re-run configured job.

**Comment by StevenBarre** [comment]
9 gold hosts in Nagios.

**Comment by StevenBarre** [comment]
Done
