### ISSUE TITLE
OCP GOLD - Complete cluster configuration using CCM

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/OpenShift4-RollOut#483]
**Describe the issue**
CCM will be used to complete configuration of the GOLD cluster. That includes core support software like Aporeto and Sysdig, as well as configuring oauth services and other configurations already delegated to CCM.

The goal is that unless needed for the initial cluster build, configuration work for the cluster should be handled via CCM.

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] Install ArgoCD
- [x] setup CCM environment specific to GOLD cluster
- [x] apply CCM configuration against GOLD cluster
- [x] confirm all operations post-config

**Comment by StevenBarre** [comment]
Docs reviewed and followed to install CCM in Gold.

GOLD is having issues with SSH to GitHub, as we've had with other clusters. I've entered a ticket for the network team, but CCM will be in a semi working state in GOLD until that is resolved.

Moving to Blocked until SSH is fixed.

**Comment by StevenBarre** [comment]
SSH Fixed. Made a few more tweaks to CCM gen repo to get things nice and smooth.
