### ISSUE TITLE
OCP KLAB2 - IP address reservations and DNS

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/OpenShift4-RollOut#485]
**Describe the issue**
IP addresses need to be assigned to the new VMs for the KLAB2 cluster. 

VRA will be used to handle the IP address reservations and non-PROD DNS, and NNR will be used to create the production (DMZ domain) DNS entries.

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] use VRA to reserve IP addresses for all PROD and MGMT IP addresses for new nodes and DNS for MGMT.
- [x] use NNR to create DNS entries for PROD IPs
- [x] use NNR to complete setup of additional records (SRV records, etc)

**Comment by wmhutchison** [comment]
Adding Tim Baker since he is working on this now, and moving into "In progress".

**Comment by tbaker1313** [comment]
This is completed. DNS and IP addresses have been assigned.
