### ISSUE TITLE
OCP KLAB2 - Prepare KLAB2 node inventory files

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/OpenShift4-RollOut#489]
**Describe the issue**
As part of the preparation for building out the KLAB2 cluster, we will need to prepare the YAML inventory files used to prepare both the TFTP/DHCP configuration as well as create suitable Ignition files on the UTIL server to allow bootstrapping of all the involved nodes.

**Which Sprint Goal is this issue related to?**

**Additional context**

**Definition of done Checklist (where applicable)**
- [x] check provisioned VMs to derive MAC addresses
- [x] create suitable GitHub PR designating all of the required inventory files populated with MAC address data.

**Comment by tbaker1313** [comment]
This is completed and PR is ready for promotion.
