### ISSUE TITLE
Configure F5 MVP in Kamloops Lab

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#49]
Per the [F5 vs HAProxy Recommendation](https://github.com/BCDevOps/OpenShift4-RollOut/blob/master/docs/F5-vs-HAProxy.md) the F5 just needs to be automated for CRDs for non-http traffic. CRD support is currently [ALPHA](https://github.com/F5Networks/k8s-bigip-ctlr/blob/master/docs/_static/config_examples/crd/CustomResource.md) in CIS 2.1 and only supports HTTP and HTTPS.

The F5 then also needs static config for the api, internal api, and apps VIPS as well as act as a NAT router for all traffic from the OCP nodes.

- [x] Create VIPs for `api`, `api-int`, and `*.apps`
- [x] Create NAT gateway
- [x] Configure VXLAN and integrate with OCP
- [x] Test CRD support

**Comment by StevenBarre** [comment]
Started work on this with John from ATT. Followed the directions but traffic is not passing from the F5 to the pods currently.

Blocked waiting on John to have time for us amongst his other priorities.

Suggested next step is for Todd to talk to Stuart Restall about the priority and deadlines of this project so Stuart can pass that info back onto the network team to properly prioritize this work.

**Comment by tosazuwa** [comment]
@sbarre-esit worked with F5 support and got one route working. Call with F5 team to understand how the routes work and ingress services

**Comment by StevenBarre** [comment]
Call with F5 helped understand the way HA works and some of the underlying networking.

Tested using a configmap to create a virtual server to expose Postgresql https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-create-service-vs.html

Next steps are to understand how that can be safely used in a multi-tenant environment.

**Comment by StevenBarre** [comment]
Joined the F5 Slack. Asking for assistance with a route using custom TLS certs not working. Asking for guidance on using Virtual Servers with Services in a multi-tenant environment.

**Comment by StevenBarre** [comment]
Had a meeting this week with @stregear and ATT to discuss where we are and where we are going. Wrote up a scope/requirements docs for Sharon.

**Comment by StevenBarre** [comment]
Marking as Blocked while I wait for more support from F5. Apparently we're getting some Professional Services ordered.

**Comment by StevenBarre** [comment]
Have had a few discussions with the F5 vendor about scaling and config and their docs lacking in detail.

Have switched to using the AS3 agend instead of the CCCL agent which has improved my luck with using TLS certs on routes.

Have now run into more issues but haven't heard back in a week. Followed up with an email. There are hints that CiS doesn't currently support having multiple services with the same name, which could be a show stopper.

**Comment by StevenBarre** [comment]
Opened https://github.com/F5Networks/k8s-bigip-ctlr/issues/1281

Had some discussions with Mark on Slack about our issue and tried out a nightly build.

Having a call with Mark and some devs tomorrow at 8am

**Comment by StevenBarre** [comment]
My GH issue should get fixed in CIS 2.1

**Comment by StevenBarre** [comment]
KLAB is going to be redeployed to SDN Compartment where we can continue testing.

**Comment by mitovskaol** [comment]
Waiting for transivers for F5, the quotes are with Finance for review and approval. @stregear  will find out what the next step is going to be and an ETA.

**Comment by StevenBarre** [comment]
KLAB F5 is up and running in SDN compartment. Basic cluster install tested with default VIPs.

Todo: Configure CIS and test non-http VIPs

**Comment by StevenBarre** [comment]
Per https://github.com/BCDevOps/OpenShift4-RollOut/blob/master/docs/F5-vs-HAProxy.md we are moving away from leveraging the F5 for HTTP(S) traffic and just using the CRDs for non-http traffic.

# Old description

Verifying the following functionality is available and configurable by our cluster-admins (some provisioning activities to be automated at a later date)

- [x] Configure incoming VIP for OCP router services (ie: cluster default port 80/443)
- [ ] Test HTTP2 support
- [x] Configure/manage outgoing NAT pool for all cluster hosts
- [ ] Configure individual incoming VIP to route directly to OCP service (potentially non-standard ports)
  - [ ] direct (no SSL)
  - [ ] Edge terminated
  - [ ] Re-encrypt
  - [ ] Passthrough

After access and initial testing confirmed:

- [x] Final decision (from DXC) on F5 Target hardware:
  * Use F5 vCMP on existing hardware
  * BCGov required to procure additional F5 components (VMs and software?)

**Comment by StevenBarre** [comment]
> CRD from 2.1 supports TLS with profiles created on BIG-IP.
> We are targeting to support certificate saved in k8s secrets in 2.1.1 and GA would be 2.2

Created a test CRD in `steve-test` to expose an http service and it worked. Health monitor needs all its args supplied despite the docs saying some are optional. Though having a health check seems redundant.

```yaml
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: my-new-virtual-server
  namespace: steve-test
  labels:
    f5cr: "true"
spec:
  host: cafe.example.com
  virtualServerAddress: "1.2.3.4" # one of the IPs in the VIPRange
  pools:
  - path: /
    service: django-psql-example
    servicePort: 8080
    monitor:
      type: http
      interval: 5
      timeout: 10
      recv: ""
      send: /
```

```console
# curl --resolve cafe.example.com:80:1.2.3.4 http://cafe.example.com
<html of django sample app>
```

**Comment by StevenBarre** [comment]
MVP complete
