### ISSUE TITLE
Create detail architecture for Stage 1

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/OpenShift4-RollOut#5]
We need one more level of detail on the network diagram that includes the number of nodes and cores per stage.

**Comment by tosazuwa** [comment]
@jefkel @stewartshea, is this still a Sprint 0 deliverable?

**Comment by stewartshea** [comment]
I feel like this will be pushed to Sprint 1 due to time constraints this week @tosazuwa

**Comment by tosazuwa** [comment]
Sounds good

**Comment by tosazuwa** [comment]
Closing ticket #5 as its a duplicate for #44, #55, #33
