### ISSUE TITLE
Integrate DevSecOps Tools in Kamloops Lab

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#52]
Checklist for deployment of all 3rd party DevSecOps tools for Kamloops Lab.

- [ ]  Sysdig
- [ ]  Aporeto
    - [ ]  Host protection mode
    - [ ]  networksecuritypolicy operator
- [ ]  Aqua
- ... ?

**Comment by mitovskaol** [comment]
This work has been complete.
