### ISSUE TITLE
Order NetApp Licenses for Lab environments

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#58]
- [x] SCO for licenses approved
- [x] Order to vendor
- [x] Licenses Received
- [x] Licenses Applied

**Comment by DanDeane** [comment]
assigning over to Joe.

**Comment by jefkel** [comment]
Blocked (vacations)

**Comment by Joe-Craig** [comment]
SCO-188 Amend SCO-156 NetApps ONTAP Storage - Complete and sent to the contract office.

**Comment by Joe-Craig** [comment]
Still waiting for " SCO-188 Amend SCO-156 NetApps ONTAP Storage" to be signed off

**Comment by Joe-Craig** [comment]
Provinces contract office have returned the SCO requesting changes which will need to be approved and re-issued. Still unable to move to procurement.

**Comment by tosazuwa** [comment]
SCO 188 for the ONTAP Select licenses is now signed off and Bruce (DXC) is taking it to procurement. @Joe-Craig, please provide ETA for delivery

**Comment by jefkel** [comment]
Licenses for both Lab environments have been applied.
