### ISSUE TITLE
Create OCP 4 dependency map

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/OpenShift4-RollOut#6]
To create a Dependency Map  to allow the  team to visualize the critical cross-project dependencies throughout the duration of the project

- [x] Create dependency map highlighting current blockers/dependencies

**Comment by tosazuwa** [comment]
To confirm with @kelpisland if this artefact is needed

**Comment by tosazuwa** [comment]
Completed. Document is living and will updated regularly
