### ISSUE TITLE
Configure F5 integration for Calgary Lab

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#60]

**Comment by Joe-Craig** [comment]
F5 configuration should be complete in Calgary by 16th Sept 2020

**Comment by StevenBarre** [comment]
Building CLAB now and will test shortly.

**Comment by StevenBarre** [comment]
Tested NAT is working.
Tested VIPs are working (api, apps)

TODO Set up CIS and test.

**Comment by mitovskaol** [comment]
This has been completed as CLAB cluster MVP.
