### ISSUE TITLE
Configure NetApp devices for Calgary Lab

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#61]
- [x] Establish Cluster Name - MCS-CLAB-NETAPP
- [x] Order gear under #58
- [x] Plan network design
- [x] Reserve IP Addresses and DNS Names from Network Team
- [x] Storage Team - Download latest ONTAP firmware and install and configure
  - [x] Dan to deploy VMs
  - [x] Submit request for SMTP to Infrastructure Group
  - [x] Configure AutoSupport for HTTPS  (Firewall requests)
  - [x] Configure Timezone and NTP
  - [x] Create SVM for Trident/OpenShift
  - [x] Create SVM for CORP Login
  - [x] Create Aggregates on both nodes
  - [x] Configure Aggregate Delegation
  - [x] Disable FSID
  - [x] Configure NFS Protocol and NFS Data LIF
  - [x] Configure iSCSI Protocol and iSCSI Data LIFs on each node
  - [x] Add cluster to Unified Manager
- [x] Setup Trident on the cluster and test

**Comment by jefkel** [comment]
Removed blocker as expectation is to deploy using Trial licenses and destroy/re-deploy once permanent licenses are available.

**Comment by tosazuwa** [comment]
Virtual Servers and SAN for the KLAB and CLAB storage now moving forward. NetApp Virtuals to be deployed in LAB and handed off to the Storage team by Feb 7th 2020 

@sbarre-esit @DanDeane , can we check off activities (list above) as we complete them please?

**Comment by DanDeane** [comment]
required vlans are now in place as of last night and required firewall rules drop tonight.

**Comment by DanDeane** [comment]
Calgary Lab NetApp clusters deployed yesterday and handed over to our storage team to configure.

**Comment by StevenBarre** [comment]
Storage team has handed the cluster over to me to configure.

**Comment by StevenBarre** [comment]
This has been on the back burner while I finish testing the setup in KLAB #50

**Comment by StevenBarre** [comment]
Trident set up and configured. Basic testing complete and ran into the same issues as #50

**Comment by tosazuwa** [comment]
Refer to ticket #50 for update.  Still blocked

**Comment by StevenBarre** [comment]
Completed except for issue tracked in #186
