### ISSUE TITLE
Create detailed architecture for Calgary DR

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#66]

**Comment by mitovskaol** [comment]
The failover design is documented in [this ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1108) 
A separate ticket will be open to document network details for Gold Kamloops and Gold Calgary (DR) clusters in Documize.
