### ISSUE TITLE
Ship Servers for Calgary DR

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#67]
Repurposed hosts from last of OCP3.11 servers to be shipped to Calgary for the GoldDR cluster.

Minimum: 3 masters (128G RAM), 3 infra (256G RAM), 4 App (256G RAM) (App node count to be determined by capacity planning targets.)

All hosts to leverage internal SSD's taken from OCS nodes, and NetApp expected to be in-place for cluster build activities.

**Comment by StevenBarre** [comment]
My understanding was that Gold-DR is being built entirely from repurposed v3 hardware? @jefkel

**Comment by jefkel** [comment]
Yes, (not including NetApp though).  So this could change to "Ship Servers for Calgary DR?"
