### ISSUE TITLE
Board Legend - Do not move from this lane

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#7]
Sprints: 
- Sprints are tracked as milestones in zenhub 

EPIC: 
- Epics will be used to track a grouping of issues within a release (ie. Lab deployment in Calgary)

Labels: 
- Tech labels 
- Environment Labels 

Releases: 
- There are 3 major states of this deployment, they will be releases.

**Comment by mitovskaol** [comment]
This info will be included in ZenHub Etiquette that @lukegonis  is working on.
