### ISSUE TITLE
Deploy OpenShift 4.2 on Virtual/Physical mix in Calgary DR

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#70]

**Comment by mitovskaol** [comment]
@wmhutchison Can you please have a look and close the ticket if this work has already been completed.

**Comment by wmhutchison** [comment]
Can be closed, tracking this via Epic https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1224
