### ISSUE TITLE
Create detailed architecture for Azure Pathfinder

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#77]
- [x] Review from team confirming vaules are correct. ( cpu, ram, node count, logging resources, etc)

**Comment by filiy** [comment]
This has been started but not fully finalized.

**Comment by filiy** [comment]
Sounds like we need to go through a proxy. Not sure if this will work with azure. GCP instructions are here. need to test.
https://docs.openshift.com/container-platform/4.2/installing/installing_gcp/installing-gcp-user-infra.html

**Comment by filiy** [comment]
need to update arch with logging info, elasticsearch count, size, etc.

**Comment by filiy** [comment]
Updated arch document, getting close to filling in all the details but will need some review.
