### ISSUE TITLE
Azure "Platform Services" Cluster Deployment

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#8]
The platform services team would like to run a small OpenShift cluster in a cloud target. This solution should be small but highly available and will host some of the platform services tools such as; 
- Rocket.Chat
- KeyCloak/SSO 
- Status Page 
- CI & CD Components

This cluster will provide the platform-services team with the ability to directly learn more about the OpenShift 4 platform and also decouples some of these services from the core production cluster in the event of a cluster outage.

**Comment by filiy** [comment]
Moving to backlog until update on cloud deployment direction.
