### ISSUE TITLE
Integrate ARO clusters to new SSO Realm

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#84]
Both ARO clusters have functioning integration to the Next Gen Security realm.  This needs to be re-pointed to the appropriate realm.

- [ ] Configure Realm client for pathfinder.aro cluster in `?xxx?` realm
- [ ] Update authentication configuration on pathfinder.aro cluster to use `?xxx?` realm.

--

- [ ] Configure Realm client for platform-services.aro cluster in `?xxx?` realm
- [ ] Update authentication configuration on platform-services.aro cluster to use `?xxx?` realm.

**Comment by mitovskaol** [comment]
This work will be tracked in new tickets once the work in ARO resumes
