### ISSUE TITLE
Determine Console Customizations

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#88]
The Web Console allows for a number of [customizations](https://docs.openshift.com/container-platform/4.2/web-console/customizing-the-web-console.html). As a user of the platform, it would be nice to see in the webui distinguishable differences for each web console outside of the FQDN. Currently we have a "red" banner for the lab environment, and in this case we could extent the configuration further. 

- [ ] Branding: colours / logos / site information
- [ ] Links: environment specific URLs
- [ ] Notifications: Can we tie this into the Status Page?

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-ops/pull/209 started this work by adding a logo.

Notification banners are controled with ConsoleNotification objects. The statuspage bot could easily create those objects in response to PRs.

I don't think we have any specific links we want to add?

**Comment by StevenBarre** [comment]
@mitovskaol Can you please review the available [customizations](https://docs.openshift.com/container-platform/4.2/web-console/customizing-the-web-console.html) for the web console and update this ticket with any additional ones you'd like made to https://console-openshift-console.apps.thetis.devops.gov.bc.ca/

**Comment by mitovskaol** [comment]
It looks good to me , and since nobody provided any other comments I am going to close the ticket.
