### ISSUE TITLE
Create Cluster Configuration Automation Design

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#90]
As an operator of many platforms, I would like a GitOps approach towards managing configuration of each cluster.
- [x] Determine tooling
- [x] Determine flow/logic
- [x] Create implementation plan

**Comment by jefkel** [comment]
Initial tooling ideas:

Ansible as automation tool
 - standalone playbooks?
 - Ansible Tower?
 - Argo-CD?

Github as repository to hold code/documentation
 - Private Repo to start?
 - Existing? or New?

**Comment by jefkel** [comment]
Design meeting scheduled for Jul 21 for next steps.

**Comment by jefkel** [comment]
Justin/Jeff to review for duplication with other CCM tickets.

**Comment by jefkel** [comment]
Completed - see epic #320
