### ISSUE TITLE
Create Multi-Cluster DNS Design

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#97]

**Comment by jefkel** [comment]
- Each cluster will have it's own DNS
- Applications that need to span multiple clusters will need to have their own vanity DNS (and certificates) that points to the BigIP loadbalancer, and that will direct the traffic to the active cluster.

Initial documentation can be found here: https://github.com/BCDevOps/OpenShift4-RollOut/blob/master/docs/design/dns-design.md

**Comment by jefkel** [comment]
Initial documentation has been reviewed, and is expected to be updated as we build the environments.

Closing.
