### ISSUE TITLE
Build and Test Multi-Site Application Deployment Pattern

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/OpenShift4-RollOut#99]
As a user of the platform, I would like to follow some deployment pattern recommendations for deploying a cluster across the Prod and DR sites: 
- [ ] Network Architecture
- [ ] Service Discovery
- [ ] Failover Operations
- [ ] Data Replication
- [ ] Deployment tools

I think we this card should focus on a maximum of 2 deployment patterns at this point in time. Stateless applications and stateful applications with databases.

**Comment by mitovskaol** [comment]
These will be addressed in the the Gold service failover strategy.
